### ISSUE TITLE
Import last played from Steam using localconfig.vdf

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#1016]
I know you said this wasn't possible in #903 to import last played from Steam, but I found out this data [is available in localconfig.vdf](https://stackoverflow.com/a/38042998). There are `LastPlayed` keys for each Steam app under Software/Valve/Steam/Apps in localconfig.vdf

Perhaps add something like this, very similar to [SteamLibrary.GetCategorizedGames](https://github.com/JosefNemec/Playnite/blob/master/source/Plugins/SteamLibrary/SteamLibrary.cs#L433-L443):

```
var vdf = Path.Combine(Steam.InstallationPath, "userdata", id.AccountID.ToString(), "config", "localconfig.vdf");
var localconfig = new KeyValue();
localconfig.ReadFileAsText(vdf);
var apps = sharedconfig["Software"]["Valve"]["Steam"]["apps"];
```

Like GetCategorizedGames, this also needs the user to select their user name to get the right config files. Should this be combined with GetCategorizedGames directly? Users may want to import this data very frequently unlike categories though.

I mocked up a quick extension to test that it works (and see how complicated a PowerShell extension can be):
https://gist.github.com/bburky/31b7d15baef9c1a79770dcff60869086

**Comment by JosefNemec** [comment]
I think this could be implemented the same way as category import, just separately, by adding new button to import last played date. You already have the combobox field there for choosing the account name, so it should be easy.

> Users may want to import this data very frequently unlike categories though.

Hopefully not because if they are using Playnite to start games then there shouldn't be a reason to use it after initial import.

Also we might want to have this info included by default in game import data (from `GetGames` method), in case where user imports game via specific account (not by vanity name).
