### ISSUE TITLE
Allow games to be searchable by aliases

### ISSUE THREAD

**Issue by FireFtw** [JosefNemec/Playnite#1029]
Plenty of games (Leage of Legends, World of Warcraft, Final Fantasy X) are also commonly referred to by just the first characters of each word (LoL, WoW, FFX). Would there be some way to implement this or would results get too messy because of how many games it would return?

**Comment by DennoCoil** [comment]
There's already a Tag system that you can use for pseudo aliases as a work around.

Unless you want the search bar at the top of the screen here to also search the Tags too?  I don't think it would be hard to implement, but search times may be slightly longer since it would have to search through more strings.

![2019-02-20 02_27_19-playnite](https://user-images.githubusercontent.com/21137176/53073901-5585c380-34b7-11e9-8917-f4dae02eae3f.png)

**Comment by JosefNemec** [comment]
I don't know about this, I think it could lead to some confusion why some games are returned by filters unless we would add new field explicitly for aliases.

**Comment by FireFtw** [comment]
If you wanted to avoid another field what about delimiting the "name" field so you could have multiple names for the game?

**Comment by JosefNemec** [comment]
I'm closing this based on my previous comment.
