### ISSUE TITLE
Don't allow metadata download from official store if plugin doesn't support it

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1052]
For example for Epic games the menu entry for downloading metadata from official store is available in the menu even that Epic plugin actually doesn't support it. User will currently get inappropriate error message when using it.

**Comment by samusaran** [comment]
Sorry to hijack the issue but I was curious about why the plugin does not support Epic metadata. Is it because of a lack of support from the store itself? I'm currently building an integration between Keypirinha and Epic Launcher, and I'm taking a lot of inspiration from the Epic Plugin, and I wanted to know if it was possible to get icons for Epic Launcher games.

**Comment by JosefNemec** [comment]
Yes, it's because I was unable to find a reliable way how to match Store data with what Epic Launcher stores locally. Specifically for the game icons I was unable to find where they reference game's executable to take the icon from. Getting installation directory is easy so you could technically guess what the game executable is and get icon from that. But that gets complicated if multiple exes are found in install directory. 

I'm hoping that they will improve their store in future and provide some usable endpoint to get game data easily (like Steam has store web API). That said I didn't do any deep look into the launcher itself, just what I needed to import and launch games.

**Comment by JosefNemec** [comment]
Done in 5.1
