### ISSUE TITLE
Possibility to add manually store(needed for uplay games added manually)

### ISSUE THREAD

**Issue by thetrueavatar** [JosefNemec/Playnite#1080]
Hello,
We have been talking on how to add Uplay Game that are not yet installed. I don't have the time yet but will try in the forcoming month to help you with that. In the meantime, I have added all my uplay game manually but it would be fine if I could manually add them to Uplay store(currently in "Playnite" store) so they are group with the installed one. I guess is not difficult to add this feature for you.
What do you think about it ?
Playnite is THE  cross-store launcher we have been waiting for such a long time so thank you very much for all the works already done !

**Comment by JosefNemec** [comment]
There won't be option to directly add a game under specific library, because the library is defined by the library extension plugin (we should probably change the name from Library to something more appropriate). Allowing users to add game under specific library plugins could cause issues because it would be unknown game to that plugin.

However, there will be major change to how filters work in 5.0 and you will be able to use `Source` field for that purpose (since Source can be changed by user). You will be able to group and filter by `Source` field the same way as `Library` grouping/filtering works now.
