### ISSUE TITLE
Discussion: Adding completion status from external source based on steam userID

### ISSUE THREAD

**Issue by gsabater** [JosefNemec/Playnite#1109]
Hello,

I actively use your launcher, and I love to set the completion status in every game i play.  Is because of this that i did made a website ( https://steam-backlog.com ) where anyone can browse their steam libraries and set the completion status for any game (Also known as the backlog).

I would like to know if it would be possible, and which would be the best way to import the completion status from our website to the launcher, so the user can set the completion status only once, and not two times.

Syncing in both directions would be possible as well.

Thanks for your time

**Comment by JosefNemec** [comment]
I would recommend writing [an extension](https://playnite.link/docs/) for it. One way sync from you website to Playnite should be already doable and our API should provide everything for that already. Sync from Playnite back would be currently problematic because there are currently no game update events exposed in API (to know when user changed the completion status).

There will be improvements to extension API in upcoming 5.0 version that should provide everything needed for bidirectional sync. I would probably wait for that.

**Comment by gsabater** [comment]
@JosefNemec , thanks for answering.
I have zero experience with C# but i will give it a look and think about this.

I will close this issue until i have something to talk about again once i have managed to make the extension.

**Comment by vogler** [comment]
👍 
Also extensions for https://howlongtobeat.com/ and http://www.gamelengths.com/ would be nice.

(@gsabater Just tried https://steam-backlog.com/ and noticed there's no login - had to disable uBlock for the button to appear.)

**Comment by gsabater** [comment]
@vogler Thanks for your comment.
Looks like i can't reproduce this. Do you mind opening an issue on [my repo](https://github.com/gsabater/Steam-Backlog/issues) and describe me what you see (with a screenshot if you can) and what version of ublock do you have? 

Thanks a lot
