### ISSUE TITLE
Better Microsoft Store / Xbox App support

### ISSUE THREAD

**Issue by starquake** [JosefNemec/Playnite#1112]
Are there any plans to support the Microsoft Store?

**Comment by JosefNemec** [comment]
See [this page](https://github.com/JosefNemec/Playnite/wiki/Importing-Windows-Store-games) for information how to import Windows Store apps. Automatic import, like we do for Steam for example, is not possible due to how closed the store is with its data (also there's currently now way how to differentiate between games and standard apps).

**Comment by RyanEwen** [comment]
I know this might be asking a lot but could you use telemetry to build a database of games that people are importing a lot, and then after some review once in a while, add them to a whitelist for auto-import?

Even some kind of community-maintained whitelist would be okay.

IMO this is the one thing holding back Playnite for me and as a result I'm waiting for GOG Galaxy 2.0 (which oddly enough MS has already committed to supporting with an official plugin)

**Comment by JosefNemec** [comment]
Done in `devel7`.
