### ISSUE TITLE
Very nice. One request - Excel Import

### ISSUE THREAD

**Issue by CmdShft4** [JosefNemec/Playnite#1220]
Please use search first to see if the issue is already opened. Thank you
I have my Humble Bundle list in an Excel file (in the cloud) to help me find out if I already own a game (and if it's installed because I have a column for that) when I'm not on my PC. It would be GREAT to be able to import that list into Playnite. Duplicates that are already in my Playnite list could just be ignored.

Thanks, this software is pretty great so far. Great Job. If everything continues to go well, I'll be visiting your Patreon soon.

**Comment by JosefNemec** [comment]
Import from custom data sources is quite tricky and I generally don't wont to hard code such scenarios, because every person's data format can be different. I'm not sure if this is possible for you, but you can write an importer script using our [extension API](https://playnite.link/docs/). That will allow you to import games from any source you want.
