### ISSUE TITLE
Sorting by ascending and descending in desktop mode is inverted

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1263]
![imagen](https://user-images.githubusercontent.com/1389286/61979431-6cc26300-afb9-11e9-832d-379f3ce9558d.png)

Ascending should go from 0-9 and A-Z but as seen in the screenshot, it's inverted.

**Comment by ChildishGiant** [comment]
See I would say ascending is going up Z-A since Z is the bottom of the alphabet, making the current implementation "correct".
![image](https://user-images.githubusercontent.com/13716824/61983050-b41b1480-aff6-11e9-8355-ff209abb7a59.png)
 I think ascending and descending is normally used for numbers, not alphabetical things. Both Google Sheets and Excel use "A to Z" over ascending/descending 
![image](https://user-images.githubusercontent.com/13716824/61983365-fee95c00-aff7-11e9-95e9-53c781f1afe0.png)
![image](https://user-images.githubusercontent.com/13716824/61983385-16c0e000-aff8-11e9-8df2-f9c75690ca95.png)

**Comment by darklinkpower** [comment]
That would make no sense. Why would you want to go 0-9 and then A-Z? How about instead of going up and down order, you think in a left and right sequence? Like 0->1->2... A->B->C.... 

And I'm not making up anything, that's literally what ascending is, if you don't believe me you can use any online text sorter like this one: https://www.gillmeister-software.com/online-tools/text/sort-list.aspx

![imagen](https://user-images.githubusercontent.com/1389286/61985139-7a81e380-afcd-11e9-94fa-d1ea0ba5a2fa.png)

**Comment by jakopo87** [comment]
@darklinkpower is right, Libreoffice calc uses it

![immagine](https://user-images.githubusercontent.com/410331/61991134-194d2500-b04c-11e9-9b55-f0f01af3e439.png)
![immagine](https://user-images.githubusercontent.com/410331/61991139-279b4100-b04c-11e9-85e3-97b48bfb42cd.png)

**Comment by ChildishGiant** [comment]
I guess I was wrong 😋

**Comment by JosefNemec** [comment]
Fixed in 5.5
