### ISSUE TITLE
Metadata cover image not updated when changing aspect presets

### ISSUE THREAD

**Issue by ChildishGiant** [JosefNemec/Playnite#1267]
https://gfycat.com/dampdarlingbedbug
![](https://thumbs.gfycat.com/DampDarlingBedbug-size_restricted.gif)

I think the covers should be redownloaded when switching to and from DVD box/Steam Banner

**Comment by ChildishGiant** [comment]
Oops, it does just needs a restart.

**Comment by JosefNemec** [comment]
Re-download would not work. Unless there's a database that would offer both DVD box style covers and banner style covers, we can't tie the cover dimensions to some metadata source. Plus this is going to be obsolete soon anyways since Steam is moving away from banners and then it's basically just GOG using them (which also is not the case anymore in Galaxy 2.0).

**Comment by doublah** [comment]
Maybe Playnite should provide the ability to locally store multiple images per game and select from different metadata sources (e.g. Steam and IGDB).

**Comment by JosefNemec** [comment]
I don't think that's worth implementing. How often are you going to switch what cover images should be used? This is IMHO one time setup and it's done.
