### ISSUE TITLE
Splash screen cannot be turned off.

### ISSUE THREAD

**Issue by Demiko** [JosefNemec/Playnite#1285]
In newest version a splash screen was added and there's no way of turning it off. It's a highly intrusive behavior when Playnite launches on computer start and it should be at least togglable if not removed entirely as it was before.

**Comment by craigt00** [comment]
@JosefNemec - do you mind me picking up this one?  My intention is to add a new checkbox option to 'Settings.../General' to control this (defaulted to checked to show the splash screen).

**Comment by JosefNemec** [comment]
Splash screen was added because there can now be a noticeable delay before any Playnite window is displayed after staring our executable (due to new theming system). Splash screen gives instant feedback that Playnite is actually starting.

However I agree that it's probably not necessary to show splash screen if Playnite is starting automatically during Windows boot.

@craigt00 Sounds reasonable, it should be enabled by default however.

**Comment by craigt00** [comment]
Hi @JosefNemec  That makes sense to me.  Since it's specifically the splash screen when Playnite runs at startup which is the problem, I won't add the extra option checkbox and always suppress the splash screen in that scenario.  Starting Playnite via the desktop will display the screen as it does now.

**Comment by JosefNemec** [comment]
This was done in Playnite 5.8.
