### ISSUE TITLE
The 'Company' tag under Library Manager is not working well.

### ISSUE THREAD

**Issue by bettafo** [JosefNemec/Playnite#1291]
To begin with, 'Company' does not correspond to any real metadata tags. I suppose it stands either for the 'publisher' or for the 'developer' tag (or for both?).  For consistency it would be better to also have both 'publisher' and developer' available under the Library Manager, rather than 'Company'.

Moreover, Playnite crashes if I try to delete a 'Company' name under the Library Manager, even if I made sure that there was no game associated with the company name that I try to delete.

**To Reproduce**
The following may hopefully help to reproduce the problem:
My installation is portable. I installed version 5.0 (now upgraded to 5.2 through the 'check for a new version' menu) by following the recommended procedure: I made a copy of my old portable installation and pasted the content of the Playnite.zip in the installation directory, replacing all the older files.
I launch Playnite with admin permissions because I noticed that it prevents some other crashes.

My 'Company' list has many duplicated names (in fact almost all names in the list are duplicates) possibly due to having incorrectly pasted a newer game library over an older one while I was trying to give a try to Playnite 5.0beta (similarly to what user NULUSIOS descrived in his 'moving library not working as expected + double entries for everything now' issue). For the same reason the same problem of duplicates existed for other categories too (Genres, etc.) but I successfully corrected those other lists with the Library Manager, by deleting the duplicates that had no associated games. However this does not work with the 'Company' tag and makes Playnite crash.

The way I delete a duplicated name with no game associated is:
1/ I start with renaming one of the duplicates in the Library Manager.
Ex:
Iron Tower Studio --> Iron Tower Studio
Iron Tower Studio --> Iron Tower Studio1
2/ I go to the details view and filter my games using succesively  'Iron Tower Studio' and ' Iron Tower Studio1' for both the Publisher and Developer tags
3/ I delete either  'Iron Tower Studio' or ' Iron Tower Studio' according to which has no game associated
4/ I click 'save' and this is when Playnite crashes if I am deleting from 'Company' (it doesn't crash with other tags like Genre, etc.)

**Diagnostics ID**
10c19ab1-d441-4384-80d8-486229afe393

**Comment by JosefNemec** [comment]
I can see that your library folder is in `C:\Program Files\...`. Are you running Playnite as administrator? The crashes are probably caused because you have library folder in program files, which can't be written to by default without elevated rights.

**Comment by JosefNemec** [comment]
I can see that your library is in `c:\program files\...`, which is why you need to run it as admin (applications don't have write access to it without elevated rights). This is definitely not recommend and I would suggest you move it somewhere else (overall I didn't test how Playnite behaves when running with elevated rights so there might be other issues).

Other crashes are definitely caused by the fact that you copy/pasted one library folder over new. That's also why you get so many duplicates. Every new database instance generates unique IDs for database objects and copying one over another will cause duplication. If you still have backup of one of those libraries then you have to choose and use only that one, don't combine them, that's not supported scenario.

Making separate lists for developer and publishers doesn't make sense because it would introduce many duplicates for cases where developer is also a publisher.

Overall support for merging duplicates will be done via #1270

**Comment by bettafo** [comment]
Thank you.
To move my library I should just copy and paste it somewhere else and then use Settings>Advanced>Database Location>Change to point to the new location, correct?

Cheers

**Comment by JosefNemec** [comment]
Yes, that's correct. Definitely don't copy two library folders over each other.

**Comment by bettafo** [comment]
Thank you.
