### ISSUE TITLE
Library sync since latest update

### ISSUE THREAD

**Issue by leobenkel** [JosefNemec/Playnite#1307]
**Describe the bug**

* Battle.net
* GOG
* Origin
* Steam

are failing to sync since updated to latest version ( 5.3 ).

**To Reproduce**

No idea, just log in and do refresh all. And you get notification about not sync properly 

**Screenshots**

![Screenshot](http://i.imgur.com/Dcb1uFT.jpg)

**Comment by JosefNemec** [comment]
Did you went to settings and re-authenticate? We updated webview component in Playnite 5, which probably invalidated cookies and login tokens. You will need to re-link the accounts in the settings.

**Comment by CptCookies12** [comment]
I'm also having the same issue on a brand new clean install of Playnite 5. 5.2 fixed my Steam login after I had to get an API key, but GOG keeps failing to import and says that I'm not logged in. Origin sort of has this issue but it's possible to get it working.

Going to the Settings to log into GOG again brings me to the login page with a different language than English with no way of changing the page. Origin on the other hand logs in properly after I do it in the Settings and updates properly, just not on first-time setup.

![Playnite DesktopApp_HaeQ60n3kC](https://user-images.githubusercontent.com/53424054/62030004-e49ab400-b198-11e9-86bc-06fd54124cb6.png)

**Comment by JosefNemec** [comment]
@CptCookies12 Can you generate diag. package for me please (from About Playnite). Right after trying authenticating to GOG? Thanks

As far as the language goes, I think it's set based on your geo IP. I don't think I'll be able to change it since we only display what GOG's website shows.

**Comment by leobenkel** [comment]
@JosefNemec yes I went in the settings, uninstalled all the extension, reinstall them and reauthenticate to all. And same behavior

**Comment by JosefNemec** [comment]
One last think you can try is to go Settings -> Advanced and use `Clear web cache`. That will completely clear all old authentication files (it will also log you out of most of the library connections), maybe it will help in your case.

**Comment by CptCookies12** [comment]
@JosefNemec Just restarted from scratch again (no big deal, was a fresh install anyways!) and updated to 5.4 and went through first-time setup again. GOG and Origin still don't login properly on the first-time setup, Steam works fine. Going into Settings and logging in again, Origin works.

GOG has stopped doing the weird language swap on the login page and is now English at all times for me as it should've been, and logging in again now fixes it too. It definitely shouldn't have been an IP-related issue because all my browsers as well as the first-time setup page gave me English like it should have. At least that isn't an issue anymore?

I did make a diag. package from me going through the whole first-time setup as well as the second login attempt that fixed them. ID should be 1af726f4-4786-4d5b-828e-9519cf893f27

**Comment by leobenkel** [comment]
`Clear web cache` solved the issue. Thank you.
