### ISSUE TITLE
hifen messes database search

### ISSUE THREAD

**Issue by JosiasElias** [JosefNemec/Playnite#1336]
**Describe the bug**
sometimes a title with a hifen in it wont return results from IGDB, but as soon as the hifen is removed it works.

**To Reproduce**
It works on:
Castlevania - Vampire's Kiss
E.V.O. - Search for Eden
Joe & Mac 2 - Lost in the Tropics
Lufia II - Rise of the Sinistrals
Blood Omen - Legacy of Kain
Oddworld - Abe's Oddysee (this one gives results but the not the right one, weird)

Does not on:
Contra III - The Alien Wars
Pitfall - The Mayan Adventure
Spider-Man
The Legend of Zelda - A Link to the Past
Legacy of Kain - Soul Reaver

**Screenshots**
https://imgur.com/a/BBf6kG3

**Comment by darklinkpower** [comment]
You are right, I thought that this was an issue with igdb and deleted the dash (TIL it's actually called Hyphen) but I see this is an issue with playnite, since doing the same search on igdb returns results. Or maybe it's an issue with the API? 

![imagen](https://user-images.githubusercontent.com/1389286/62415257-613fef00-b5ec-11e9-962c-3757f710923d.png)
![imagen](https://user-images.githubusercontent.com/1389286/62415259-6ac95700-b5ec-11e9-83a6-de56c8708d4b.png)

https://www.igdb.com/search?utf8=%E2%9C%93&type=1&q=Castlevania+-+Vampire%27s+Kiss

**Comment by JosiasElias** [comment]
hmmm its good that you mentioned it, I did not consider it could be and IGDB API issue. I assumed it was playnite since both "Blood Omen - Legacy of Kain", and "Blood Omen: Legacy of Kain" return the same results in IGDB.
However searching both of these terms in the wiki option in playnite return the game, they both find "Blood Omen: Legacy of Kain", which probably means the problem is in the API, or the way playnite uses it.

**Comment by JosefNemec** [comment]
I've done some testing and it's definitely an issue with IGDB's API, I'll report it to them.

For mass downloads I'll probably remove both colon and hyphen from the search string automatically since that seems to produce best results.

**Comment by JosefNemec** [comment]
Fixed in 5.7
