### ISSUE TITLE
When selecting media, start in game's installation directory

### ISSUE THREAD

**Issue by PopeRigby** [JosefNemec/Playnite#1392]
It's a little annoying to have to navigate to the correct folder every time.

**Comment by darklinkpower** [comment]
In my opinion this would make it more difficult when you are adding media to a lot of games, since you usually download the media to a single folder and add them to the games more quickly since it loads the same folder each time. Opening a different folder each time would make it very messy and more difficult and time consuming since you would need to download media files to different folders.

I could see it useful in an scenerario where maybe Playnite could extract ico image files from executables but only for that.

**Comment by PopeRigby** [comment]
I usually store my media in the game's folder to keep it more organized.

**Comment by JosefNemec** [comment]
I agree with darklinkpower, I think we should keep the default Windows behavior in this case where the dialog opens on last folder that was used.

Just a note to how Playnite handles game media: If you assign media to a game then those files are copied to Playnite's library folder, Playnite doesn't reference the original location and uses copied files.

**Comment by PopeRigby** [comment]
Oh. Ok. Where's the folder located?

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/wiki/Frequently-Asked-Questions
