### ISSUE TITLE
Performance/Enhancement

### ISSUE THREAD

**Issue by shanazzlowe** [JosefNemec/Playnite#1404]
This might be a long shot, because i don't know coding myself. But RAZER has a game launcher and it has a feature that disables all the unnecessary processes in windows when launching a game to improve game performance and then it restarts all the processes it closed as soon as it detects that the game has been closed. Maybe it could be set to where the user chooses what processes/programs close upon launching a game from playnite. I think some playnite users with slower PC's could benefit from such a feature in Playnite

**Comment by cristi1990an** [comment]
I have a Ryzen 3 1200 and I once tried benchmarking all my games while having Discord, Spotify, Steam, Origin, Uplay, GOG, Battle.net, Twitch, uTorrent etc all running in the background. I got at most a 5 fps drop in average frame-rates, so I can pretty fairly say that these kinds of "performance enhancers" are nothing more than snake-oil. The only thing significantly worse were the loading time since uTorrent was eating all the bandwidth.

**Comment by darklinkpower** [comment]
It's not snake oil in this case. In lower end PCs when resources are limited, it will definitely help since it's freeing RAM for the game to use and having programs running in background will eat a little of the CPU and if it's a low resource machine, every little amount will help. You are saying you tested and you got 5fps drop so I'm confused how you can say it's snake oil if you yourself are saying there was an impact.

This will be possible with #113 if you create a script to do this.

**Comment by JosefNemec** [comment]
I don't think we should add this as built-in feature. We would have to keep some whitelist of apps we can safely shutdown, plus a way how to shut them down safely. That's not realistic with how limited resources for Playnite's development are.

I'm closing this since anybody will be able to add this via #113 in Playnite 6.
