### ISSUE TITLE
Better indication that filter is being applied

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1419]
Looks like more and more people are reporting issues that games are disappearing, while they only have filter enabled without realizing it. I'm not sure how it's possible since the filter panel automatically opens if user filters by game field (which should indicate to user that filters are applied), but it's apparently not enough.

We must add some popup or something to make it very clear that some filters were applied and not all games are being displayed because of that.

**Comment by darklinkpower** [comment]
I made some mockups with some ideas that could solve the issue

**Proposal 1:**  Add a little info panel with information of the current active filters in a condensed list. There's no way people won't be aware that there are active filters. It also helps if you are looking at the current game list and don't have the intention to change filters, but want to know which filters are making the current lists. Also helps because when opening the filter list, you have to scroll up and down to view the current filters since you are not seeing all the filters at once. If the active filters are too long and don't fit, the text would end with a `(...)` but when moving the mouse to the panel, it would list all the filters in a tooltip in a non intrusive way.

![imagen](https://user-images.githubusercontent.com/1389286/65016628-5b774200-d8ea-11e9-83b2-8f6639bc41fd.png)

**Proposal 2:** Just little enhancements to the current UI. First I think changing the `(...)` Button to a button that shows more clearly what it does would be a good idea. Regarding the filters, for a while now there color change of the filter icon has not been working, but I think it's still not enough, I propose adding a `"Filters"` text label and also make all the button change color when filters are active and change the label to `"Filters Active"`.

![imagen](https://user-images.githubusercontent.com/1389286/65020045-f889a900-d8f1-11e9-8b81-dca7344ce32f.png)

![imagen](https://user-images.githubusercontent.com/1389286/65020059-fde6f380-d8f1-11e9-8d60-2776ea674032.png)


**Proposal 3:** Add a little info panel showing that filters are active. A boring idea, but thought I should mention at least.

![imagen](https://user-images.githubusercontent.com/1389286/65020073-050e0180-d8f2-11e9-8bb2-ed1715c5af1f.png)


In my opinion I think using both of my first two ideas would make for a better user experience in general and that's what ocurred to me when I read what you want to do, although you may have some other ideas in mind.

**Comment by JosefNemec** [comment]
I like the second proposal best. I have filter enabled all the time (to show installed games only), and other two options would be too intrusive IMHO to have them there all the time.

**Comment by darklinkpower** [comment]
Yeah I agree, forgot to mention that if both of those options are implemented, have the option to disable them in options becase it's taking space that is already used.

Another idea I have that sort of combines the first two proposals, is implementing the second one and have a popup with the active filters appear when hovering the mouse over the filter button. This popup would be just to give information since you wouldn't be able to interact with it.

![imagen](https://user-images.githubusercontent.com/1389286/65064708-9a3ae580-d946-11e9-872a-0daefa1dacd7.png)

**Comment by darklinkpower** [comment]
Another option is adding the text in semi-transparent boxes with a little  blur similar to the new steam library UI

![imagen](https://user-images.githubusercontent.com/1389286/65085633-5e1e7980-d974-11e9-9fb9-7385550244c3.png)

**Comment by JosefNemec** [comment]
I've had another idea and that is to show the number indicator (or some similar icon) like we do for notifications. I think it would be hard to miss that. But then again it could be quite intrusive if you have some filter enabled all the time (like for installed games only).

**Comment by darklinkpower** [comment]
Have you talked to Fren about this? Neither Graphic design or programming is my field, maybe his opinion may prove more valuable in this, but yeah I agree that I woudn't like an annoying icon always active since it's too noticeable, for example, like it happens when the bell icon shows in Playnite when there's an error.

**Comment by JosefNemec** [comment]
@LordFren I know you are busy, but do you have an idea for some quick and dirty solution? Right now I'll probably go with darklinkpower's **Proposal 2**. Showing the text next to the icon with changing color. At least for Playnite 6, we can then implement something more sophisticated in future.

**Comment by LordFren** [comment]
We considered something similar while developing the fullscreen mode, I think it would be a good solution for the problem while we find a better alternative. @JosefNemec

**Comment by JosefNemec** [comment]
Done in 6.0
