### ISSUE TITLE
Inherit metadata from a parent game

### ISSUE THREAD

**Issue by RubeensVinicius** [JosefNemec/Playnite#1448]
Recently the Epic Games Store gave away some Batman games and while it wasn't hard to do, having to copy all the metadata that I added to those games isn't exactly fun. Looks like merging games would be a big task and isn't planned for the near future, so, how hard would it be to make a game inherit or share all the metadata and media from another game, and be automatically updated when something is changed on the parent game?

Maybe adding a checkbox to each field, like when you edit multiple games at the same time, so the user could check the fields that he wants to edit and be ignored when inheriting the metadata. Of course, fields like Library or Game ID would still be unique per entry. Since there's no way to make sure what game is a duplicate, this would be something that the user would need to do manually for each duplicated game.

**Comment by JosefNemec** [comment]
That would essentially mean that we would have to implement game nesting/merging, which has been discussed in other issues already and I currently don't plan to add it due to high technical complexity (you can search the issues for more detailed answer).

You can already write a script extension to copy metadata from one game to another if you need such functionality and Playnite 6 will add an option for custom metadata sources that would allow you to use metadata from different Stores (if somebody writes them as an extension).
