### ISSUE TITLE
Add free-form as a grid preset during setup

### ISSUE THREAD

**Issue by rogersachan** [JosefNemec/Playnite#1467]
**Describe the solution you'd like**
Currently setup only shows the option 3:4 boxes and the old style steam tiles (even though this can be configured to any ratio). Now that Microsoft and Steam are trying to standardize on 2:3 boxes it's getting close to impossible to have all covers meet one style. Having this as a preset would mitigate this for the time being.

**Comment by darklinkpower** [comment]
That's a boxed, 1:1 aspect ratio. Playnite let's you use any aspect ratio, use the following settings to achieve that result, if you don't see that option, try updating Playnite since it must be a very old version. Select "Draw item background" if you want the background behind the covers.

![imagen](https://user-images.githubusercontent.com/1389286/65822927-1fa97a00-e212-11e9-829f-24018a4402b5.png)

![imagen](https://user-images.githubusercontent.com/1389286/65822938-4a93ce00-e212-11e9-8197-4bedae94a4b4.png)

**Comment by rogersachan** [comment]
I'll update my portable version, thanks. I think this should be added as one of the presets though.

**Comment by darklinkpower** [comment]
I don't understand what you mean by free form, but I opened an issue #1468 suggesting new aspect ratio presets to be added.

**Comment by rogersachan** [comment]
@darklinkpower the 1:1 preset is what i mean, so i'll close this issue in favor of yours.

**Comment by JosefNemec** [comment]
You don't need preset to use the ratio, just add 1:1 values manually.
