### ISSUE TITLE
Support import of unsigned UWP apps

### ISSUE THREAD

**Issue by XJIOP** [JosefNemec/Playnite#1475]
UWP Games are visible in Shell:AppsFolder but cannot be imported in Playnite

![Аннотация 2019-09-30 162432](https://user-images.githubusercontent.com/1385503/65888040-2ca7a400-e39f-11e9-8884-6583eb1548cb.png)
![Аннотация 2019-09-30 162504](https://user-images.githubusercontent.com/1385503/65888038-2ca7a400-e39f-11e9-95e7-66725b1897e0.png)

**Comment by JosefNemec** [comment]
I'm not sure why is that happening, FH4 is there on my system. Can you go to "About Playnite" menu and create diag. package for me? Thanks

![image](https://user-images.githubusercontent.com/3874087/65946616-d128f500-e436-11e9-99e6-9b26f9ebf3f0.png)

**Comment by XJIOP** [comment]
For reproduce this you need to register game without windows store. I understand that this is not an ordinary situation, it would be nice if this was supported in Playnite.

**Comment by JosefNemec** [comment]
How do you install game without Microsoft Store (or Xbox App)?

**Comment by XJIOP** [comment]
For install unsigned appx packages on Windows 10, first you need enable Developer mode in Windows settings.
Then install UWP app from PowerShell
`Add-AppxPackage -Path PATH-TO-APPXFILEFOLDER\AppxManifest.xml -Register`

More abut this
https://www.thewindowsclub.com/generate-direct-download-links-for-microsoft-store-apps

**Comment by JosefNemec** [comment]
Why would you install Forza that way and not via official store or Xbox App?

**Comment by XJIOP** [comment]
I don't have a Microsoft account and the Microsoft store has been removed on my PC fter installing Windows.

**Comment by JosefNemec** [comment]
I looked into this more and it looks like this method of installing UWP games is primarily used for installation of pirated versions of games (for example Microsoft doesn't provide any official version of FH4 that could be installed this way). I'm closing this because I don't feel right about supporting this.

You can still add add the game manually and set its Play action to launch `explorer.exe` with appropriate `shell:` argument to launch specific UWP app/game.

**Comment by XJIOP** [comment]
Thanks for explorer.exe this is enough.
