### ISSUE TITLE
Assign background source provider for manually added games

### ISSUE THREAD

**Issue by Stuntaneous** [JosefNemec/Playnite#1556]
**Describe the solution you'd like**
Manually added games are unable to source background images from stores, IGDB, etc. Ideally I'd like to be able to assign a background provider per platform, with the option to override for individual games in their Edit Game Details window.

**Comment by darklinkpower** [comment]
Manual added games can download Background images from IGDB since Playnite 6. It shouldn't make a difference if it was added manually since it only takes into account the game name. Example:
![imagen](https://user-images.githubusercontent.com/1389286/69590987-e6de1500-0fb6-11ea-9cd2-293cd70ece82.png)

**Comment by JosefNemec** [comment]
Yeah as darklink says we already pull images for manually added games. I don't see a point in this feature request anymore.

**Comment by JosefNemec** [comment]
Closing per my previous comment.
