### ISSUE TITLE
Ability to change the default platform where "scan automatically" puts games

### ISSUE THREAD

**Issue by Stuntaneous** [JosefNemec/Playnite#1557]
**Scenario**
Adding games via "scan automatically" drops them in the platform "PC" by default. When this platform has been previously removed, e.g. in favour of a renamed platform called "1. PC" for sorting purposes, the "PC" platform is recreated and the newly added game is inconveniently put in it.

**Describe the solution you'd like**
I'd like to define the default platform for games added by "scan automatically".

**Comment by darklinkpower** [comment]
I don't think this is a good idea, since what you are doing is altering a platform name when it shouldn't be changed to an un-existing one.
You can always use any of the existing grouping and sorting options for that purpose, making use of categories and/or tags,etc to achieve the same result without resorting to a workaround like this.

**Comment by JosefNemec** [comment]
I think this makes sense. However I think this is a low priority since I don't think that many people rename PC platform.

**Comment by JosefNemec** [comment]
No longer an issue since P9. Playnite now assigns existing platform which has "PC Windows" specification assigned to it (no matter platform's name).
