### ISSUE TITLE
Add support for non-steam games shortcuts

### ISSUE THREAD

**Issue by Michoko92** [JosefNemec/Playnite#1580]
Hi,

As you know, Steam allows to add non-steam games to the Steam library (simple shortcuts to executables). It would be very handy to also detect games based on those shortcuts (especially for people who used Steam Big Picture as their main launcher, and added all their games shortcuts to Steam, even non-Steam ones. Transition from Steam to Playnite would be much smoother.)

For your information, here is a small project whose code detects Steam non-games shortcuts to get a list of games and download covers: https://github.com/boppreh/steamgrid

It might be helpful if you want to consider implementing this feature. Thank you!

**Comment by JosefNemec** [comment]
I'm not sure about this. The whole purpose of Playnite is that you don't have to add non-Steam games to Steam, but instead you add them into Playnite directly.

If you need it because of Steam input support then that will be done via #760

**Comment by JosefNemec** [comment]
Closing this based on my previous comment.

**Comment by lyndonguitar** [comment]
> I'm not sure about this. The whole purpose of Playnite is that you don't have to add non-Steam games to Steam, but instead you add them into Playnite directly.
> 
> If you need it because of Steam input support then that will be done via #760
> 
> There's also this: https://github.com/bburky/playnite-non-steam-shortcuts

Hi! just stumbled upon this thread and my main reason is because I have amassed a bunch of non-steam shortcut for my games over the years with Steam. (including classic and emulated games with their own shortcuts not via other third party clients that playnite does NOT detect) . 

My transition isn't exactly as seamless as I have anticipated, as those non-steam shortcuts have no way of transferring to Playnite, unless I manually add them all.

As the original post said
>  (especially for people who used Steam Big Picture as their main launcher, and added all their games shortcuts to Steam, even non-Steam ones. Transition from Steam to Playnite would be much smoother.)

Right now I'm looking for a way to do this. (I really want to transfer to Playnite since its a much better launcher honestly)
