### ISSUE TITLE
Add 'Features' button

### ISSUE THREAD

**Issue by Cyberavater** [JosefNemec/Playnite#1637]
Adding a 'Features' button next 'Play' would provide external settings. In which you could add different feature options; i.e. 

1. Fullscreen (https://westechsolutions.net/sites/WindowedBorderlessGaming/ or https://github.com/Codeusa/Borderless-Gaming) 
2. D3DOverrider > 1.Force Triple Buffering 2.Force Vsync (#1624) 
3. Sizer > All available resolution sizes in dropdown menu ( #1636) 
4. Local Savegame (#1623)

Ticking any of this feature would enable it.
Thanks

**Comment by JosefNemec** [comment]
I don't think that this should be on main game view (near the Play button as you explain), because it's something you would setup once and leave it be. However I think it would be useful to have mechanism to allow 3rd party apps/extensions to provide settings on per game basis (available via game edit dialog).

It's basically #801, so I'm going to close this and specifics from this issue will be taken into consideration when implementing #801.
