### ISSUE TITLE
Özellik İsteği

### ISSUE THREAD

**Issue by vortexpro404** [JosefNemec/Playnite#1667]
Merhaba ,

Playnite adlı programınızı bugün kurdum. Fakat, oyunları "otomatik taradıktan sonra" bazı oyunlar kütüphanede gözükmedi. Bende "ayarlar" kısmına girerek ayarlanabileceğini düşündüm. Fakat, ayarlar kısmında "yüklü olmayan oyunları ekle" seçeneği göremedim. Böyle bir özelliğiniz var mıdır acaba? Yoksa eklemeyi düşünür müsünüz? Sadece "bilgisayara yüklü olan oyunlara" ulaşmak, sinir bozucu olabiliyor. :) Fazla oyun olduğu zaman hepsini elle eklemek zor olabiliyor. Kategori veya otomatik sınıflama özelliğinizi ise, ayrıca sevdiğimi belirtmek isterim. :+1:

**Comment by JosefNemec** [comment]
English please.

From what Google Translate told me you want some "auto scanning" feature. There's already import feature for "Add Game -> Scan Automatically" menu. We can't add non-store games fully automatically (games not installed via official store clients like Steam), because there's no way how to reliably differentiate between games and standard applications.

The same goes for [emulated games](https://github.com/JosefNemec/Playnite/wiki/Importing-Emulated-games) if you setup emulators properly, by scanning game ROMs.

If you can please provide more detailed description in English (if possible not Google Translate since it's rubbish).

**Comment by JosefNemec** [comment]
Closing
