### ISSUE TITLE
Better options for DRM-free game import from Humble

### ISSUE THREAD

**Issue by DotsSalchow** [JosefNemec/Playnite#1676]
Certain games in my library aren't imported.

For clarification: None of the games I have are from the Humble Trove. I had bought most of these games (either separately or through a bundle, though a few I got in free giveaways) long before the Humble Trove service existed.

02a2164b-fb6b-47af-b23c-78b6e5a1b9d0
![playnitetroubleshooting](https://user-images.githubusercontent.com/35101055/75570501-906df000-5a57-11ea-8a5e-f46d4ce664a3.jpg)

**Comment by JosefNemec** [comment]
Do you have "Ignore third party store games" option enabled for Humble integration and are those games distributed with 3rd party keys (for Steam, Origin etc.)?

**Comment by JosefNemec** [comment]
Just a clarification why this is implemented that way. I wanted to minimize duplicates (since we currently don't have a proper way of handling them), so if option mentioned above is enabled, we expect the game to be already imported from the 3rd party service and importing it again would cause a duplication.

I will probably do a small change and allow the option for a game to be still imported if DRM-free version is also available, since you might prefer that one instead.

**Comment by DotsSalchow** [comment]
Yeah, the "Ignore third party store games" option was enabled. I overlooked that option like a complete doofus. :woman_facepalming:

Although yeah, the option for a game to still get imported if it does have a DRM-free installer package would be pretty handy in my case.

**Comment by JosefNemec** [comment]
Done in `devel8`.
