### ISSUE TITLE
Unreal Tournament (

### ISSUE THREAD

**Issue by trillex** [JosefNemec/Playnite#1681]
**Check for existing issue**
N/A

**Describe the bug**
The "Unreal Tournament Pre-alpha" (https://www.epicgames.com/store/en-US/product/unreal-tournament/home) game from the Epic Store shows as the original Unreal Tournament from 1999 in Playnite. I'm unable to get it to choose different metadata to download and removing it and doing a new game update doesn't solve it. 

This is most likely due to it being a pre-alpha and unreleased game that doesn't have metadata available. 

Some of the data is OK, such as description. 

**To Reproduce**
1. Add the game to your account through the Epic store
2. Allow Playnite to update game libraries
3. Check that the metadata for the original Unreal Tournament is downloaded rather than for the new one.  

**Screenshots**
![image](https://user-images.githubusercontent.com/6444691/75607438-7f74bb80-5af7-11ea-95eb-86f57ff6af04.png)

**Comment by JosefNemec** [comment]
Since the game has the same game as original, there's no way to differentiate between them and we currently prefer older entry when automatically downloading metadata.

You can download metadata for correct game manually, by using "Download Metadata" button from dialog you screenshoted and using IGDB as a source. You will get option to choose specific "Unreal Tournament" (2016 one) then.
