### ISSUE TITLE
Group games on Grid view

### ISSUE THREAD

**Issue by RadAd** [JosefNemec/Playnite#170]
It does seem to sort according to the category but doesn't show a title for the group.

**Comment by JosefNemec** [comment]
That's currently by design, it really didn't look great so I've disabled it. It might come back in 3.0 where cover view will be reworked, we'll see.

**Comment by JosefNemec** [comment]
Turns out this this might not be possible. We use custom rendering panel in order to lower amount of memory needed and speed up list loading (we only render visible covers), and it looks like it's not possible to add grouping to custom virtual panels in WPF. At least by looking at WPF code and how they handle it, we would need access to lot of internal methods that we simply can't access.

I could technically disable virtualization if grouping is enabled, but performance would be horrible. I'll leave this open if anybody wan't to have a look at this, maybe I missed something.

**Comment by vannessqn** [comment]
oh too bad, it's the only thing i want

**Comment by jvarnes** [comment]
I would like to revisit this suggestion (started to make a new post and discovered this already existed).

Games in cover view can currently be filtered. My suggestion is a new view mode called Hybrid mode combining a left hand tree view (ala List view) that shows an appropriate list dictated via group by Library / Platform / Category. The right hand pane would be the existing cover thumbnail pane used by Covers view.

This may be easier to show than explain. I mocked these in Photoshop (a picture worth a thousand words and all that):
![playnite_hybrid_mode-1](https://user-images.githubusercontent.com/4473408/51781298-ea79e480-20e4-11e9-8a15-b97987ab9513.png)

![playnite_hybrid_mode-2](https://user-images.githubusercontent.com/4473408/51781413-44c77500-20e6-11e9-8e13-58084fbcf730.png)


In essence instead of an *actual* functioning tree view the left hand list would act as a series of filter links - click a "category name" and behind the scenes Playnite would first clear any existing filters and then apply a filter of that name in the category field. In other groups it would apply the appropriate filter (i.e. in Group by Library it would apply the clicked library's name into the library filter). 

Essentially you are using the filter features in an easy to access method. At the moment it's a bit painful to work with large numbers of games and have it look good and be functional. Playnite's filter features are WONDERFUL (please take pride in what you have done with those), but this would ease a lot of click and type.

While it might be easy to dismiss this issue as only being folks who are outliers and have way more games than most people do (I do have a ridiculously huge library over 1600+ games) - I think this feature would be of VAST benefit to those who have large Platform libraries due emulation. Emulator collectors are notorious for having hundreds to thousands of titles in just one Platform. I can't imagine scrolling through those and trying to organize them in List view... I'm currently struggling with just my PC titles :(

As an aside I'm also hoping you have plans to release Group by Genre, Group by Tag, and (most important to me) Group by Series.

![playnite_hybrid_mode-3](https://user-images.githubusercontent.com/4473408/51781409-3bd6a380-20e6-11e9-9af1-88942b6e47a7.png)

**Comment by JosefNemec** [comment]
I'm planning to do exactly that as part of #305, but the implementation will probably be a bit different. Instead of creating new view type, I will add an option to show the group list (exactly like on your screenshots) that will list all currently selected group items (for example all available genres) and clicking on them will show only items from that group on your selected view.

Also next major version (5.0) will add an option to group by all game fields.

**Comment by Gareth4321** [comment]
+1 for this feature. The way GOG groups by year seems to look and work really well.

![Temp - GOG Group By Year](https://user-images.githubusercontent.com/72940366/96166779-bbda1800-0f1e-11eb-9363-3afef86782c3.PNG)

**Comment by JosefNemec** [comment]
Done in devel9.
