### ISSUE TITLE
Single-login Authentication

### ISSUE THREAD

**Issue by Proxxy0** [JosefNemec/Playnite#1712]
I was unable to find this feature requested in current issues. I know personally I have a lot of my games spread across various platforms, and I found playnite because I was in desperate need to have a way to keep things in order. However, occasionally some of my libraries fail to load or become unauthenticated. 

I was hoping there would be some way to have a sort of "playnite" account that you link your other accounts to, which could then be used to auto-authenticate your other libraries. 

I know this would be especially handy for me to re-authenticate my accounts, or even make it easier to set up playnite on my new computer once it arrives.

**Comment by JosefNemec** [comment]
This is not possible due to how authentication to these services works. Also sometimes login sessions simply expire and you have to re-authenticate, there's no way around it. Also most of these stores don't provide official way of linking their accounts to 3rd party services, which complicates it even more.
