### ISSUE TITLE
Many feature suggestions about layout\image\metadata ect

### ISSUE THREAD

**Issue by planningall** [JosefNemec/Playnite#1856]
I made some contrasting pictures.

![Playnite_suggest_2](https://user-images.githubusercontent.com/37258853/83499537-22badf80-a4f0-11ea-9463-808a2d1821fc.JPG)
![Playnite_suggest_3](https://user-images.githubusercontent.com/37258853/83499548-264e6680-a4f0-11ea-9db5-4301283e4765.JPG)
![Playnite_suggest_4](https://user-images.githubusercontent.com/37258853/83499552-277f9380-a4f0-11ea-8ab0-b216cb465354.JPG)
![Playnite_suggest_5](https://user-images.githubusercontent.com/37258853/83499558-29495700-a4f0-11ea-9e60-c98996745c69.JPG)
![Playnite_suggest_6](https://user-images.githubusercontent.com/37258853/83499560-29e1ed80-a4f0-11ea-869c-a2a2a99c5259.JPG)
![Playnite_suggest_7](https://user-images.githubusercontent.com/37258853/83499565-2babb100-a4f0-11ea-8919-fe69e680789c.JPG)
![Playnite_suggest_8](https://user-images.githubusercontent.com/37258853/83499567-2c444780-a4f0-11ea-8019-7330a3f9016a.JPG)
![Playnite_suggest_9](https://user-images.githubusercontent.com/37258853/83499570-2d757480-a4f0-11ea-991b-acaaea765ecd.JPG)
![Playnite_suggest_10](https://user-images.githubusercontent.com/37258853/83499572-2ea6a180-a4f0-11ea-9e76-02ee2a80ab46.JPG)
![Playnite_suggest_11](https://user-images.githubusercontent.com/37258853/83499574-2fd7ce80-a4f0-11ea-86ad-a80beda28a4f.JPG)
![Playnite_suggest_12](https://user-images.githubusercontent.com/37258853/83499578-30706500-a4f0-11ea-9874-a793baace882.JPG)
![Playnite_suggest_13](https://user-images.githubusercontent.com/37258853/83499581-31a19200-a4f0-11ea-87d6-4ea3ad39e8ad.JPG)
![Playnite_suggest_14](https://user-images.githubusercontent.com/37258853/83499589-32d2bf00-a4f0-11ea-869f-450abfaf6d24.JPG)
![Playnite_suggest_15](https://user-images.githubusercontent.com/37258853/83499592-3403ec00-a4f0-11ea-83d9-1e0c5c986d25.JPG)
![Playnite_suggest_16](https://user-images.githubusercontent.com/37258853/83499594-349c8280-a4f0-11ea-9f1c-0e5a34eae0ec.JPG)
![Playnite_suggest_17](https://user-images.githubusercontent.com/37258853/83499596-35351900-a4f0-11ea-83cd-cafa263be77d.JPG)
![Playnite_suggest_18](https://user-images.githubusercontent.com/37258853/83499602-36664600-a4f0-11ea-8988-37e3c0504e46.JPG)

**Comment by Lacro59** [comment]
I like #15 (extension to #03).
Multi-image & video give a better overview of the game.
The tab support is a good idea. The plugins will can also to add a tab (like achievements).

**Comment by JosefNemec** [comment]
Hi, thanks for suggestions, but multiple of these are already requested or actually implemented. It would save you some time using search first.

1) Not possible, store plugins rely on game IDs and can't be used just for any game. Some generic support can be added via custom metadata plugins.

2) That's already supported when downloading metadata manually. These settings don't make sense for automatic download because that only happens for newly added games that don't have any metadata to begin with.

3) Already requested in different issue.

4) Already requested in different issue.

5) Already supported.

6) Not possible due to limited development resources.

7) Library field relates to library plugin that imported the game, it can't be reassigned. You need to use Source or Tags for this.

8) See 7

9) Can be achieved via custom theme. Drag and drop support would be way too technically difficult to implement while also having theme support.

10) You can adjust size in the settings.

11) That's what "Show game names on Grid view" option does already.

12) This has been brought up multiple times in the past and it's simply impossible to create view that would fit all different kinds of background images. Also, we already add darkening gradient there (at least built-in themes have it), I have no idea why it looks that for you.

13) Already requested in different issues.

14) I'm not sure this will make sense in future, because we are planning to switch to Markdown for description text.

15) 16) 17) Manuals will be added as field that points to a manual file (pdf). Different layouts can be achieved with custom themes (which is their purpose in the first place).

**Comment by JosefNemec** [comment]
I'm closing this based on my previous comment. If you feel that some request is still valid, open separate issue (one per request).
