### ISSUE TITLE
Steam Integration - Hide API Key

### ISSUE THREAD

**Issue by TheTrueCoder** [JosefNemec/Playnite#1891]
**Check for existing issue**
Couldn't find this issue anywhere else.

**Describe the solution you'd like**
Currently, anyone who goes to the steam integrations page on my Playnite can see and copy my accounts API key. To fix this issue the API key box should show *'s instead of the API key to prevent people from using it without permission.

**Screenshots**
Current behaviour
![image](https://user-images.githubusercontent.com/38576090/85217624-f1df1380-b3e6-11ea-854c-c8393add4245.png)

Requested behaviour
![image](https://user-images.githubusercontent.com/38576090/85217632-0c18f180-b3e7-11ea-931b-31dbf5cf88c6.png)

**Comment by shakeyourbunny** [comment]
If somebody has physicall access to your screen other than yourself, you have more pressing issues, really.

Obfuscating the API in the user interface does nothing really, nor does it make any more "secure".  If I really wanna grab it for whatever reason and I'm physically present at your computer, I'd just open https://steamcommunity.com/dev/apikey and chances are very high you are already logged in, thus obtaining (and even changing) this key.

In other news, I could just open this page via javascript in a hidden window and grab its contents, running away.

**Comment by JosefNemec** [comment]
I have no issue changing that filed to "secured" one, but it's not going to improve security that much:
1) The key is still stored unencrypted (there's really no way we can prevent somebody from encrypting it since the Steam plugin is open source).
2) I don't think you can do anything malicious with that key, it's only used for read-only web APIs and most private thing it can show is content of your game library (I'm not sure 100% about this, so please correct me if I'm wrong). Plus you would also need to know user's Steam ID, the key is useless for getting private data without it.
3) As shakeyourbunny mentioned, if somebody has physical access to your PC, then visible Steam API key in Playnite is least of your problems.

Also, I will be reworking Steam sync in future (#1808), to not use Steam API keys at all.

**Comment by spektor56** [comment]
Some people are streamers and viewers can see the screen sometimes... so may not need physical access to the machine

**Comment by shakeyourbunny** [comment]
Why do you open these options if you are (live) streaming? I'm just curious.

Not everything which looks like a "password" is something with which you can circumvent authentication and be able to "hack the account". These tokens have mostly strict restrictions what they may do, 

In this case this grants mostly read-only access to basic metadata, the wishlist and an incomplete list of games the Steam user has licenses for. For details see https://steamapi.xpaw.me/.

You cannot login to a Steam account with this, nor change the credentials nor modify anything with this account.

**Comment by shakeyourbunny** [comment]
I just re-checked the dialog window Libraries->Steam where you can enter the API key. In its current state, even if this is streamed, an attacker would not even be able to use the API key, because it is not displayed fully.

To display and stream this key fully, the streamer has to click into the input box and has to scroll right to the end to display the hidden last part of the token. 

So .... whats the point of "hiding" the API token?
