### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by teconmoon** [JosefNemec/Playnite#1953]
I clicked the play button on a game, which loaded fine, but then when I exited the game I was greeted with a crash report.

Playnite recommended I upload a diagnostics report, which I did under 20d9c230-bd4c-4410-94b8-e05b3f6372f9

![Capture](https://user-images.githubusercontent.com/46909426/89771313-f48bea00-dab4-11ea-8e3a-8beae3eae34f.PNG)

**Comment by teconmoon** [comment]
Sorry, I didn't realize at first that the create diag. package automatically sends playnite everything necessary.

**Comment by JosefNemec** [comment]
I actually prefer if people open GitHub issue since I have some point of contact in case I need more information.

**Comment by JosefNemec** [comment]
The crash occurred because Playnite was unable to read one of its library files. I see that you have library files stored on Google Drive. This has been know to cause issue because Google Drive doesn't handle file updates gracefully and sometimes messes up library files completely. There's nothing I can do about this.

I would suggest to disable Google Drive sync while you are using Playnite and only let it sync files when Playnite is not running.
