### ISSUE TITLE
Have a new section called "Tools"..

### ISSUE THREAD

**Issue by ziplock9000** [JosefNemec/Playnite#197]
.. That opens up apps like nVidia / AMD Driver config, GeForce Experience, RealTemp, OBS, Advanced Combat Tracker, Borderless Gaming etc.

**Comment by JosefNemec** [comment]
Might be a duplicate to #111

**Comment by Evene174** [comment]
I have noticed that many questions related to the integration of Playnite and various programs https://github.com/JosefNemec/Playnite/issues/202
https://github.com/JosefNemec/Playnite/issues/289

Also, many players use third-party software for watching movies, etc.
https://github.com/JosefNemec/Playnite/issues/358

I think that the implementation of each issue on demand will take a lot of time and effort
Just addition of software among the games do not want to, because it looks inappropriate (even with manual sorting), but a separate database and tab with it would look very good:
! [soft1] (https://user-images.githubusercontent.com/26068083/34692716-e4218a36-f4e2-11e7-8155-ca2a5a2e3f26.jpg)

For those players who need controller for these programs - it is easily implemented using the specified Xpadder / Controller Companion
Therefore, Playnite does not need any special implementation for any of similar programs in the future.
In addition, it would be cool to make a little help with a link to a topic on the editor (or excel file), where users would make a list of the most useful programs for the player.

**Comment by psychonic** [comment]
Partially related to this, it would be nice if there were a better way to handle this with regard to Steam library import.

Currently, downloadable Steam apps of all [types](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/steam/steamclientpublic.h#L267) are imported - Games, Demos, Software, Tools, Media. If Playnite's focus is on games, perhaps an option should be made to only import games, or better yet, a selection of types to import in the settings. Otherwise, maybe adding automatic tags based on Steam app type would help there.

**Comment by trymeouteh** [comment]
A tools/misc section would be nice for mumble, parsec and emulator apps themselves so they won't have to be added as a game and show up in your  game library.

**Comment by JosefNemec** [comment]
Done in `devel8`.
