### ISSUE TITLE
Duplicate plugin folder

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#2022]
When you installed a plugin with a different extension.xaml that older version, Playnite create a new folder for it.

Example with my successStory plugin:
I'm added links property in extension.yaml.
The v0.11 & older used the folder SuccessStory_e19bcf3b4090d027d90f39ef7ff733f3 and the v0.12 used the folder SuccessStory_a2f1dbf8524a7c3657eeb2a46519c7a2.

**Comment by darklinkpower** [comment]
The issue is because you changed the name of the extension from "Success Story" to "SuccessStory" and that causes Playnite to detect them as different extensions and not replacing the older version.

![imagen](https://user-images.githubusercontent.com/1389286/94350842-1ebf4a00-0018-11eb-8f6c-4ceaacfe50e7.png)

**Comment by Lacro59** [comment]
Indeed... Thanks.

**Comment by JosefNemec** [comment]
This will be solved in Playnite 8, because the manifest will start including `ID` property. For now, if you change manifest signature, then it's treated as a different plugin (signature is made from Name and Author).
