### ISSUE TITLE
Import uninstalled Windows Store games

### ISSUE THREAD

**Issue by mahgo** [JosefNemec/Playnite#204]
It would be good if the Windows Store could be added as a 3rd party client to detect and add games from

**Comment by JosefNemec** [comment]
You can already add Windows Store games manually, by going to `Add Game` -> `Import installed or from folder` menu. I can't currently import then automatically like I do for other clients, because I haven't found a way how to differentiate between games and other apps (you would end up with Facebook and other apps being imported as well).

**Comment by JosefNemec** [comment]
I'm going to close this because it's not technically possible and I doubt that MS will open the platform.

**Comment by ArtexJay** [comment]
Would it not be possible to differentiate with the games tag/department? So that it would import only apps from the games section from the MS store.

**Comment by JosefNemec** [comment]
This has been added in Playnite 7 via new Xbox plugin.
