### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by DigitalNikki** [JosefNemec/Playnite#2052]
**Describe the bug**
Will not start without downloading images and wasting bandwidth and disk space. Other than the broken xbox plugin, everything worked before 8.1.

**To Reproduce**
Block write access to the images directory to prevent saving images.

**Diagnostics ID**
Not possible as it will not start.

**Comment by JosefNemec** [comment]
Please post requested diagnostics id. What do you mean by downloading images specially?

**Comment by genova447** [comment]
Please excuse me, but isn't this what you're really looking for?:
![image](https://user-images.githubusercontent.com/36210357/96140315-cb7d4080-0ecd-11eb-827a-1879e3c687a0.png)

Disable downloading of images/icons through Playnite, rather than block write-access to the folder at OS/NTFS/idon'tknow-level.
(Disregard if I misunderstand)

**Comment by DigitalNikki** [comment]
@genova447 I tried that first, it didn't stop it.

@JosefNemec There is no diagnostics ID. It doesn't get past complaining about the folder to do anything. This wasn't a problem before 8.1.

**Comment by JosefNemec** [comment]
I don't understand. First you write that you have some issue with image downloads, which indicates that Playnite at least starts, but now you are saying that it doesn't start at all. Please upload `%appdata%\playnite\playnite.log` file.

**Comment by JosefNemec** [comment]
No response, closing.
