### ISSUE TITLE
Add whishlist category and star system to rate

### ISSUE THREAD

**Issue by afox1789** [JosefNemec/Playnite#2078]
Can you add whishlist category and a star system to rate the games? That would be usefull in many ways

**Comment by JosefNemec** [comment]
You can manually create any category or tag for wish list, I don't think it makes sense to specifically create support for wish list since it's just another category.

The rating system uses 0 to 100 system, because that's most universal solution needed because of various metadata sources Playnite could be using for ratings. Star system would be too limiting.

**Comment by JamesFrankel** [comment]
> You can manually create any category or tag for wish list, I don't think it makes sense to specifically create support for wish list since it's just another category.
> 
> The rating system uses 0 to 100 system, because that's most universal solution needed because of various metadata sources Playnite could be using for ratings. Star system would be too limiting.

Rather than limiting, a star system makes rating games much easier and requires less thought. Instead of worrying about whether to rate the game an 81 or 82, you simply give 4 stars. Popular implementations of a star rating system allow a very quick rating where you just hover over the rating area, move the mouse to adjust the number of stars and click to confirm the rating. Just one click to rate a game, vs currently clicking on "edit game properties" and manually typing in a 2-digit number.

Please consider adding a star rating system for quick and easy rating! GoG has it too.
