### ISSUE TITLE
Use steam big picture overlay when started from Playnite Fullscreen mode

### ISSUE THREAD

**Issue by igno2k** [JosefNemec/Playnite#2140]
**Describe the solution you'd like**
Switch to "big picture" overlay for steam games when launching them from Playnite Fullscreen mode. At the moment all games seem to get started with the "Desktop overlay" - regardless of launch mode. 
I think most users of the Playnite Fullscreen mode use a gamepad so all steam games started with it should also switch to "big picture mode".

This could also be viable for other launchers, where a controller optimized overlay exists.

**Comment by psychonic** [comment]
Games launch with whatever mode Steam is running in. I don't think you can force the game to launch in a different mode than Steam is running in with the way that Playnite currently launches the games. You would have to set the SteamTenfoot environment variable on the game process to 1 before the overlay dll is injected. Since Playnite doesn't actually launch the game and just tells Steam to do so, it can't touch the process's environment.

**Comment by darklinkpower** [comment]
This could be achieved very easily for Steam games if it's possible to either start BPM directly on Steam boot without going to desktop mode, in a similar way I do it here using the `OnGameStarted` event: https://github.com/darklinkpower/PlayniteScriptExtensions/blob/master/SteamMiniBlacklist/SteamMini.ps1#L150-L205

If it's not possible to start BPM in this way, it would need to be more complex.

**Comment by igno2k** [comment]
@darklinkpower 
Maybe you could add it to your extension?

**Comment by darklinkpower** [comment]
I just checked and `Start-Process 'C:\Program Files (x86)\Steam\steam.exe' "-bigpicture"` can be used to launch BPM directly. I'll probably rewrite the extension and add that.

**Comment by JosefNemec** [comment]
You could technically write a game script to launch Steam in BPM before the game is started.

I'm going to close this. This is not possible because of the way how Steam supports starting of games externally (via steam:// uri).

**Comment by peter-moran** [comment]
Does anyone know if there is an extension or script that can launch Steam BPM before launching steam games like suggested above?

**Comment by darklinkpower** [comment]
> Does anyone know if there is an extension or script that can launch Steam BPM before launching steam games like suggested above?

There's this option in Steam, have you checked if it works?

![image](https://user-images.githubusercontent.com/1389286/114324318-ffd56080-9aee-11eb-8677-c07c10591850.png)

**Comment by darklinkpower** [comment]
This extension will launch Steam in BPM when a Steam game is launch from Playnite when in Fullscreen Mode, extract and install. I've not tested it, please check if it works. Also be aware that it will need to be updated when Playnite 9 releases.


[Steam_Launch_BPM_1_0.zip](https://github.com/JosefNemec/Playnite/files/6292950/Steam_Launch_BPM_1_0.zip)

**Comment by peter-moran** [comment]
> There's this option in Steam, have you checked if it works?

@darklinkpower I was hoping to find something that would not require me to have Steam in Big Picture Mode at all times but would rather start SBPM right before launching any Steam game in Playnite (and if possible, only do this in Playnite Fullscreen mode, but that is not essential).

It sounds like this is what the extension you sent me should do, but it is not working for me (Playnite version 8.12, tried launching a few different games from Fullscreen Mode and all games launched with standard steam overlay).

**Comment by darklinkpower** [comment]
@peter-moran 
I just tested it and it works correctly. Can you send me your Playnite log to see what is happening? Is Steam launching in desktop mode or BPM? It's launching in BPM for me as intended.

The log is Playnite.log if you use portable it is in the Playnite directory and %AppData%\Playnite\Playnite.log if installed

**Comment by Qhitewolf** [comment]
tried the extension you listed above. At first i had the same problems as peter-moran. Despite installing the new extension and restarting playnite no start in BPM mode from playnite fullscreen mode.

Wanted to make a log for you today, but it works now. perhaps a pc restart was required, not really sure.

But im very happy to report it works exactly as intended now. Games started in playnite fullscreen mode now start in steam BPM and games started in playnite desktop mode start steam in desktop mode.

only small problem i had was steam BPM getting focus after exiting the game instead of playnite fullscreen mode. changed the client auto-close setting in playnite settings to 10 seconds after exiting the game and now its not really a problem.

thanks for your work, darklinkpower!

**Comment by peter-moran** [comment]
@darklinkpower I tried it again, and it is working for me if Steam is closed. Should it work if steam is already open?

What would be really seamless is if it could automatically close Steam BPM, open playnite, and re-open steam in the background.

Is the source code anywhere I could poke around at?

**Comment by darklinkpower** [comment]
@peter-moran Yes it needs to be closed, that's why I needed to check the logs to see what was happening. The extension is just a powershell script and is in your Playnite extension directory https://playnite.link/docs/tutorials/intro.html#1-directory-structure-and-location

I'm not sure if closing Steam if it's running is a good idea but I've updated the script and uploaded it if you want to check it. Here's the relevant part (Although untested): https://github.com/darklinkpower/PlayniteScriptExtensions/blob/pre-playnite9/Extensions/SteamLaunchBPM/SteamLaunchBPM.ps1#L31-L57

**Comment by darklinkpower** [comment]
I just checked and `steam://ExitSteam` is not working for some reason, you would need to close steam via command line instead with the `-shutdown` parameter.

**Comment by JosefNemec** [comment]
Please move this discussion somewhere else. This issue has been closed.

**Comment by Lmaquaire92** [comment]
just a utpdate. I made my own little script  with new option -gamepadui, since I have to pick an account every time I start Steam — I’ve got multiple accounts (wife, kids, etc.). Figured I’d share it in case it helps anyone.

[SteamGamepadUI.zip](https://github.com/user-attachments/files/23020994/SteamGamepadUI.zip)
