### ISSUE TITLE
Make same game available on multiple platforms appear as one entry in our list

### ISSUE THREAD

**Issue by Obigre** [JosefNemec/Playnite#217]
As of now, if you own the same game on multiple platforms and import both of those platforms games, the two iterations of the game will appear as two different entries.
What if Playnite detected these games, and treated them as one, allowing you to choose the platform you want to play it on from the game page or after clicking the Play button ? You could then choose which platform you'd prefer the game to start with in the future.

Why do I ask for this ? Thanks to GoG connect, i currently have many games that i own both on GoG and Steam, and I'm sure others do. For now i hide the duplicate entries of the game, but it would be a treat if I had a little help from Playnite :)

**Comment by JosefNemec** [comment]
I'm not sure about this, since it would be a lot of effort to the backend and UI. There's no way how to detect duplicate games other then to check the game title, which might not be the same. For now I recommend simply hiding one of duplicates. I also can't imagine situation where you would want to start game via Steam one time and via GOG another time anyway.

**Comment by janforster** [comment]
I think this is quite similar to what I was proposing in #76 (with addition of the auto-detection)

**Comment by Obigre** [comment]
Yes, you're right, it's basically the same proposition.

No you're right JosefNemec, i cant think of any common situation in which you'd prefer playing on GoG one time, or on Steam another one. The only cases would be, friends playing online and Steam and not owning the game elsewhere.I was just suggesting being able to switch so that when you chose which platform to pick you're not locked into that choice.
But you might be right, this must be too much of work for something you can basically do already.

**Comment by v00d00m4n** [comment]
Different platforms may have different version. I for example when was messing with patches for Psychonauts had to switch between steam and gog and retail versions to make sure patch compatible between them all. Also Uplay and Steam games has some issues (uplay games like Ghost Recon Wildlands has different uplay id for saves than steam version, so if you run steam version and then uplay saves could be different). But grouping should be optional and there should be selection on start which version is preferable and another option to choose preferable default version (or not choose, in case if choosen default version should start instantly instead of selection window.

**Comment by JosefNemec** [comment]
I'm going to close this. As I said in previous comment, this would be a lot of effort for something that doesn't bring that much of a value.

**Comment by DanDoes** [comment]
@JosefNemec Could automatic-combining be accomplished more easily by leveraging a big crowdsourced database like [RAWG](https://rawg.io/) to get unique game IDs, then comparing the game's listed store pages to filter duplicates?

It has [API](https://api.rawg.io/docs/#operation/stores_list) to see which stores every game is available from: (with URLs!)
![image](https://user-images.githubusercontent.com/6108209/97775184-fb5a5400-1b1b-11eb-8c0a-eef93a81b9af.png)
[(here's some additional api docs, made by users)](https://rawgthedocs.orels.sh/api/#about-rawg-api)


Since you start by importing games from a store anyway, I'm picturing the process as:

(eg, for Steam import:)
1. have Steam game ID/URL
2. look up that game in big database via that store-specific ID/URL
3. get big database's unique game ID
4. use unique game ID to combine duplicates from other stores into one entry

Thus, completely avoiding the problem of different game titles on different stores!
...Would this work?

**Comment by mooock** [comment]
also looking for such feature, i would rather have the possibility to set priority of platforms, and only show one game for the first available platform in the priority list.

**Comment by RakSrinaNa** [comment]
https://github.com/felixkmh/DuplicateHider adds the ability to display only one entry for games available on different platforms.

**Comment by mooock** [comment]
> https://github.com/felixkmh/DuplicateHider adds the ability to display only one entry for games available on different platforms.

omg just what i was looking for. crazy this already was made just as i thought it should be. 

thanks for the link
