### ISSUE TITLE
Option to enable silent launch parameter for external clients

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/Playnite#2226]
**Description**
Add option to libraries to enable/disable silent launch when starting a game.
For example:
GOG: /launchViaAutoStart (although that only does something if GOG wasn't running before)
EGS: &silent=true

**Comment by Evene174** [comment]
I got startup commands for launchers that run their in silent mode, I hope they come in handy:
Battle.net.exe --autostarted
EpicGamesLauncher.exe -silent
UbisoftConnect.exe -uplay_silent
Origin.exe -AutoStart
steam.exe -silent 

It would be really cool if there was an option to automatically run launchers when Playnite runs so that they can update themselves and update games in the background rather than before launching the game.

**Comment by MartinAngelov** [comment]
You can always write a simple powershel script and wrap it as an extension,. Plus they can be started on boot of the os silently by defualt.

**Comment by JosefNemec** [comment]
Not really possible. We don't handle client startup when a game is started. We just open URI to start a game and then it's out of our control. Unless we can force silent launch via URI param (like &silent=true for EGS), then there's nothing I can do about this.

**Comment by felixkmh** [comment]
It does at least work for the GOG Galaxy 2.0 client because games are launched using the .exe instead of a URI. I tried adding the /launchViaAutoStart argument to it and if the client wasn't running before, it causes GOG to start silently without any windows showing up while launching the game. It does not do anything when the client is already running though.
