### ISSUE TITLE
[XboxLibrary] Xbox Game Pass canceled but previously played games still imported

### ISSUE THREAD

**Issue by y0LAs** [JosefNemec/Playnite#2339]
I noticed that after canceling my Xbox Game Pass on PC, Playnite was still showing me the entire library, even if I updated everything and reloaded every game library and plugins.

I then decided to delete them (without hiding them) but when I reloaded the Xbox library, it is still showing games I previously played during the time I had the Xbox Game Pass.

If I go on the Xbox Store page of any of these games, they show up as available on Xbox Game Pass or on purchase, confirming I don't own them.

**Comment by JosefNemec** [comment]
It's because once you play a game form that service, it's get permanently recorded on your account. We don't currently have a support for checking if sub is active so we import all games from your Xbox account.

Also, wrong repository. Please pay attention to what issue template says.

Anyways, subscriptions support will be improved once #2123 is done.
