### ISSUE TITLE
Automatic Update of Add-Ons

### ISSUE THREAD

**Issue by burnpsy** [JosefNemec/Playnite#2580]
I appreciate the addition of the in-program add-on menu in Playnite 9, but there is one somewhat annoying side effect to it. Add-ons now update entirely too often, with at least my setup having multiple add-ons ask for an update several times per day.

I would like to request some sort of settings menu where I can select some/all add-ons to always silently auto-update on next launch.

**Comment by JosefNemec** [comment]
I'm going to close this. I don't think this is a good idea especially since how add-ons can completely break Playnite with broken updates. I think users should be always aware of what they are installing/updating in case issues occur.

**Comment by Raijin56** [comment]
@JosefNemec Could you please consider it again? It is very annoying to have to be updating them manually. Perhaps you could make it opt-in as suggested by a fellow user and show a way to disable the possible malfunctioning add-on outside of running Playnite.

**Comment by brynjolf** [comment]
Please reconsider this, I think the conclusion is slightly flawed. What happens now is when I boot up Playnite which is 2-3 times per month, the process becomes cumbersome.
1. Check for updates for Playnite, usually automatic
2. Download update
3. Install update
4. Restart application
5. Receive 5 + notifications that authentication has failed due to plugins not up to date
6. Update plugins, aka 
  1. Open addon tab
  2. Update every addon button
  3. Download
  4. Install
8. Restart Playnite
9. Login to every 3rd party service that is now broken

The fact that updates from addon can break is for me same risk as not updating. Both can result in broken state. 

So why not try to make it more convenient instead and let the user tackle the possibility of it breaking? The end result is not different. Not updating and updating both can result in breakage.
