### ISSUE TITLE
Remove Games when they are no more present in an External (Plugin) Library

### ISSUE THREAD

**Issue by nosyn00b** [JosefNemec/Playnite#2677]
I post here because I think  it is something  related to how Playnite manages games got form a Libraray Extension, and is not related  with the Library Plugins themselves. 

Currently, removed games from an External Library  are not removed automatically. You have to do that manually (or deleting all games form the Library end reimporting them).

Calling GetGames function, Playnite asks for the list of present games to the External Libraries via the installed Plugins, an the Plugin returns all the present games (or a delta).  New games that are not already present are added to Playnite List.

But if a game that was imported previusly is no more present in the list of returned games from the plugin (it happens for example for expired time-based licences, or for games removed because of problems with the distribution, and many other cases), then the game should be removed also in Playnite List!

At least, this is what I think it should happen.

**Comment by JosefNemec** [comment]
This would be very bad in case user needed to uninstall and then reinstall a plugin. It would remove all games from that plugin and force re-import after new installation.

There's intentionally no functionality in Playnite that would automatically remove games. This is very important because of how 3rd party extensions add/remove/update games and in general interact with the library. Playnite a lot of times don't even know how/what added a game. Therefore this request is a no go for me.

**Comment by nosyn00b** [comment]
Thx for the answer.  I understand your point. So you suppose that the library plugins manage directly the in memory game collection and update/remove their own games? If yes, then is there a way to do that periodically (every n minutes) without waiting for a restart or an explicit update called by the user?

**Comment by dmoreira-cualit** [comment]
@JosefNemec Cannot be that introduced with a toggle? I would appreciate that kind of feature. Maybe just give users the chance to do it or not depending on their needs. Awesome would be something like PLEX does for movies, so all "deleted" games could be marked as "NOT FOUND" or something and the user can either delete them manually, cancel the deletion or just clean the library and all of them will go away. In my case, I have a very big ISO library that I use to update folders and file names and it is a nightmare every time I do some changes to review the paths for each of them. Please consider at least putting a "!" icon if the game doesn't seem to be available anymore.

**Comment by NikoMuffin** [comment]
Playnite has been an absolute godsend for me.  Even though I paid for LaunchBox, I trashed it since Playnite is so lightweight and fast.

> @JosefNemec Cannot be that introduced with a toggle? I would appreciate that kind of feature. Maybe just give users the chance to do it or not depending on their needs. Awesome would be something like PLEX does for movies, so all "deleted" games could be marked as "NOT FOUND" or something and the user can either delete them manually, cancel the deletion or just clean the library and all of them will go away. In my case, I have a very big ISO library that I use to update folders and file names and it is a nightmare every time I do some changes to review the paths for each of them. Please consider at least putting a "!" icon if the game doesn't seem to be available anymore.

That said, I found this thread while asking AI about why Playnite does this. I understand this is a design choice, but frankly it's a bizarre one for those who manage their libraries in the (apparently non-majority) way.

Please can we consider making this an option to remove items from library when deleted? Make it OFF by default and make the user consciously turn it on.  Pretty please with 🍒on top?
