### ISSUE TITLE
9.11: Authentication via built-in browser isn't visible

### ISSUE THREAD

**Issue by bluddy** [JosefNemec/Playnite#2689]
Trying to authenticate GOG or Steam opens up a small Playnite subwindow. This window remains blank, but hovering over it changes the cursor, showing that there are fields to fill and buttons to push. The web view is rendered and works, but isn't visible. In the case of Steam, I was once able to get to a single unresponsive image of the Steam login. Again, the fields work, but the graphics don't update properly.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/87875/144458500-67c29218-4202-4e93-8767-057d07b88061.png">

**Comment by JosefNemec** [comment]
Can't reproduce. Do you have Intel Xe GPU or other newer generation Intel one? If so, please update your drivers, this is a known issue with those: https://github.com/JosefNemec/Playnite/wiki/Known-Issues#integration-logins-dont-work-show-only-whiteblack-screen

You can also try disabling hardware acceleration (not recommend, but if it fixes the issue then it's definitely caused by gpu drivers) or using alternative web view rendering mode. Both of those are available in settings -> advanced -> performance.

Also please attach information requested in issue template in future, thanks.

**Comment by bluddy** [comment]
Um, yeah I have an Intel GPU. Updating and closing the issue.
