### ISSUE TITLE
Start a game like Steam(/Epic/Origin/etc.) does it

### ISSUE THREAD

**Issue by SenseiLeRoof** [JosefNemec/Playnite#2694]
This is with games like Beat Hazard 2 and Slay the Spire in mind. When you start them through Steam, a small menu comes up with some extra options (BH2: Use normal or Unreal Engine version, StS: start with or without mods), but this doesn't happen when they launch through Playnite. I think, if it's possible to implement, this feature would help with the feeling of PN being an integrated launcher.

**Comment by JosefNemec** [comment]
1) Wrong repository. This is all handled individually by each integration plugin.
2) Specifically for Steam this is not possible because Steam simply doesn't show it when a game is launched externally (the same issue happens if you launch a game via desktop shortcut created by Steam).
3) You can configure this manually while editing a game on Actions tab. If you add multiple Play actions, you'll get selection dialog on startup.
