### ISSUE TITLE
Emulator auto-scan folders with `\\` in the path cause duplicate game entries

### ISSUE THREAD

**Issue by matthewbarreiro** [JosefNemec/Playnite#2697]
**Describe the bug**
If an Emulator auto-scan configuration contains the characters `\\` in the Scan folder path, duplicate titles are added every time "update emulated folders" is run for that config. 

**Paths that work correctly (no duplicates)**
`E:\some\path` (local disk)
`Z:\some\path` (mapped network drive)

**Paths that create duplicates**
`\\server\share` 
`E:\\some\path`

**To Reproduce**

* Create a new emulator auto-scan config
* Set the "scan folder" to either a UNC network share (e.g. `\\server\share\`), or a local path with an extra `\` (e.g. `E:\\some\path`)
* run "update emulated folders" -> specific config
* run "update emulated folders" again. Note how duplicates of all ROMs will be added. 

**Screenshots**

**Functional Config - no duplicates**
![image](https://user-images.githubusercontent.com/24529040/144762866-a8336e92-f6a7-4365-913c-ac081d0e0bd9.png)

**Broken Config - Network**
![image](https://user-images.githubusercontent.com/24529040/144762636-f8e4f34a-9cd0-44d3-af80-8eef9ef21404.png)

**Broken Config - Local path with `\\`** 
![image](https://user-images.githubusercontent.com/24529040/144762846-ad897e7d-8f8e-497c-b54d-1781fe2f0acc.png)

**Update emulated folders:**
![image](https://user-images.githubusercontent.com/24529040/144762589-fc15d9dd-49f7-4af3-a835-1c061f5b4b41.png)

**Diagnostics ID**
6b58c976-7ee0-4e09-90bd-e95f0973a9dc

**Other**
Windows 10, version 21H1, OS Build 19043.1348

**Comment by UnionExxis** [comment]
Yeah, I'm seeing this, too.

I'm actually wondering if there is a way to NOT have auto-scan? I actually preferred the older functionality where I could manually scan a folder using an emulator, and I didn't have to set up an autoscan configuration.

**Comment by JosefNemec** [comment]
Auto-scan is disabled by default, if you enabled it when creating a new scanner, then you can disable it from emulator config window, "auto-scan configurations" tab.

**Comment by UnionExxis** [comment]
Right. That's essentially that is what I've done to get around this issue.

But I think the difference is that with the old functionality (if I remember correctly) is that I could go to Add Game > Emulated Game > Scan with emulator, and I didn't have to create a scanner and consequently, a folder path.

Really it's the required folder path that is creating an issue for me because I don't keep all ROMs in a single folder. For some platforms, say "SNES", I'll dump on all the ROMs in that folder. For other platforms, I keep a game in an individual folder, so I like just adding them manually to Playnite.

**Comment by matthewbarreiro-kus** [comment]
The bug I reported occurs on any subsequent scan. So if I add a new ROM to a folder and manually trigger a scan, it will add duplicates for all existing ROMs.

**Comment by JosefNemec** [comment]
Done in devel.
