### ISSUE TITLE
Better Play action handling, allow multilpe Play actions

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#272]
-  Allow multiple game actions to be Play actions
- In case game has multiple Play actions show selection dialog like Steam does
- Allow other actions to count towards play time

**Comment by Keelhauled** [comment]
Any updates on this?

**Comment by JosefNemec** [comment]
The only update is that it won't be in Playnite 7.

**Comment by Deide** [comment]
Multiple play actions that track time is great, however, it would help to allow some dynamic arguments to play actions, so that custom URI (for example `game://<some IP>` to connect to a specific server) can be launched via Playnite.

So maybe something like `Playnite.DesktopApp.exe --start "<id>" --action 1 --arguments "-some args"`, and then those arguments either replace or are added to the Arguments in the Play Action. Though perhaps the actions might be better named than automatically numbered.

**Comment by JosefNemec** [comment]
Done in devel9.
