### ISSUE TITLE
Scrape Metacritic/Steam review scores and add the ability to sort by score

### ISSUE THREAD

**Issue by fuzxi** [JosefNemec/Playnite#273]
For users with large libraries, this would be a great way to find well-received games they may have overlooked.

**Comment by berserkwarwolf** [comment]
It would be nice if there was support for OpenCritic too, MetaCritic is often seen as an easily exploitable and corrupt system.

**Comment by AFaustini** [comment]
OpenCritic and IGDB has rating support in their API.

**Comment by Evene174** [comment]
@JosefNemec  there is a request!
Could you also make a manual addition of the rating for the game? For example, by specifying a link to the desired rating.
For many games, PC versions have a fairly unfair rating:
http://www.metacritic.com/game/playstation-3/grand-theft-auto-iv
http://www.metacritic.com/game/pc/grand-theft-auto-iv


http://www.metacritic.com/game/xbox-one/forza-horizon-3
http://www.metacritic.com/game/pc/forza-horizon-3

Many critics evaluate the port itself, not the game and I think it's wrong.

**Comment by JosefNemec** [comment]
So I did a bit research into this and this is where are we right now:
- OpenCritic has API access in alpha. I'm going to singup for it, but I'm not sure about using API that's not production ready. So it's probably not an option right now.
- MetaCritic has no non-commercial API available so that's not an option.
- User reviews are not available from every store, Steam API doesn't provide it (only aggregated MetaCritic), nor does Origin for example (they don't have user ratings at all)

Really the only place that provides reasonable API and both critic aggregated score as well as user score is IGDB.

So what I'm going to do for 4.0 is add new fields for a game that would allow you to specify your own score as well as critic/users scores. For automatic critic review score I'm going to fetch that from IGDB and for users I'm going to pull it from official store (if available) or from IGDB.

Let me know what you think.

**Comment by Evene174** [comment]
@JosefNemec It would be really cool if the icons of each aggregators(great three: gamerankings/opencritic/metacritic) were in the same style, for example as suggested by berserkvarvolf:
https://github.com/JosefNemec/Playnite/issues/71#issuecomment-333218887 
And the user just manually filled in the field with an estimate.
It would also be cool to have a optional fourth rating - a user's own assessment.

**Comment by JosefNemec** [comment]
In that case there would have to be separate rating field for every critic site, which is something I don't want to do. I'm skeptical about how much use it would got, given that user would have to fill that score manually for every single game (because there's no API for sites you mentioned).

What I want to do for 4.0 is to have 3 fields:
- User Score - your own score
- Critic Score - score from critic aggregator site (for 4.0 taken from IGDB)
- Community Score - community score either from store records (Steam user reviews) or community score from critic sites

For the sake of consistency all of those could be set from 0 to 100 (or none).

In future we could add a feature for users to choose which provider is used for "Critic Score" when there's usable API for those sites.

**Comment by Evene174** [comment]
@JosefNemec It sounds good, but maybe it's worth giving an optional feature to manually set the score with a metacritic for example, instead of IGDB?
IGDB is not quoted in the evaluation plan. For people with a small library - it is unlikely to be difficult to make estimates manually.  Also they will have option with automatically IGDB score, if they don't want to put score manually.

**Comment by JosefNemec** [comment]
You will be able to change all 3 values. The plan is to fetch the data from IGDB and then you can change it if you want.

**Comment by JosefNemec** [comment]
Released in 4.0

**Comment by JosefNemec** [comment]
Released in 4.0

**Comment by Kamek437** [comment]
Any chance of this being updated?
