### ISSUE TITLE
Deadlock using `WebViewBase.GetCookies`

### ISSUE THREAD

**Issue by erri120** [JosefNemec/Playnite#2733]
### Bug Description

https://github.com/JosefNemec/Playnite/blob/3e8b6222e194708152337191467ba7087f297a70/source/Playnite/WebView/WebViewBase.cs#L44-L64

`GetAwaiter().GetResult()` is the perfect recipe for a deadlock and this just happened. I don't know why there is little async in this codebase but if it should continue to be synchronous, `GetAwaiter().GetResult()` is not the solution. Instead the current thread should wait for the task to finish using `.Wait()` and then grab the result from `Task<T>.Result`.

**Comment by JosefNemec** [comment]
Wait and Result will result in the same deadlock. It needs to be offloaded to a separate thread. I'll fix it.

**Comment by erri120** [comment]
> Wait and Result will result in the same deadlock. It needs to be offloaded to a separate thread. I'll fix it.

Not really, `.Wait()` can actually remove the task from the scheduler and execute it inline on the current thread if the task has not been started. If it already started it will just block the calling thread until completion (see docs: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.wait)

**Comment by JosefNemec** [comment]
Btw the reason Playnite doesn't make use of async/await pattern a lot is because the codebase was created back in the day where a lot of dependencies and core framework libs still primarily offered sync methods. Introducing async methods now is huge pain because once you make a method async, the whole call stack/chain has to be async, which is obviously an issue if you have large codebase, it requires a lot of changes.

I do plan to rework this to some point with transition to new .net runtime.

**Comment by JosefNemec** [comment]
> > Wait and Result will result in the same deadlock. It needs to be offloaded to a separate thread. I'll fix it.
> 
> Not really, `.Wait()` can actually remove the task from the scheduler and execute it inline on the current thread if the task has not been started. If it already started it will just block the calling thread until completion (see docs: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.wait)

All of these can deadlock under certain conditions: .Wait(), .Result, .GetResult()

**Comment by JosefNemec** [comment]
Fixed in master.
