### ISSUE TITLE
Ability to set completion status

### ISSUE THREAD

**Issue by eddiestrike** [JosefNemec/Playnite#281]
Just as Plex does, it would be nice if Playnite had a little icon set that shows the status of the game.

Statuses: Played, Unplayed, In-progress and Post-game.

Having a little icon on the actual game posters that show the status really helps to differentiate stuff in the library. Yes I know personally what I've played, but having the little badge helps when browsing for new stuff to play!

Example: https://imgur.com/a/okMI0

POTC poster has no orange triangle at the top, which means it's been watched. I find this really helpful when sorting/browsing.

**Comment by ArtexJay** [comment]
Nice idea, but how would Playnite know when you have finished the game or what stage in the game you are in?
It could have a small badge showing if you opened the game at all or not.

**Comment by JosefNemec** [comment]
@ArtexJay I guess that you would mark the game as finished manually.

**Comment by eddiestrike** [comment]
In plex you would just right click it and "mark as complete" then the triangle/icon would disappear.

**Comment by ArtexJay** [comment]
I think it would be better to manually add the status of the game

**Comment by Ianuarius** [comment]
In https://isthereanydeal.com you can manually set the status and I think that works really well. You can set it to following:

- not played
- played
- beaten
- completed

**Comment by shendrix** [comment]
I think setting the status manually would be good, along with the ability to filter by it. It would be nice to be able to edit it with as few clicks as possible. i.e. Right clicking and selecting from dropdown, rather than going to the main Edit dialog.

In my current library manager, I use the following 'progress' list: Never opened, a couple minutes, played some, played a lot, mostly done, complete.  Admittedly, that's probably a bit overkill.

**Comment by m6sec** [comment]
From what it looks like to me it would essentially be a set of separate, special categories.

**Comment by outsider7a** [comment]
What about also adding a overlay showing the emulator used for the game? or in case there's no emulator use the platform logo.. something like in this site:

http://collectionchamber.blogspot.co.uk/

**Comment by JosefNemec** [comment]
@outsider7a I don't see how is that related to this issue, or maybe I'm missing something.

**Comment by outsider7a** [comment]
@JosefNemec you're talking about adding an overlay to show game completion status so i think it should relate to this.. but maybe i should open a new issue

**Comment by JosefNemec** [comment]
I think it's reasonable for now to have options to set these states:
Not Played
Played
Beaten
Completed

They will not change automatically with only exception when you start the game and it's in "Not Played" state, in that case "Played" will be set. Any other changes will have to be done manually.

"Filtering" based on play time that @shendrix mentions will be possible once #135 is implemented since 4.0 will start counting your play time.

**Comment by outsider7a** [comment]
what do you think about setting to "Playing" instead of Played?, then after X amount of time has passed from "last play time" it changes to Played.

**Comment by JosefNemec** [comment]
I'm not sure if "Playing" falls under "Completion State/Status" category. It might be better to add separate field, some option like "Currently Playing", that you could use to filter out games that you are playing lately or something like that.

Also we currently don't have any system that would be able to change game state in background (based on playtime or other conditions), so changing state from Playing to Played would require a lot of work currently, which I'm not sure is worth the effort.

**Comment by JosefNemec** [comment]
Released in 4.0
