### ISSUE TITLE
Click and drag in top bar of main window randomly fails to move the window

### ISSUE THREAD

**Issue by ElfDestruct** [JosefNemec/Playnite#2832]
### Bug Description

Using any view type, the main window occasionally fails to register a click and drag action on the title/top bar area to move the window to a new location.

### To Reproduce

Repeatedly click and hold the left mouse button on the blank portion of the title bar and attempt to drag the window.  The action fails to register the click perhaps 5-10% of the time.  The issue seems to persist even with overlay apps and programs listed on the known issues page disabled.

### Diagnostics ID

f631dfff-97e3-4c9f-aea1-422d922220cd

**Comment by JosefNemec** [comment]
Nothing I can do about it. That operation is handled by the underlining UI framework we use, it would have to be updated there. We will be updating to new version of the library via #1141, but that's all I can do about it.

Also, I'm unable to reproduce this on my system so it also might be caused by some 3rd party.
