### ISSUE TITLE
Stats Issue with Top Play Time

### ISSUE THREAD

**Issue by networldsystems** [JosefNemec/Playnite#2844]
### Bug Description

I had a question about game stats for my Steam library and of course, Playnite had them for me.  However, when I glanced at 'Top Play Time' I noticed it was incorrect, listing my top game at ~3000 hours.  My top game has ~18159.5 hours (I just checked it on Steam.)

I thought maybe Playnite didn't handle numbers over 9999. NBD - just thought I'd report it.

### Diagnostics ID

4319759c-6875-4f04-903d-c7aafe9ffa5e

**Comment by networldsystems** [comment]
I just looked up my real top game in Playnite and it's listed at 37 hours and hasn't been played sine 2019 (both are incorrect). Not sure what to make of that.

**Comment by JosefNemec** [comment]
It means that you didn't start the game via Playnite since it was first imported. Playnite by default only imports play time once (on initial import) and then you have to keep running the game via Playnite for internal counter to work. If you want to always pull play time from 3rd party service (ignoring internal counter), go to setting and enable "Prioritize play time for supported libraries".

**Comment by networldsystems** [comment]
Thanks. Sorry to bother you.

    On Tuesday, March 15, 2022, 02:51:22 AM CDT, Josef Nemec ***@***.***> wrote:  
 
 


It means that you didn't start the game via Playnite since it was first imported. Playnite by default only imports play time once (on initial import) and then you have to keep running the game via Playnite for internal counter to work. If you want to always pull play time from 3rd party service (ignoring internal counter), go to setting and enable "Prioritize play time for supported libraries".

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
