### ISSUE TITLE
Overlay menu while in game

### ISSUE THREAD

**Issue by fullheartgames** [JosefNemec/Playnite#2849]
### Feature description

This would be a similar feature to steams overlay menu which is triggered by shift+tab or a controller hot key. This could have several useful options such as force closing a game.

### Screenshots

![image](https://user-images.githubusercontent.com/47377550/159108541-57aee7a9-4ca7-4dae-99e4-8070f12250b8.png)

**Comment by JosefNemec** [comment]
#1390

**Comment by fullheartgames** [comment]
> #1390

So is this not being actively worked on? I am really interested in this project and would love to start looking into a solution of just a generic overlay. I am not saying this would be a solution, but I have done something similar before using qt and python.

**Comment by JosefNemec** [comment]
Please read comments in the issue I linked.

**Comment by fullheartgames** [comment]
Okay I did before my follow up question, I was just verifying no one was working on it before I start looking at it. Thanks, great work so far.

**Comment by ZeptoBST** [comment]
I managed to get something equivalent using AntiMicroX & XInputApplicationLauncher.

I set-up AntiMicroX so that when I press Guide+Start, it opens XInputApplicationLauncher.

Within XInputApplicationLauncher, I can launch PlayniteFullscreen.


I also set-up Guide+B to close certain games (mainly emulators) that don't have an ingame quit button.


Projects in question:

https://github.com/AntiMicroX/antimicrox

https://github.com/adamgoon/XInputApplicationLauncher

Note: I made a modified version of XInputApplicationLauncher for a better experience, if anyone is interested let me know.

**Comment by Dr4goonD3mon** [comment]
I say is necesary for fronends, launchbox already have one for emulators it will be very usefull in pc games on playnite so it will have the functionality to force close the game or using plugins like achivements and how long to beat, this will make much beter funtionality.
