### ISSUE TITLE
Launching RPCS3 through Playnite from Program Files causes stuttery, poor performance

### ISSUE THREAD

**Issue by ethansshaw** [JosefNemec/Playnite#2857]
### Bug Description

Had RPCS3 and all my other emulators in a Program Files (x86) subfolder, and every other emulator worked fine when I clicked the "Run as Administrator" checkbox in the properties of the .exe (e.g. with Cemu) until I tried to do the same with RPCS3. For some reason, this program in particular stutters horribly when launched through Playnite and exclusively when launched through Playnite, i.e. launching from command prompt and file explorer both work perfectly. Moving the location of rpcs3.exe to a different folder resolved the issue.

### To Reproduce

Place rpcs3.exe and other necessary files in a folder within Program Files (x86). Launch rpcs3.exe though Playnite, then launch a game though RPCS3.

### Diagnostics ID

84c6435e-169b-4a09-b693-635465bacc12

**Comment by JosefNemec** [comment]
Are you using SuccessStory plugin? Somebody recently reported this on our Discord and they found the issue is casued by SuccessStory's RPCS3 integration. Playnite itself just launches RPCS3's executable and doesn't interact with the emulator in any way, so it must be an extension causing it (most likely SuccessStory).

**Comment by ethansshaw** [comment]
That was me, actually. I was wrong; safe mode did not fix the issue, I got _slightly_ better performance but after launching it through the RPCS3 gui I realized it wasn't even close to the same.
