### ISSUE TITLE
Add way to cancel game launch during OnGameStarting

### ISSUE THREAD

**Issue by mtkennerly** [JosefNemec/Playnite#2930]
### Feature description

My use case for this is:

* During OnGameStarting, try to restore the last known backup of the game's save data (e.g., for people who switch between computers often and use their own cloud sync)
* If restoration fails for some reason, abort the launch

I tried checking the repo/docs/tickets for variations of `StopGame`, `stop`, and `cancel`, but I couldn't find anything for this. Apologies if this functionality already exists and I just missed it.

**Comment by JosefNemec** [comment]
This is realistically not possible to do. Every library plugin would have to support this individually and in most cases it's not possible to gracefully cancel game launch.

**Comment by JosefNemec** [comment]
Ignore my last comment. I thought about it more and it might be possible since I forgot that starting event is actually not called by plugins, but Playnite itself.

I'll add cancel support to the event's argument and if you set it, game's launch won't be passed to plugins anymore and startup will be stopped.

**Comment by JosefNemec** [comment]
Done in devel.
