### ISSUE TITLE
lag after lag takes years to lunch 

### ISSUE THREAD

**Issue by Kratos20191920** [JosefNemec/Playnite#2937]
### Bug Description

makes system slow doesnt mini minimize
ps5 skin lags like hell  to be certain all  the skins lag like hell makes the pc freeze up i have to power it down
another think the app nedds to luch the game fast when i click on it not a million years its fater clicking on a shortcut fix that  both windows mod and full screen an login in other add on accounts is not working  steam epic etc 

### To Reproduce

makes system slow doesn't mini minimize
ps5 skin lags like hell  to be certain all  the skins lag like hell makes the pc freeze up i have to power it down
another think the app needs to lunch the game fast when i click on it not a million years its fater clicking on a shortcut fix that  both windows mod and full screen an login in other add on accounts is not working  steam epic etc  an make the logo smaller or show the controller only make it transplant or something ps make the deamn thing lunch faster 

### Diagnostics ID

f

### Screenshots

![0fda32e68dbddf5e0c511b673d6ec1d6](https://user-images.githubusercontent.com/103535812/170842191-f0b21c11-9b6f-4228-be60-7b62ce49ba95.jpg)

**Comment by JosefNemec** [comment]
I'm sorry, but this is not acceptable bug report. Where's diagnostics ID request from issue template? That request is not there just for fun.

If you are having issues with themes slowing down Playnite, it's an issue with that theme, you need to report it to its author.  
If you are having issues with specific integrations plugin, you need to report it to their authors.

As far as game startup, Playnite adds absolutely minimum delay (in milliseconds). If you are seeing slow game startup, it's most likely caused by some extension. As issues template says, try running Playnite in safe mode to test it.
