### ISSUE TITLE
Automatically download metadata when importing custom games

### ISSUE THREAD

**Issue by CantyCanadian** [JosefNemec/Playnite#302]
It would be nice to have it so, when you import a custom game (my main example being emulated games), you have it so it tries to search and fetch metadata from bigger databases that contains most non-PC games.

Example, I import a Pokemon Red rom. The rom is called Pokemon.Red.[US].[l33th4xor]. Of course, the rom name is not a known game due to the garbage surrounding it, so it requests that you input the game's actual name. You write it, and it fetches the right metadata online.

I know it's somewhat possible since my BOTW rom got the right metadata fetched for some reason. It would be nice to have extra leeway / a system to input a game name so that even custom game have the correct metadata.

(And maybe having a Playnite library where games that doesn't have known metadata can have public-made metadata. Games like OpenRCT2 which is basically Roller Coaster Tycoon 2 v2 would benefit from this. Although, this is a crazier idea.)

**Comment by JosefNemec** [comment]
This is probably not explained properly in Playnite, but you can always download metadata manually after importing your ROMs. Go to main menu Tools->Download Metadata. 

The reason why some of your games have them downloaded is because you've added them during first time configuration process, after which the metadata download is executed automatically.

It is however a good idea to have them downloaded automatically if you import games manually after first time configuration is completed. Thanks for a suggestion.

**Comment by CantyCanadian** [comment]
Thanks, that did solve some of the metadata issues. Although, it would be nice to have a 'skip known metadata' option to reduce the downloading time when dealing with a large library.

**Comment by JosefNemec** [comment]
You can do something like that now by filtering/selecting only games without metadata and choosing filtered/selected games as a target on metadata download dialog. But I agree that it's not an ideal solution.

**Comment by JosefNemec** [comment]
Released in 4.40
