### ISSUE TITLE
Same-resolution covers sometimes vary in visible size

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#3174]
### Bug Description

As seen in the two screenshots, sometimes covers of the same resolution differ in size in the Edit Metadata window. 

### To Reproduce

Here's the 'small' cover: https://www.steamgriddb.com/grid/39702

### Diagnostics ID

8dddf66f-6d14-4241-92f3-193730bbf8c8

### Screenshots

![image](https://user-images.githubusercontent.com/47759676/203500012-db7accb7-80ec-4c71-b46e-144266bd6b69.png)
![image](https://user-images.githubusercontent.com/47759676/203500082-f86fa9e4-ad6c-4077-9a34-a9b4017e76b2.png)

**Comment by JosefNemec** [comment]
I looked into it and it happens if an image provides specific DPI metadata, WPF (UI library we use) will obey by it and render the image based on it. So it's technically a correct behavior.

Solution would be removing those metadata or reencoding the image. I also checked some workarounds that we could do from Playnite's side and I don't like them.
