### ISSUE TITLE
Cover Image Max Size Cache

### ISSUE THREAD

**Issue by trymeouteh** [JosefNemec/Playnite#3175]
### Feature description

I like to use custom covers for my games. I always use the biggest cover images I can find for the cover quality to be as high as possible, especially for future computers and displays which will be large in size 4k, 8l, 16k, etc.

I would like to purpose a feature when when set will cap the cover size in pixels. If a cover for a game exceeds this size, Playnite will take the cover and generate a smaller resolution of that file and store it as "cache".

These cache covers will not be saved when you [import/export your Playnite library](https://github.com/JosefNemec/Playnite/issues/2220). Instead they will be saved in a separate folder and will be updated when the user changes the cover image of a game.

When the users has many large cover images for their games and is using fullscreen mode, Playnite will load fullscreen mode slowly and fullscreen mode itself will be slow. This can be a solution to this issue while allowing users to use high res cover images for their games.

**Comment by JosefNemec** [comment]
This exists in Playnite already, but the cache is in memory only (capped at 100MB at the moment) and cleared with every app restart.

**Comment by JosefNemec** [comment]
Just to clarify why this is done in memory and not permanently on a disk drive. The images are loaded and rescaled in a resolution exactly as they should appear on the screen. This resolution can of course change if you change view settings (zoom, number of columns etc.).

Unless you have very slow CPU, than this rescale operation should be really fast already, plus you can also change to a different scaler in advanced -> performance settings (depending on if you prefer quality over speed and vice versa).

I'll leave this open since having scaled versions in some "permanent" cache would obviously be beneficial if you don't change view settings often.

**Comment by trymeouteh** [comment]
This is not needed. I tested this with the latest version of Playnite and I find fullscreen mode is not slow, nor is switching between display modes.
