### ISSUE TITLE
New Xbox One Series gamepad does not work via USB wireless adapter

### ISSUE THREAD

**Issue by mwisnicki** [JosefNemec/Playnite#3215]
### Bug Description

Latest Xbox One Series gamepad does not work in full screen when connected through USB wireless adapter.
It works via Bluetooth.
Previous model from Xbox One works either way.

I prefer adapter because headset jack doesn't work over BT.

### To Reproduce

https://www.amazon.com/Xbox-Wireless-Controller-Special-Windows-Controllers/dp/B08DF248LD/

### Diagnostics ID

9a688dd4-adb8-4cc6-9ed0-c86e941d5b82

### Screenshots

![image](https://user-images.githubusercontent.com/96032/208061940-71ec5552-2e0b-4ea4-ae48-bd8bf745d1ba.png)

Problematic controller highlighted.

**Comment by JosefNemec** [comment]
I have this exact controller connected through [this](https://www.amazon.com/Microsoft-Xbox-Wireless-Adapter-Windows-one/dp/B00ZB7W4QU/ref=psdc_6469276011_t1_B092QS6HMF) adapter and it works properly, so no idea what the issue is on your side. 

We currently only support controllers that properly work as XInput devices and there's nothing I can do about it until controller support rework is done in P11 via #684

**Comment by mwisnicki** [comment]
Strange, I have the exact same adapter. The controller does identify as XInput as per screenshot, even if with weirdly generic name, and works in other XInput apps/games.

Forgot to mention I'm on Win11.

**Comment by JosefNemec** [comment]
Check if you have the option to accept only primary controller's inputs enabled in Fullscreen mode's settings. Maybe the controller is registered as player 2 when connected via an adapter on your system.

I'm on Windows 10 too, so it's that it doesn't work for you.
