### ISSUE TITLE
Show game platform when downloading metadata manually

### ISSUE THREAD

**Issue by rafaelvasco** [JosefNemec/Playnite#322]
It would be good to show the game platform in the results list from IGDB scrapper. When scraping a GBA game i accidentally selected a PC game cover with the same game name.

**Comment by JosefNemec** [comment]
Do you remember what game was this? IGDB bundles all platforms under one game entry so in theory this shouldn't happen. That also means that showing platform when downloading metadata won't make much difference.

**Comment by rafaelvasco** [comment]
Well, any game. If i go on Edit Game Details, then Media, then Download Metadata, it searches by the game name only, so if the search is "Grand Theft Auto Advance" it'll bring back all Grand Theft Auto games from all platforms. It should search by the selected game platform first, then by the game name.

**Comment by JosefNemec** [comment]
I will have to close this for now. As I said in my previous comment I don't a way of showing multiple platforms entries for a game from IGDB since they are usually under one entry. However as of Playnite 6 we now show the release date for different game entries with the same name (old Doom vs 2016 Doom for example).
