### ISSUE TITLE
Can HDR and Auto HDR switches be added to Playnite?

### ISSUE THREAD

**Issue by shinobiz** [JosefNemec/Playnite#3248]
### Feature description

As we all know, the HDR switch of Win10 and Win11 is very inconvenient to control in the system settings. Can HDR and Auto HDR switches be added to Playnite? Especially in full screen mode. 

Thanks programmer!

**Comment by JosefNemec** [comment]
Already possible using game scripts:
https://www.reddit.com/r/playnite/comments/zs3m3d/config_for_simple_hdr_switching/
https://www.reddit.com/r/playnite/comments/d5yccj/using_powershell_to_switch_to_hdr_mode_then/

**Comment by shinobiz** [comment]
Thank you for your reply. But I still wish HDR Switch was integrated into Playnite, not just via script.

从 Windows 版邮件发送

发件人: Josef Nemec
发送时间: 2023年1月5日 15:34
主题: Re: [JosefNemec/Playnite] Can HDR and Auto HDR switches be added toPlaynite? (Issue #3248)

Already possible using game scripts:
https://www.reddit.com/r/playnite/comments/zs3m3d/config_for_simple_hdr_switching/
https://www.reddit.com/r/playnite/comments/d5yccj/using_powershell_to_switch_to_hdr_mode_then/

**Comment by lscholte** [comment]
@shinobiz Your proposal inspired me to experiment with this change because I have also had a need for this feature since I don't like toggling HDR and using start/stop scripts is more cumbersome compared to a simple checkbox that I can quickly set on each game that needs this.

This is what I created based on your mockup above. I should note however, that I have not put any effort to trying to put this in fullscreen mode, but that's largely because I've had no need for it
<img width="634" alt="image" src="https://user-images.githubusercontent.com/6503344/216218404-41d4522c-0057-47ef-8045-7b8cd047c5c5.png">

Ultimately I did was use this checkbox to create some implicit start/stop scripts that run. The script specifically starts up a C++ program I wrote that uses NVAPI (a library for NVIDIA GPUs) to enable HDR and disable it when the program terminates. It works well for me (it even works correctly if HDR is already enabled in that it won't kill HDR when the game exits), but as it is, I'm not sure this is the type of thing I could put in a PR in its current state. The main problem is my reliance on an NVIDIA library which limits who this is useful for.

**Comment by shinobiz** [comment]
> @shinobiz Your proposal inspired me to experiment with this change because I have also had a need for this feature since I don't like toggling HDR and using start/stop scripts is more cumbersome compared to a simple checkbox that I can quickly set on each game that needs this.
> 
> This is what I created based on your mockup above. I should note however, that I have not put any effort to trying to put this in fullscreen mode, but that's largely because I've had no need for it <img alt="image" width="634" src="https://user-images.githubusercontent.com/6503344/216218404-41d4522c-0057-47ef-8045-7b8cd047c5c5.png">
> 
> Ultimately I did was use this checkbox to create some implicit start/stop scripts that run. The script specifically starts up a C++ program I wrote that uses NVAPI (a library for NVIDIA GPUs) to enable HDR and disable it when the program terminates. It works well for me (it even works correctly if HDR is already enabled in that it won't kill HDR when the game exits), but as it is, I'm not sure this is the type of thing I could put in a PR in its current state. The main problem is my reliance on an NVIDIA library which limits who this is useful for. This is also my first time dabbling into the source code for Playnite.

It looks very nice. It would be great if it could be included in the official version of Playnite, and it would be perfect if it could support full screen mode, because most of my game time is spent on the couch.

**Comment by lscholte** [comment]
Ok I worked a bit more to add this HDR option to the game context menu for both desktop and fullscreen mode. Rather than a checkbox like you showed in your mockup, I followed the pattern used for hiding/favouriting games and used enable/disable HDR. Ideally I'd like to have icons for these context menu options, but what I have right now at least gets the functionality there.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/6503344/216263865-0a825c60-3941-4f7e-a523-733e96380fcc.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/6503344/216264015-2052af5c-f155-4068-84d8-2c2ad60af436.png">


But as I mentioned previously, the underlying mechanics of enabling HDR is still using an NVIDIA-centric approach which would need to be generalized I were to put a PR up.

**Comment by lscholte** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/6503344/216542317-80782a61-771e-4cba-8d9d-0ccf1a4eade7.png">
I added an icon for it, although it's the same icon for both enable and disable. Not sure if it's the best option, but it's better than nothing I guess. At least as far as I am concerned now, the UI aspects of this are done, so the only thing left for me to really focus on is the underlying functionality for toggling HDR -- what I have now works for me, but it's a bit hacked together.

@shinobiz Also, can you clarify what you meant by supporting multiple games? Were you intending to play several games simultaneously? Or did you mean toggling the HDR setting for multiple games in a single batch operation? If the latter is what you meant, then I'd expect that to be working. If you meant the former, I'll need clarification on what your use case is.

**Comment by shinobiz** [comment]
> <img alt="image" width="552" src="https://user-images.githubusercontent.com/6503344/216542317-80782a61-771e-4cba-8d9d-0ccf1a4eade7.png">
> 
> I added an icon for it, although it's the same icon for both enable and disable. Not sure if it's the best option, but it's better than nothing I guess. At least as far as I am concerned now, the UI aspects of this are done, so the only thing left for me to really focus on is the underlying functionality for toggling HDR -- what I have now works for me, but it's a bit hacked together.
> @shinobiz Also, can you clarify what you meant by supporting multiple games? Were you intending to play several games simultaneously? Or did you mean toggling the HDR setting for multiple games in a single batch operation? If the latter is what you meant, then I'd expect that to be working. If you meant the former, I'll need clarification on what your use case is.

Sorry, my English is not good, there is a problem with the expression, which made you misunderstand. I mean the latter.

Regarding the switch recognition of HDR, I suggest adding a check box behind it as a reminder. It's even possible to indicate the status on the cover, so there's no need to check menu settings.

**Comment by lscholte** [comment]
I polished up my work and also switched to a more generic approach using Windows APIs rather than NVIDIA. There is a pull request up for this, so we shall see what happens with that. https://github.com/JosefNemec/Playnite/pull/3290

**Comment by lscholte** [comment]
@JosefNemec You should be able to close this issue now.

**Comment by SHOT1M3** [comment]
Can we get a setting in Playnite to set this toggle to 'default on' for all games?

Reasoning:
Almost all the games I play support some level of HDR now, I really only want to disable it for specific games.

**Comment by lscholte** [comment]
> Can we get a setting in Playnite to set this toggle to 'default on' for all games?
> 
> Reasoning: Almost all the games I play support some level of HDR now, I really only want to disable it for specific games.

What you want can probably be accomplished with extensions. Specifically, what I am doing is using the PC Gaming Wiki metadata provider. This will tag games that support HDR. Then from that, I wrote a PowerShell extension to auto enable HDR for those games. I could look into sharing that extension if it meets your needs as well.

**Comment by Emil-Va** [comment]
> > Can we get a setting in Playnite to set this toggle to 'default on' for all games?
> > Reasoning: Almost all the games I play support some level of HDR now, I really only want to disable it for specific games.
> 
> I could look into sharing that extension if it meets your needs as well.

I was trying to look through the comments here and in the #3290, but can only see sections been deleted.
Has this project completely halted and been discontinued? Just started looking up an addon or extension for this, and while I haven't tried out the references to the reddit-posts above; this looked very intriguing.

Could you share the PowerShell extension you created, please? @lscholte

**Comment by JosefNemec** [comment]
No the project is not discontinued and this was added a built-in feature as you can see in that pull request you linked.

**Comment by Emil-Va** [comment]
> No the project is not discontinued and this was added a built-in feature as you can see in that pull request you linked.

Oh, sweet. Not familiar enough with github to wrap my brain around the entire section. Got me confused. And I couldn't find the same options which were referenced in the screenshots. But from what I understand now, by hitting Edit on a game, going to the Advanced-tab you can there choose to activate HDR support immediately on launch.

Effectively having SDR, turning off autoHDR, launching titles in Playnite which have HDR support enabled, and it will basically autoHDR from the getgo?

**Comment by Emil-Va** [comment]
I'll go ahead and answer, and say. I've read it, I've understood it, and it now makes a lot more sense. Thanks for replying, and clearing out, Josef. And thanks to you all for the implementation. Woop woop

**Comment by SHOT1M3** [comment]
Auto-HDR is enabled on more games then not these days, thats aside from native HDR. So I think we need to starting assume HDR works more often then not. Playnite only handles the reverse scenario right now. We should be able to set it to assume HDR by default and disable HDR for specific legacy games that don't support it.

**Comment by lscholte** [comment]
@SHOT1M3 I can't say that I agree with the suggestion. Firstly, Auto HDR is a Windows 11 feature. And secondly, I would imagine there are many people who don't want to use Auto HDR and would rather only use HDR for games that natively support it. I think the suggestion you are making is getting into the territory of being better served through extensions.

**Comment by lscholte** [comment]
@SHOT1M3 @Emil-Va I put the extension I created for automatically enabling HDR on games that have support for it. You can get it from https://github.com/lscholte/PlayniteDetectHdr. Do note that the extension is designed to work with the PCGamingWiki Metadata Provider extension as that is capable of determining which games have support for HDR, which my extension then uses in order to enable HDR. Also note that if there are certain games which have support for HDR but you don't want to have HDR enabled automatically (e.g. you think the HDR implementation is worse than just using SDR), then my extension will not be helpful for you because it will keep re-enabling HDR. But if you have the technical expertise, the source code is there so you can try to modify it to fit your needs.

**Comment by SHOT1M3** [comment]
> @SHOT1M3 @Emil-Va I put the extension I created for automatically enabling HDR on games that have support for it. You can get it from https://github.com/lscholte/PlayniteEnableHdr. Do note that the extension is designed to work with the PCGamingWiki Metadata Provider extension, as that is capable of determining which games have support for HDR, which my extension then uses in order to enable HDR. Also note that if there are certain games which have support for HDR but you don't want to have HDR enabled automatically (e.g. you think the HDR implementation is worse than just using SDR), then my extension will not be helpful for you because it will keep re-enabling HDR. But if you have the technical expertise, the source code is there so you can try to modify it to fit your needs.
> 
> EDIT: I am working towards just getting this submitted into the add-on browser.

A great tool, however I would need it to also adapt to games that support Auto HDR. Auto HDR is generally better then SDR and available in more games then not.
