### ISSUE TITLE
Can I adjust the order of the filter names myself?

### ISSUE THREAD

**Issue by shinobiz** [JosefNemec/Playnite#3253]
### Feature description

Seems like it always sorts filter names alphabetically

**Comment by darklinkpower** [comment]
I'm not sure what you mean, do you mean the sorting order? If that's the case, it can be changed using the Sorting Settings button

![image](https://user-images.githubusercontent.com/1389286/210938173-863c682e-745f-46e3-80ea-a3b4c2010679.png)

or in the filter panel in Fullscreen Mode

As a suggestion, I recommend to join the Discord server if you can as it's a better place to ask support questions there since GitHub is more intended for feature requests and bug reports https://discord.gg/BrtABqe

**Comment by darklinkpower** [comment]
If you mean changing the order in that submenu then it's not possible to change the order

**Comment by shinobiz** [comment]
> If you mean changing the order in that submenu then it's not possible to change the order

Sorry, my English is not very good.

I mean to adjust the name order of the filters on the right side in desktop mode, since I'm using a PS5ish theme, it affects the name order of the quick filters at the top of the fullscreen theme.

**Comment by shinobiz** [comment]
> If you mean changing the order in that submenu then it's not possible to change the order

Sorry, my English is not very good.

I mean the order adjustment of filter custom names on the right side in desktop mode. Since I'm using the PS5ish theme, it directly affects the quick filter name order at the top of the theme. However, the order is not what I expected.

Sorry for my internet problem, I can't upload schematic pictures, I hope you can understand what I'm talking about.

**Comment by chocolatechipcats** [comment]
> I mean the order adjustment of filter custom names on the right side in desktop mode. Since I'm using the PS5ish theme, it directly affects the quick filter name order at the top of the theme. However, the order is not what I expected.

Sorts alphabetically; adding a number to the beginning should work.

**Comment by JosefNemec** [comment]
Will be done via #2510

**Comment by shinobiz** [comment]
> Will be done via #2510

It's awesome and I'm looking forward to it!
