### ISSUE TITLE
Converting playtime from hh:mm to dd:hh:mm

### ISSUE THREAD

**Issue by karlroush** [JosefNemec/Playnite#3312]
### Feature description

Currently the playtime displayed in the Library is formatted as hours:minutes (e.g. 25h 10min).
I am proposing it be changed to days:hours:minutes (e.g. 1d 1h 10min).

This can be accomplished by changing "PlayTimeToStringConverter.cs". I'd love to add my code to contribute, but I don't know how to make a pull request for the modifications to this file.
https://github.com/JosefNemec/Playnite/blob/3dcfe90f7a2b307769496c3a94622ed0e9ba51ef/source/Playnite/Converters/PlayTimeToStringConverter.cs

add on line 22 
`private static string LOCPlayedDays;`

Then replace lines 57-64 
````
var hours = minutes / 60;
if (hours <24)
{
	return string.Format(LOCPlayedHours, hours, minutes - (hours * 60));
}

var days = (hours-hours%24)/24; //eg (49-49%24)/24 -> (49-1)/24 -> 2 days
return string.Format(LOCPlayedDays, hours%24, minutes - ((hours%24) * 60))
````

I'm not sure how this impacts string.Format though since I'm doing this just off the top of my head.

**Comment by darklinkpower** [comment]
If implemented, the modification should be configurable in settings instead of changing and making it the default behavior so it would require more changes. I think it should go below the settings here in my opinion:

![image](https://user-images.githubusercontent.com/1389286/220512778-432ed94c-0a18-4fc2-97dc-f7c075dc05e5.png)

**Comment by JosefNemec** [comment]
Done in 10.10
