### ISSUE TITLE
Export tags.

### ISSUE THREAD

**Issue by Richard-D81119** [JosefNemec/Playnite#3361]
### Feature description

Export tags. To the clipboard with the ability to set the order in the template. Like what is done in Musicbee or similar players. So that later it can be exported, let's say to Excel or somewhere else, and get a list / table.

**Comment by JosefNemec** [comment]
There are no plans to add any native exporting feature because people usually have individual and very specific requirements for resulting export, making it hard to provide such functionality in an universal enough manner. 

You can either use some exporting plugin, like [this one](https://playnite.link/addons.html#LibraryExporter_54bf64c6-c453-4cbc-92f8-4960b56f930e) or write simple exporting extension/script yourself.

**Comment by Richard-D81119** [comment]
Thank you very much, just what you need.
