### ISSUE TITLE
Playnite Desktop is always starting in the non-maximized window after the recent update. 

### ISSUE THREAD

**Issue by limodual** [JosefNemec/Playnite#3392]
### Bug Description

After I updated to the recent 10.15 ver and launch the Playnite Desktop App, It always starts in the non-maximized window taking only like 1/3rd of the screen, I either have to click on the Maximize button or to double left click on top of the Playnite window to make it maximized. 

### To Reproduce

1. Update to the Playnite 10.15 version 
2. Run the Playnite Desktop App 

### Diagnostics ID

NA

**Comment by brh150** [comment]
I've noticed that, too. Though minimize, maximize and close buttons misbehave for me right after start in non-maximized window. "Minimize" does nothing, "maximize" only changes its icons and "close" causes black window instead of closing/minimizing do tray. Then I have to click "open playnite" from tray icon and all start to work as it should.

**Comment by purple512** [comment]
Came here to report the same thing. This drives me crazy. It worked fine before.

**Comment by JosefNemec** [comment]
Fixed in 10.16
