### ISSUE TITLE
Battle.net game import

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#34]
Full battle.net account sync is too complicated, but we could at least add support to automatically import installed games.

**Comment by ziplock9000** [comment]
Another vote for this.

**Comment by outlawzgosu** [comment]
A current manual workaround you can do for now is: 

-add a new manual game. -select the Actions tab -hit "Add Action" -set type to URL -type "battlenet://D3/" in the "Path" text box.

To add other games, do the same except replace the path with one below:

Hearthstone: battlenet://WTCG/ 
Diablo 3: battlenet://D3/ 
Starcraft 2: battlenet://SC2/ 
World of Warcraft: battlenet://WoW/ 
Heroes of the Storm: battlenet://Hero/

Your Bnet launcher has to be open for this to work, otherwise the shortcuts will just open the bnet launcher.

**Comment by JosefNemec** [comment]
Or you can also go via "Import Installed or from Folder...", pick Blizzard games from the list and they will import with all paths and icons set already.

**Comment by judge2020** [comment]
Problem with Blizzard games is that running from the straight EXE will just open the bnet launcher instead of the game.

Also, overwatch URI: battlenet://Pro/

**Comment by JosefNemec** [comment]
Lots of people are requesting this, but I don't have a time to get this to 3.0 If you guys want to help then find where Battle.net stores information about what games are currently installed. That would help me a lot to get this feature done sooner and it would at least allow Playnite to import installed games if not whole library. Thanks

**Comment by outlawzgosu** [comment]
Are you looking for a list that has the current installed blizzard games to be in or would the registry work? Blizzard stores a few registry entries that are always created when a game is installed, and removed when the game is uninstalled. 

These are the games I was able to test this on, since they're the only ones I have installed. 
Bnet Launcher games:
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\StarCraft II
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Diablo III
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\World of Warcraft
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Overwatch
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Heroes of the Storm

Standalone games:
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Starcraft
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Warcraft III
- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Diablo II

I'm unable to test Warcraft 1 or warcraft 2

I don't know what you would need to do on the programming side, I guess add an 
"import blizzard games" button and do a check to see which of the games' registry entries exist (playnite would probably have to have a list of blizzard's games somewhere).  If the entry exists then add it to the game list. Blizzard doesn't have that many games so the list can be updated after a new game comes out. 

I don't know how you would launch the game though since you can't do it through the EXE. The EXE will always open the launcher, even if you already have the launcher open. It would have to be through the URL method while the blizzard launcher is open. I'm completely guessing on what you need to do to make this work though so don't take my advice that seriously.

**Comment by JosefNemec** [comment]
I guess I could check it via those `Uninstall` keys, but I would have to hard code it for each game. I was looking for something that would give me a list of apps, preferably including those ids that go into `battlenet://{id}/` url.

**Comment by JosefNemec** [comment]
Found it, you don't have to look anymore :)

**Comment by ziplock9000** [comment]
If this suggestion only works for installed Blizzard games then it's not worth bothering about since the rest of Playtime works for uninstalled games. You'll have mismatched functionality otherwise

**Comment by JosefNemec** [comment]
UPlay integration also works only with installed games. I wouldn't say it's not worth it.

**Comment by KIPdeKIP** [comment]
FWIW [Hearthstone-Deck-Tracker](https://github.com/HearthSim/Hearthstone-Deck-Tracker) is able to launch Battle.net followed by Hearthstone from a single user click. Could their implementation be useful?

(Guessing they also have some way to detect if HS is installed but I haven't found it yet.)

**Comment by judge2020** [comment]
@KIPdeKIP btw, HDT just assumes you have HS installed :P (and we use battlenet://WTCG to launch it)

**Comment by JosefNemec** [comment]
Released in 2.7
