### ISSUE TITLE
Remove install button for games that can't be installed.

### ISSUE THREAD

**Issue by HerrKnarz** [JosefNemec/Playnite#3421]
### Feature description

Every game in Playnite that isn't installed shows an install button instead of the Play button. But often those games simply can't be installed, be it because the Library extension doesn't provide an install feature (for example for console games) or the game was added manually without an executable. It would be great, if there was an option to hide the install button for those games.

To add that feature, the installed field would need to have the possible states: "Installed", "not installed" and "can't be installed". Libraries without install feature and manually added games should automatically set it to "can't be installed". A second option would be to add a new field "installable", that should only be true, if the game really can be installed through the install button.

Additionally it would be great, to allow to manually add an Install feature to those games, maybe via pointing to an install.exe or script, that would start the installation.

**Comment by JosefNemec** [comment]
Defying what game can or can not be installed is not simple because you could have additional plugin installed that would provide installation functionality.

Lets say you have plugin A that imports a game, but can't install it. Then you can have also plugin B installed which could install the game. When you click Install, Playnite asks all plugins whether they can provide install functionality for specific game and if any plugin responds positively, Playnite will use that plugin to install the game.

We could technically do this check even before you click Install, but I'm not sure it's worth it.

> Additionally it would be great, to allow to manually add an Install feature to those games, maybe via pointing to an install.exe or script, that would start the installation.

There's already an issue open for that.

**Comment by JosefNemec** [comment]
Closing per my last comment.
