### ISSUE TITLE
Add new default completion status for games that can't be beaten

### ISSUE THREAD

**Issue by Sprabuni** [JosefNemec/Playnite#3463]
### Feature description

Is it possible to add a new default completion status for games that can't be beaten? Name it something like "Endless", "Unbeatable" or "Infinite". Multiplayer and roguelite/roguelike games would fit in this category. The reason I would like a new default completion status to be added is so it can be supported by themes that use icons for completion statuses like eMixedNiteMC and Seaside.

**Comment by telorand** [comment]
Do you mean the capability to add a completion status, like what's found at: "Menu > Library > Library Manager > Completion Statuses > Add"?

**Comment by Sprabuni** [comment]
No, I know you can add custom ones, but any themes will only have custom icons for the default completion statuses (Abadoned, Beaten, Completed, Not Played, On Hold, Plan to Play, Played & Playing). I want to add a new default completion status that will be part of the default Playnite installation. Since it will be uniform across all installations (unless people manually change it), it can easily be supported by themes that add custom icons for completion statuses.

**Comment by FedericoSteidl** [comment]
The issue here is that what counts as "incompletable" is different for everyone, which makes is too difficult to implement/standardize.
You might consider a multiplayer-only game like CS:GO that has achievements to be completable. I don't.
That's the reason I just do it manually and there really aren't that many, truly incompletable games.

This would be neat to have, but it's way too niche to develop and maintain for now.

**Comment by JosefNemec** [comment]
You can already add any completion status you want and I don't think this new status would clearly specify what it's mean to be used as people can interpret it differently. In my opinion current default list we have is more than enough for "built-in" completion status list.
