### ISSUE TITLE
Xbox 360 controller is not working.

### ISSUE THREAD

**Issue by taobingqing** [JosefNemec/Playnite#3512]
### Bug Description

After connecting Xbox 360 to the PC, the controller does not navigate the bottom menu in full-screen mode on Playnite. However, the controller works fine in games. Could it be an issue with the controller? What model of controller should I buy, and could you provide a purchase link?

### Diagnostics ID

Xbox 360 controller is not working.

**Comment by JosefNemec** [comment]
360 controller should work just fine since it's an [XInput](https://github.com/JosefNemec/Playnite/wiki/Gamepad-Controller-support) controller. Make sure you have XInput support enabled in input settings (is by default). Also try disabling primary controller only option in case you have multiple controllers connected.

**Comment by taobingqing** [comment]
> 360 控制器应该可以正常工作，因为它是[XInput](https://github.com/JosefNemec/Playnite/wiki/Gamepad-Controller-support)控制器。确保您在输入设置中启用了 XInput 支持（默认情况下）。如果您连接了多个控制器，还可以尝试禁用仅主控制器选项。
Could it be that the one I bought is not genuine, so it doesn't support Xinput?

**Comment by JosefNemec** [comment]
Maybe, no idea. I tried it with genuine 360 controller just now and it works fine.

**Comment by TacticalTurtleneck** [comment]
I have the same problem, where are the input settings?
