### ISSUE TITLE
Option to add custom game media

### ISSUE THREAD

**Issue by Rubecks** [JosefNemec/Playnite#358]
The ability to use images as logos replacing the game title in the infobox, like you can do on media center softwares (Kodi, Emby, Plex, etc.).

I don't know of any database that you can find these logos, but just adding them manually for now would be really nice.

**Comment by JosefNemec** [comment]
Can you add a screenshot to illustrate how it should look like?

**Comment by RubeensVinicius** [comment]
This is how my The Phantom Pain infobox looks atm.
![clipboard image](https://user-images.githubusercontent.com/15078228/34321045-eb33369c-e7ec-11e7-988d-2d3fb3b4ba3f.jpg)

My request is to let us set a logo, the same way we can set a cover or background image, to make it look like this:
![clipboard image 1](https://user-images.githubusercontent.com/15078228/34321046-ed163298-e7ec-11e7-8274-076116942289.jpg)

**Comment by JosefNemec** [comment]
I can in theory add option to assign any media to the game, but then it would depend on the theme if it would actually display that data.

**Comment by RubeensVinicius** [comment]
So, I'm experimenting with the themes and I think that now I get what you're talking about. What makes the program display the images we have now are the "bindings" Game.Image, Game.Icon and Game.BackgroundImage, right?

So, your idea is to let us add any image to a game and set their ID? E.g. If I want to use logos in my theme, I would have to upload it to the media tab, set the ID to "ImageLogo" and edit the theme so it can render the "Game.ImageLogo" image instead of the "Game.DisplayName" string.

If so, it would be better than opening an issue for each piece of art we want to use on our themes. Another use case would be the Aurora Skin #359 that uses a different cover format than the other themes. The author could add support for a "Game.ImageCircle" instead of replacing the more common rectangular ones, therefore, breaking the look of the default theme.

**Comment by JosefNemec** [comment]
Yes that's exactly what I'm proposing.

**Comment by Continous** [comment]
Would it not be possible to implement a Playnite specific binding or binding type that would allow either a string or an image? Exclusively for themeing/plugins?

**Comment by PhrozenByte** [comment]
It might be a good idea to use this feature to expose all screenshots of a game published in Steam's store, allowing users to choose a favored background image by simply changing the desired image's ID to `Game.BackgroundImage`. See the `screenshots` array of http://store.steampowered.com/api/appdetails/?appids=221380
