### ISSUE TITLE
Enhancement: Add 'open Task Manager' to 'cancel game monitoring?' dialog

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#3582]
### Feature description

On occasion, a game fails to exit (or crash) properly and remains open in background. 

When this happens, an option in the 'cancel game monitoring?' to open the task manager to kill the process would be helpful.

**Comment by limodual** [comment]
Instead of opening the task manager to kill the game process, why not just the button to directly kill that game's process? Isn't that makes much more seamless experience?

**Comment by chocolatechipcats** [comment]
To differentiate between processes that are actually stalled and those that are just slow to close.

**Comment by JosefNemec** [comment]
1) I don't like an idea of opening task manager and asking user to do stuff there manually (opening it manually is very simple thing to do anyways).
2) Killing game processes is not an option since Playnite usually has no idea what game process even is, since tracking and startup is usually handled by library integrations, not by Playnite itself.
