### ISSUE TITLE
Steam and GOG default cover rework

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#36]
Add option to change how Steam and GOG cover are being generated. Current solution involves predefined style with provider logo to ensure that default cover aspect ration is maintained (which default images from store don't provide). This look might not be universally liked and it also might not fit selected app theme.

**Comment by JosefNemec** [comment]
What will change:
- Playnite will only store original cover art provided by Steam or GOG without any modification to original image
- Option will be added to display original cover or display cover with unified aspect ratio and custom backdrop
- Option will be added to reset covers for games added prior to v3.0, which would contain only modified cover art

**Comment by ziplock9000** [comment]
How about they also have a section at the bottom that does generic YouTube video searches and embeds them into the page too. Same for screenshots via a search.

**Comment by JosefNemec** [comment]
@ziplock9000 I'm not sure that's related to cover view, or at least I don't understand how would it work and look.

**Comment by ziplock9000** [comment]
@JosefNemec Under all of the details pertaining to the game via GoG or Steam, have a section that shows a list of YouTube videos about the game generated from YouTube search results. Under that have a section that shows images generated from image search results. 
This means that when a person clicks on a game they have in the list they can see the store details for the game as well as some videos that show gameplay, speed runs etc all in one place.

**Comment by BoltPow3r** [comment]
[So, right now this is how cover look like. ](https://i.imgur.com/viavTu8.png)

This is a lot of empty space wasted. This is what I would suggest it *could* look like. 

[Ver1.0](https://imgur.com/a/mTAKB)

[Ver1.1](https://imgur.com/a/gWFQQ)

By no means am I a professional at photoshop, but this is very close to how I imagined it.

**Comment by ziplock9000** [comment]
I would just remove the unused space rather than trying to think of something we never specifically asked for to stuff into the space. The title is already in the banner, we have already purchased the game so the price is unimportant.. Same with user score.. useless when we already own it.. Genre.... Not important enough to have up front, you should get that from the detail page.

**Comment by BoltPow3r** [comment]
While I somewhat agree, I do disagree with the rest. For example, the title is nowhere to be seen, you have to mouse over it to see it. Waste of action and time. 

I would like to sort games by prices. My friend for example purchases a lot of games (as seen in the pictures above). Most of it is indie garbage that sell for 4€ or less. I would like to filter that out. Not only that, but there is a hidden boon with this. You get to have all your AAA titles at the top.

As you can clearly see. It is not useless. Maybe to you. But you have not provided a single good reason not to have these features implemented. Unless you can come up with a single good reason, I will not debate this any further.

**Comment by ziplock9000** [comment]
I kinda did.
**Title** - This is shown in the banner itself. In fact, the screenshot you show clearly says "South Park, The Fractured But Whole" so your point is moot in your example. 

**Genre** If you want to sort something by a specific parameter like genre, do that on the detail list view, that's what it's for. There's nothing special about Genre that needs it to be promoted to the Covers view. A view designed to only show very important and frequently used information by the majority of users.

**Price** This is doubly what I said about Genre, it's a minor parameter that belongs in the Details view, there you can order them as you wanted to your hearts content, just like any other parameter too. There's nothing special about it that warrants it to be big and bold on the Covers page. Add to that your specific use us very fringe, which just goes to enchance the fact that it has no place in a prominent Cover view. Nobody who owns a game will need to see the price **they already paid** for it on the very prominent Covers view. From the details view you can sort for you cheap 4 euro games to your hearts content, or any other parameter as well!

**User Score** Again, as one of dozens of parameters regarding a game, a person who already owns the title will not find that important and therefore should not be on a cover image, just the details page.

I stand by the opinion and have stated valid reasons why those things are very clearly useless *on the cover view* as they are not important enough to be "front and center" by just about every user. They belong on the details view only. Although I could see an argument for "Title" as sometimes banners are not 100% clear and certainly not uniform.

It seems you've very much confused the purpose of the Covers page versus the Details page it seems.

**Comment by BoltPow3r** [comment]
Title - You need something easy to read in a consistent font. Imagine street signs each using a different font and size

Genre - its was just a filler things to fill up the list, plus it is what it usually shown as information on every site ever

Price - why should it not be in covers tab also? why does it belong into details view? That doesn't make sense. If I can sort by A-Z in covers tab, I should also be able to do so in Covers tab, no, I should be able to do that everywhere you can sort. this is just retarded. You make 0 sense. 

again no good reasons.

I'm sure my friend and me also memorised every score and price of every game he owns. /s

Please stop replying.

**Comment by ziplock9000** [comment]
Title - As I said earlier,  this sometimes might need to be shown clearer than what's on the banner.

Genre - So you admit it's just filler and not actually needed. Thanks for agreeing

Price - It belongs on the details view because the overwhelming majority of users will not need or want to see that information every time "front and center" when they have already purchased the game. It's therefore makes much more sense to put it in the details view only and makes perfect sense for it to be there. You mention sorting by price.. Sorting in any manner is only possible on the detail view anyway, WTF are you on about?

All good solid reasons based on use cases from the majority of users.

"I'm sure my friend and me also memorised every score and price of every game he owns. /s!"
That's what the detail view is for!!! NOT the cover view!!!

Just look, this is how Steam does it. **NO price, NO genre, NO title, it's a COVER VIEW!!**
https://i.imgur.com/031cdFd.jpg

Look again, This is how GoG does it, **NO price, NO genre, Just the title, it's a COVER VIEW!!**
https://i.imgur.com/X8fFRqb.png

And again, Uplay, **NO price, NO genre, Just the title, it's a COVER VIEW!!**
https://i.imgur.com/Yu1yBsm.png

And Origin, **NO price, NO genre, not even a title, it's a COVER VIEW!!**
https://i.imgur.com/gx6CrlO.png

Every single one uses just the banner or at the most the title.
You are fundamentally not understanding what the cover view is for and getting confused with the details view.

Please stop replying. - No

**Comment by BoltPow3r** [comment]
Title - you never said that

Price - I never said it should be displayed, I said that you should be able to sort by price so higher priced games get to be on top. Jesus Christ man

Ok thanks for the trolling. I'm done here.

**Comment by ziplock9000** [comment]
**Title - you never said that**
Yes I did. Look up. I said several posts back I said "Although I could see an argument for "Title" as sometimes banners are not 100% clear and certainly not uniform."

**Price - I never said it should be displayed, I said that you should be able to sort by price so higher priced games get to be on top.**
Yes you very clearly did. It's in your damn mock up and you defended that several times.  I repeatedly mentioned that any sorting by price would be in the details view, not cover view but you would not accept that.

**Jesus Christ man, I'm not going to even bother with the rest of the points.**
Thats your choice. Be ignorant

**Ok thanks for the trolling. I'm done here.**
This is not trolling, it's called a debate. It's what people do when they get together to design things. They discuss options, what's good and bad, what they like and what they feel won't work. If you can't handle constructive criticism of a suggestion you made on a public forum and are not willing to learn from people who work in the industry then maybe it's a good idea that you're done here.

**Comment by JosefNemec** [comment]
Guys, cover view will be fully skinnable in 3.0 If you want just covers, you'll have just covers. If you need more info then you can edit the skin and add it there. I would stop the discussion there.

**Comment by JosefNemec** [comment]
Released in 3.0
