### ISSUE TITLE
Library Damaged/Corrupted

### ISSUE THREAD

**Issue by ElieRP3121** [JosefNemec/Playnite#3610]
### Bug Description

When I try to add a new game, the app crash.

I saw previous reports so I attached all my .db files from my playnite path.

[library.zip](https://github.com/JosefNemec/Playnite/files/13495037/library.zip)

### To Reproduce

Pressing the Insert button or Manually Insert a Game.

### Diagnostics ID

"Failed to automatically upload diag package"

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/99256287/782a4f42-065a-4da9-9b49-cfa9082c70d8)

**Comment by ElieRP3121** [comment]
Thank you very much!

Btw, I have a few questions about this Issue

1. Is there a way to fix it manually or how do you fix it?
2. What is the cause of the Issue?
3. Is there a way to avoid this Issue?

again, thank you.

**Comment by JosefNemec** [comment]
1) There's an automatic repair mechanism in Playnite but some rare corruptions have to be fixed manually.
2) No idea
3) No idea since I was unable to find out what exactly causes these specific rare corruptions. Playnite 11 is switching to a different data store method so it shouldn't be an issue in future.
