### ISSUE TITLE
Default installation path should be %LOCALAPPDATA%\Programs\Playnite instead of %LOCALAPPDATA%\Playnite

### ISSUE THREAD

**Issue by zhiyuan-lin** [JosefNemec/Playnite#3615]
### Bug Description

It’s more idiomatic to follow the more commonly used Windows folder structure, which is also used by many other apps e.g. Signal, Python, VSCode.

### Diagnostics ID

None

**Comment by zhiyuan-lin** [comment]
https://learn.microsoft.com/en-gb/windows/win32/shell/knownfolderid?redirectedfrom=MSDN#FOLDERID_UserProgramFiles

It has actually been recommended by Microsoft since Windows 7, and they have provided a `FOLDERID_UserProgramFiles` identifier for it.

Also, since Playnite uses the `AppData\Roaming` folder for its application data, the whole DB will be synced to the AD if someone runs it on a domain-joined PC.

If we follow the Windows convention perfectly, the folder structure should be
`%LOCALAPPDATA%\Playnite` => Playnite application data
`%LOCALAPPDATA%\Programs\Playnite` => Playnite program files

You should not use Roaming as Playnite’s functionality requires other game launchers to work, and the database is useless if it is synced to another domain-joined computer.

**Comment by batterycharger** [comment]
Directory folder hierarchy resonates well to all who have their toys and tools always in their right places.
Apple would probably force this change on their OS, but Microsoft's roots are on quick'n'dirty (QDOS) that's why it will be a mess forever. Probably future Windows version will force this and pain will be felt then.

Signal and Podfriend are 2 most known out of 5 using this among 217 (incl. Playnite) on my system.
Playnite would be in good company, but this needs a push from M$ to get going. (sad)

**Comment by myarchivist** [comment]
> If we follow the Windows convention perfectly, the folder structure should be `%LOCALAPPDATA%\Playnite` => Playnite application data `%LOCALAPPDATA%\Programs\Playnite` => Playnite program files

The normal convention is storing the configuration and data in %APPDATA% and NOT %LOCALAPPDATA%, as the former gets synchronized and can traverse with profile syncing as the latter is only meant for profile data, which SHOULD NOT be synchronized, like cache stuff and similar things.

Microsoft did shoot itself in the foot, as all or most .NET applications (as well as any chrome / electron based stuff) store their stuff per default in %LOCALAPPDATA%, ie "not important user data, which may be discarded".

To get on topic, I don't advocate that Playnite should change its default location to %APPDATA%.

> Microsoft's roots are on quick'n'dirty (QDOS) that's why it will be a mess forever.

The last operating system which had a lineage to that was Windows ME and died out in favor to (Windows) NT.

> Probably future Windows version will force this and pain will be felt then.

As Microsoft itself and its operating is literally littering everywhere in the file system their stuff, as well as their configurations due to the lack of centralized development management, hard-coding drives and paths everywhere in the OS itself and lack of clear distinguishing between what is part of the different operating system (layers) and utilities, this is only remedied if you make a hard cut, which won't ever come.

**Comment by JosefNemec** [comment]
Not worth the change imo, mainly for backwards compatibility reasons for people that might be repairing installs with old path.

Also this:

> You should not use Roaming as Playnite’s functionality requires other game launchers to work, and the database is useless when it is synced to another domain-joined computer.

is irrelevant since 99% of gaming PCs are not connected to a domain.
