### ISSUE TITLE
Switch to full-screen mode. Add a checkbox to never see that pop-up again

### ISSUE THREAD

**Issue by vizionblind** [JosefNemec/Playnite#3634]
### Feature description

Would it be possible to add a checkbox here where you can click "never see this window again

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/4580595/2d6c5506-dbcb-4b3f-a4c6-4a9d04b978b9)

**Comment by JosefNemec** [comment]
Don't think this is good idea. User should know about some possibly important background task running while they are switching modes and interrupting that task.

If you are getting this because you are running Desktop mode and immediately switching to Fullscreen while library update on startup is running, then you have two options:
- disable library update on startup
- run Fullscreen directly by starting fullscreen exe
