### ISSUE TITLE
Built-in IGDB didn't find the game Predecessor so no media downloaded for the game

### ISSUE THREAD

**Issue by projektilski** [JosefNemec/Playnite#3669]
### Bug Description

For some reason Playnite didn't update metadata for the game Predecessor and when manually updating metadata using IGDB it shows empty list, and it does not show the game Predecessor which does exist on IGDB.

https://www.igdb.com/games/predecessor

### Diagnostics ID

c68447ac-1222-4797-9f30-ee6d4862076d

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/37306957/6e456d23-92bf-4f41-9768-a3b433c3310e)
![image](https://github.com/JosefNemec/Playnite/assets/37306957/fcd96a7b-ad15-4012-a25e-a660f110cc93)

**Comment by JosefNemec** [comment]
This is handled by IGDB plugin, not a Playnite issue.

As far as the plugin, mods and forks are currently excluded from matching because they poison search results. You can lookup the game by its ID you can find on IGDB page:

![image](https://github.com/JosefNemec/Playnite/assets/3874087/5341eb14-6b6e-49f4-aed8-6083c91e3f98)
