### ISSUE TITLE
Automatically re-pull metadata

### ISSUE THREAD

**Issue by BLACK4585** [JosefNemec/Playnite#3713]
### Feature description

It would be nice if you could set an interval, after which PN fetches the metadata for the games you select again. Like all installed games or all. It could do that in the background without a loading animation, since it could take a while if you have a lot of games.
This is pleasant for games with seasons, like THE FINALS, Call of Duty or simply to get the newest descriptions and informations, in my case from Steam Store.

**Comment by JosefNemec** [comment]
This is intentionally not a feature because any issues on metadata plugin's side could lead to data lost when updating metadata "silently" in background. All metadata are provided by plugin anyways and if a plugin can recognize that new game "season" is available, it can update metadata even without this being an explicit feature in Playnite.

So closing this as it's not planned and for metadata sources that can safely recognize changed metadata, they can already update them if they wanted to.

**Comment by BLACK4585** [comment]
So a plugin is able to silently refresh the metadata or at least on its own?

**Comment by JosefNemec** [comment]
yes, any plugin can update any game data anytime they want

**Comment by BLACK4585** [comment]
Oh, I didn't know that, somebody on the Discord told me that plugins are not able to do that.
Thank you!
