### ISSUE TITLE
 It was supposed to be A Y for XBOX but it turned out to be u t

### ISSUE THREAD

**Issue by HP-BugMayCry** [JosefNemec/Playnite#3717]
### Bug Description

Full screen mode below the prompt shortcut key is wrong, how to modify. It was supposed to be A Y for XBOX but it turned out to be u t
![1711459769720](https://github.com/JosefNemec/Playnite/assets/160491156/09977f51-620d-4c5f-919a-5b1156793898)

### Diagnostics ID

0

**Comment by JosefNemec** [comment]
Your Playnite install is corrupted somehow because it's missing symbol font that would display correct controller button prompts. So I recommend reinstalling. Can't say more because you didn't bother attaching diag. ID that was requested in issues template which would help diagnosing what's going on...
