### ISSUE TITLE
Possibility to export one's data

### ISSUE THREAD

**Issue by andreifoldes** [JosefNemec/Playnite#3739]
### Feature description

It would be very useful or private and public research purposes if Playnite users could export their data as csv files.
Ideally there would be a separate export option of lifetime usage stats and weekly statistics?

**Comment by JosefNemec** [comment]
There are already extensions for this purpose (search "export" [here](https://playnite.link/addons.html)) or you can write simple script to export data you need.

Built-in support for data export is not planned because everybody will have different needs for resulting format and that would be way too much effort to maintain. Built-in scripting is perfect substitute for this since you can easily export data to whatever format you want.
