### ISSUE TITLE
Add "Turn off Windows nighlight" toggle in settings

### ISSUE THREAD

**Issue by JonathanPitre** [JosefNemec/Playnite#3761]
### Feature description

It would be cool to disable Windows nightlight automatically when Playnite is launched. I tried to script it but no luck.

The following reg key determines if nightlight is on or off, the binary value of **Data** changed but it's a random number each time.

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\DefaultAccount\Cloud\default$windows.data.bluelightreduction.bluelightreductionstate\windows.data.bluelightreduction.bluelightreductionstate`

**Comment by JosefNemec** [comment]
In my opinion, way too niche to be added as a built in feature since it can be done as custom startup script.

If you are having issues making it work, try these that popped up doing quick Google search:

https://superuser.com/a/1724561
https://www.powershellgallery.com/packages/Set-BlueLight/1.0.0/Content/Set-BlueLight.ps1

Second one probably doesn't work since 19H1 Windows 10 update.

**Comment by JosefNemec** [comment]
I couldn't find any public Windows API to control this, everything points to these registry keys and if those no longer work, I have no other option how to implement this. So I can't add this as built-in feature even if I wanted.
