### ISSUE TITLE
Expand the PowerShell API to allow more customization

### ISSUE THREAD

**Issue by polygonnedpotato** [JosefNemec/Playnite#3782]
### Feature description

This would allow users to easily:
  - Create full custom UIs
  - Pave the way for more addons
  - Allow more freedom in the launcher, and even allow others to completely overhaul it.

**Comment by JosefNemec** [comment]
No planned, there are several issues with PowerShell interacting with the UI because of PowerShell's threading system.

PowerShell extension support is actually being removed in Playnite 11. Application and game scripts will remain but only C# extension will be supported. Absolute majority of existing extensions are already in C# anyways and I highly recommend you switch to C# as well, you'll get better performance, code completion, static type checks etc.
