### ISSUE TITLE
Playnite won't open external links using Arc Browser.

### ISSUE THREAD

**Issue by mickaelxd** [JosefNemec/Playnite#3793]
### Bug Description

When i'm trying to click in any link available inside Extensions (or any other window), it just doesn't open when Arc Browser is set as Default Browser. When I switch to Microsoft Edge in Default Apps (Windows feature), it fixes the problem.

### To Reproduce

1 - Download Arc Browser for Windows
2 - Set as Default Browser
3 - Open Playnite
4 - Try to open a external link

### Diagnostics ID

6fd61648-b814-45ed-aef6-7ea279723274

### Screenshots

![image](https://github.com/user-attachments/assets/299f1757-59dd-4bc4-bf1a-b51c6da97b05)

**Comment by JosefNemec** [comment]
I don't see any errors in logs (which means that .NET API call to start URI process worked) and links are opened in the same way no matter what browser you have. So must be browser issue.

**Comment by mickaelxd** [comment]
Okay, I’ll try to reach out the browser company. Anyway, thanks for explaining it.

**Comment by stevenbrix** [comment]
Thanks for filing this issue, I'll take a look on the Arc side

**Comment by stevenbrix** [comment]
Hmm I just tested this and it worked, I know we had some issues but they should've been fixed by now.  If you wouldn't mind launching Arc from powershell with something like `Arc.exe --log-file=$env:TEMP\arc-launch.log` and then trying to open the external link.

Then send the log to steve@thebrowser.company and I can take a look. Thanks!
