### ISSUE TITLE
Any future plans for macOS/Linux support with Mono?

### ISSUE THREAD

**Issue by TheDarocker** [JosefNemec/Playnite#38]
Nice project here, got a bit farther than mine ever did. Would like to know if there's any future plans for cross-platform support.

**Comment by JosefNemec** [comment]
I'm afraid no, at least not in foreseeable future. The biggest blocker is the absence of WPF on those platforms, which is used for the GUI in Playnite. I'm currently not planning to use anything else because there isn't any mature toolkit with C# and modern binding support (with only Eto and Avalonia getting there slowly). So I guess it's up to Microsoft to release WPF as cross-platform toolkit (which might happen some day given their open sourcing efforts lately).

**Comment by Ruedii** [comment]
Exactly what subset of WPF do you use.  Many of them are duplicated across the .Net namespaces and are implemented in Mono.  

The most substantial portion, XAML, is mappable to the system.xaml namespace.

**Comment by JosefNemec** [comment]
XAML and WPF are two completely different things (WPF uses XAML for markup definitions) and WPF as UI toolking is not implemented in Mono at all.

**Comment by colonelpopcorn** [comment]
Is Xamarin a candidate for WPF replacement? I know it would be a pretty big ordeal, but I know I'd certainly like to see this available for other platforms. It could also allow ports to phones as well.

**Comment by JosefNemec** [comment]
Last time I checked Xamarin.Forms for desktops was not a good option for porting complex application like Playnite. At this time Avalon would be more fitting alternative.

**Comment by mirh** [comment]
WPF should be available on .NET Core 3.0

**Comment by JosefNemec** [comment]
WPF is in .NET Core 3, but still Windows only (and that's not going to change any time soon). See #59 for more information. This issue is closed, please continue discussion there if you have something to add.

**Comment by cipitaua** [comment]
bad strategy to not adopt a cross-platform devkit from the beginning

**Comment by aardvark82** [comment]
Despite how other commenters seem to view X-platform compatibility as a decision with no costs, I understand the rationale in this thread for single platform availability - and how it has made Playnite the great software it is today, albeit on Windows only.

**Comment by aardvark82** [comment]
> bad strategy to not adopt a cross-platform devkit from the beginning

cross-platform frameworks inevitably introduce compromises and limitations - their adoption outright for any new project is not a feasible strategy if speed of development is a requirement

**Comment by bayazidbh** [comment]
> cross-platform frameworks inevitably introduce compromises and limitations - their adoption outright for any new project is not a feasible strategy if speed of development is a requirement

It depends on the initial design, drawbacks, and the expertise of the developers. [Heroic Games Launcher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher) has done pretty well supporting Windows, macOS, Linux desktop, and Steam Deck.

In exchange, no community support of other platforms (unless someone works on it and upstream it to mainline), it uses electron (which is quite infamous at this point), and it's not as configurable on platforms other than Linux. The development pace is still fast, though, but that's due to being Linux-first and the nature of Linux gaming scene's collaboration efforts (see Bottles, Lutris, and ULWGL).

At the end of the day, it is what it is. That said, I'm pretty sure this subject have been discussed a lot and is already a done deal - so maybe someone can lock this Issue? IMHO the #59 one can be unlocked but status changed to Closed (Not Planned), if there's no plan to do other platforms (just so that there's a quarantine for Linux support requests - but still remain clear that it's not planned).

**Comment by Ruedii** [comment]
> > bad strategy to not adopt a cross-platform devkit from the beginning
> 
> cross-platform frameworks inevitably introduce compromises and limitations - their adoption outright for any new project is not a feasible strategy if speed of development is a requirement

Limitations depend on the toolkit, but sometimes you run into places where you need platform specific code.  This is typically done by small "platform integration" modules.

This means using modular code design.   Ideally even the UI should be modular.

However, for this project I would assess that getting it running under wine and doing QA testing on wine should be enough for now, and modular cross platform.design should be reserved for a rebuild.

**Comment by JosefNemec** [comment]
Wine route is not going to happen since that has ton of drawbacks becuase running under "emulated" environment. App like Playnite needs "native" access to the system.

I will be experimenting with Linux support after P11 is done (which will remove 99% of Windows dependencies). Until then, any discussion about possible Linux support is pointless. That's why I locked the other issue and locking this now as well.
