### ISSUE TITLE
Opening installation section in game properties crashes playnite

### ISSUE THREAD

**Issue by itsFaizan49** [JosefNemec/Playnite#3817]
### Bug Description

IDK what is causing this but whenever i open the installation section in properties of any game, it just crashes for no reason, tried using safe mode to no results so this is an issue with playnite itself.

Here are the logs:
[Playnite.zip](https://github.com/user-attachments/files/16918055/Playnite.zip)

### To Reproduce

1. Open any game's properties.
2. Click the installation section on the upper middle

### Diagnostics ID

(Shows an error "Failed to create diagnostics package")

### Screenshots

![vED307Sae1](https://github.com/user-attachments/assets/0fd2527a-39c2-4283-96d2-27971bfb9812)

**Comment by JosefNemec** [comment]
Are you using something that's redirecting user temp folder to a: drive? The UI library we are using is crashing because it for some reason tries to access this path on a: drive.

> System.IO.DirectoryNotFoundException: Could not find a part of the path 'A:\Temp\WPF'.

Diag. package creation failed on similar error, failed to access `A:\Temp\Playnite\diag`.

Overall, not an issue in Playnite, something is broken with how user temp folder works on your system.
