### ISSUE TITLE
Use the name of a folder at a higher level to search for game metadata...

### ISSUE THREAD

**Issue by Korb** [JosefNemec/Playnite#3835]
### Feature description

...if a search for the file and its folder names did not yield anything.

`Scan Automatically...` → `Select Games to Import` → `Scan Folders...`

If I understand correctly, Playnite 10.34 uses only the game's executable or batch file name and the folder name they are located in for online metadata search. I suggest considering using the folder name where the folder containing the found file is located to search for the game name.

In the example shown in the screenshot, igdb.com did not find any information on the executable files of the three games, but if the search had been performed in the folder above the level, a match would have been found:

A320 Airbus (1992) https://www.igdb.com/games/a320-airbus
A.D Cop (1997) https://www.igdb.com/games/ad-cop
A-10 Tank Killer (1989) https://www.igdb.com/games/a-10-tank-killer

### Screenshots

![2024-09-26_14-10-30](https://github.com/user-attachments/assets/c7b9cb1b-d642-4f48-b4d2-184c10f26ae5)

**Comment by JosefNemec** [comment]
It's virtually impossible to handle or these weird cases. We've adjusted name detection multiple times and the current system is the most compatible.

There are plans to implement customized import via `.playnite` files you would be able to store in games folder, but scan dialog is not getting any other options for name detection because it would quickly get out of hand.

**Comment by Korb** [comment]
> JoseNemec closed this as completed on Sep 26, 2024

Perhaps this issue should have been closed `as not planned` ("won't fix, can't repro, stale")?
