### ISSUE TITLE
Localization updates

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#385]
This is just a notification issue that will be updated when changes are made to English localization files. It's for people to subscribe to it and be notified, so they can update custom translations.

**Comment by ArtexJay** [comment]
alright, as of now french translations are up to date with the current English ones :)

**Comment by operamaniac** [comment]
Okay, thanks for your hard work! :)

**Comment by JosefNemec** [comment]
New changes in 3.4:
https://github.com/JosefNemec/Playnite/compare/c787adf0ab4cbaa54fcd3a58bcef003d9e903be3...5262db87ca6f0962aa413a625a2d787af590dcf7

Switch to `files changed` tab and look for `english.xaml`

**Comment by PhrozenByte** [comment]
@JosefNemec: Thanks again! 🎉 What do you think about delaying new releases for 1-2 days (it shouldn't be too long, just a reasonable response time) to give us translators the chance to update the localization files on time?

**Comment by JosefNemec** [comment]
Yeah I will probably send notifications sooner then on release date (I don't usually make changes to texts at the last moment).

Also my current plan is to implement incremental updates (#363), which will allow me to push localization updates faster (without program update on client's side and immediately after changes are available).

**Comment by L1cardo** [comment]
Simplified Chinese Translation for Playnite (https://github.com/JosefNemec/Playnite/issues/299)

Updated to the latest Playnite 3.4. Fixed some translation error and add the new strings which  are made to English localization files. Now it should be the 100% same as the English localization file :)  

The next time you upgrade Playnite, please replace with the new localization. And please change the file name "中文" into "simplified chinese" in order to be consistent with everyone.

**Comment by ArtexJay** [comment]
French Translation has been update (#343 )
Updated with new strings in english localization file and tranlated a string that i missed

**Comment by JosefNemec** [comment]
New strings added for 4.0, there's ton of changed files so go `Files changed` and search for `source/PlayniteUI/Localization/english.xaml`. The list is huge so it may take a while to load diff for english file.

Here's the link:
https://github.com/JosefNemec/Playnite/compare/2d853a80326b22d7b2b76ac03f18f416609d3e85...ddae210af7f3d87efb84a64b1444b41a468de758

Also take [these files](https://github.com/JosefNemec/Playnite/blob/devel/source/PlayniteUI/Localization/) from devel branch as your base because not everything is in master yet and all localization strings now have `LOC` prefix.

**Comment by RubeensVinicius** [comment]
So, even if the master doesn't have the prefixes yet, we should use them on our files?

**Comment by PhrozenByte** [comment]
So, https://github.com/JosefNemec/Playnite/compare/2d853a80326b22d7b2b76ac03f18f416609d3e85...ddae210af7f3d87efb84a64b1444b41a468de758 lists all changes and we should additionally prefix all variables with `LOC`, right?

**Comment by JosefNemec** [comment]
To be specific:
- download your language file from [devel](https://github.com/JosefNemec/Playnite/tree/devel/source/PlayniteUI/Localization) branch
- if you are adding new string then yes, prefix it with LOC (if you check english.xaml from devel then you'll see that everything has LOC already.
- if you are just updating existing string then they should have LOC already there in your language file.

The diff is without LOC prefixes because it's before I added them. You wouldn't be able to see what's been just added if I posted diff after LOC prefixes have been added.

**Comment by PhrozenByte** [comment]
Got it, thanks :smiley: 

@JosefNemec: Can you please provide us with some pre-built installer or portable pre-release version, allowing us to test our localization updates? Unfortunately there's no installer for Playnite 4.0 yet and since the changes were pretty massive, I'd like to test my updates before opening a PR. Building Playnite doesn't work for me for some reason, `build.ps1` bails out with `Couldn't find "nuget.exe"`, even though `nuget.exe` exists in the build dir (I've zero experience with Powershell, so no idea how to fix this). Releasing pre-releases, allowing us to update the language flies and others to test Playnite before a new release, might be a good idea in general :smiley:

**Comment by JosefNemec** [comment]
Yeah, the current state is not ideal. I will be redoing the whole release schedule and build availability for next major version. Public 4.0 release is on today so there's no time to update languages anyway (another "not ideal" situation).

Sorry to everyone about how language updates are currently being handled, I will do something about it. And thanks to everyone contributing translations despite this mess.

**Comment by L1cardo** [comment]
Simplified Chinese has been updated (#299  )

Updated for Playnite 4.0


It was really a big work ...   Now I have to prepare for my exams... haha

**Comment by ClearStrelok** [comment]
Updated French Translation (#343 )

**Comment by ClearStrelok** [comment]
Updated French Translation (#343 )

Also, you're probably already aware of that but "Export Library" and "No categories" have no related strings. (I couldn't find them in _english.xaml_ either)

**Comment by Ratox00** [comment]
Updated the hungarian translation (#564)

**Comment by JosefNemec** [comment]
New strings for 4.2 https://github.com/JosefNemec/Playnite/compare/06c9cf65bcb6285b8bc9c7051f6fc7cb921a179f...f5b6aeea66c0b3e5ff1ca23c9bd66a2dd7c386e7#diff-fc6eaa727d5578c3ac3d59652659d9e2 I even managed to post it before release :)

**Comment by JosefNemec** [comment]
@ClearStrelok I'll fix it in #570

**Comment by Vuelos** [comment]
Updated Spanish Translation #573

**Comment by RubeensVinicius** [comment]
Brazilian Portuguese updated #330

**Comment by ClearStrelok** [comment]
Updated French Translation (#343 )

**Comment by wilco375** [comment]
In case you didn't see it, Dutch translation was also updated (429)

**Comment by JosefNemec** [comment]
@wilco375 I don't see any updates for 4.2 there, am I missing something?

**Comment by L1cardo** [comment]
Updated Simplified Chinese Translation for Playnite 4.2 #299

**Comment by wilco375** [comment]
@JosefNemec Sorry, missed the 4.2 update, thought the comments were still about the 4.0 update. Added 4.2 translations to #429 now.

**Comment by JosefNemec** [comment]
New strings in 4.21:
https://github.com/JosefNemec/Playnite/compare/5d7239dae2c17356d97efc740e5382aa7933b111...1ff47891fa6e21e233446c724af10a703b2b6e44#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by PhrozenByte** [comment]
The link is broken (the `#` is missing for some reason), here's a working link: https://github.com/JosefNemec/Playnite/compare/5d7239dae2c17356d97efc740e5382aa7933b111...1ff47891fa6e21e233446c724af10a703b2b6e44

> Yeah, the current state is not ideal. I will be redoing the whole release schedule and build availability for next major version. Public 4.0 release is on today so there's no time to update languages anyway (another "not ideal" situation).
> 
> Sorry to everyone about how language updates are currently being handled, I will do something about it. And thanks to everyone contributing translations despite this mess.

:arrow_up: Any updates on this? The current situation is a bit unsatisfying.

**Comment by L1cardo** [comment]
Updated Simplified Chinese Translation for Playnite 4.21 #299

**Comment by JosefNemec** [comment]
@PhrozenByte I welcome any ideas how to handle this better. The problem is that I don't want to hold releases back by just waiting for new translation updates since it's very variable how fast can people deliver them.

**Comment by PhrozenByte** [comment]
I'd say that the response time of all translators is pretty fast in general, so I'd simply recommend defering updates (with an exception for security updates) for about 48 hours. IMO this is a reasonable response time, at least for non-major releases (for which you could give us e.g. 4 days in total or something like that).

**Comment by ClearStrelok** [comment]
Is there a way we can be notified each time a commit adds or change a string ? That'd be a good way to keep track of the changes ahead of release.

**Comment by JosefNemec** [comment]
@ClearStrelok  Sadly GitHub doesn't have any way how to get notified if the file changes, but I found this: https://app.github-file-watcher.com/, I'm not sure how reliable it is.

@PhrozenByte I'll try to post here as soon as I'm sure that there won't be any language changes in the build. That should help, also I'll try to not make language changes at last minute.

**Comment by JosefNemec** [comment]
Changes for upcoming 4.3, some new strings were introduced: https://github.com/JosefNemec/Playnite/compare/1ff47891fa6e21e233446c724af10a703b2b6e44...cbfbbe8b373edf2ccfe781cf674f75cfaa019a0d

**Comment by PhrozenByte** [comment]
Great, I've updated the german localization.

However, there's a problem: Playnite shouldn't use shortcuts based on the label (like `B` for `Back`), because it's often simply impossible to represent this in other languages. For example, the German word for `Back` is `Weiter` - and there's simply no `B` in `Weiter`. I don't even want to think about langauges using different character sets, like Cyrillic script or Chinese characters. Thus I didn't implement the shortcuts (yet). Any idea how to solve this?

**Comment by L1cardo** [comment]
Updated Simplified Chinese Translation for Playnite 4.3 #299

**Comment by L1cardo** [comment]
I don't know much about coding , so I will try my best to do the translating. Leave the coding for you guys. Sorry for not being helpful.

**Comment by JosefNemec** [comment]
Please ignore shortcut `_` keys for now in any non-english languages when translating. Thanks.

**Comment by StarFang208** [comment]
I've updated the italian translation of the program up to version 4.30.  #446

**Comment by JosefNemec** [comment]
New strings for upcoming 4.4: https://github.com/JosefNemec/Playnite/compare/e72fd76c618b28a742fe4d652211bd82328cea7b...e9595f763c1947fecc4d381b8c7ef84dd31cd108#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by L1cardo** [comment]
Updated Simplified Chinese Translation for Playnite 4.4 #299

**Comment by StarFang208** [comment]
Updated the Italian translation for Playnite 4.4 #446

**Comment by Evene174** [comment]
Updated the Russian translation for Playnite 4.4 #313

**Comment by JosefNemec** [comment]
New strings and changes for upcoming 4.5: https://github.com/JosefNemec/Playnite/compare/master...devel_4.5#diff-fc6eaa727d5578c3ac3d59652659d9e2

I'll have beta build ready for testing tomorrow in case you need to test your changes in application itself.

**Comment by L1cardo** [comment]
#299

**Comment by L1cardo** [comment]
Updated Simplified Chinese Translation for Playnite 4.5 #299

**Comment by JosefNemec** [comment]
New strings for upcoming update https://github.com/JosefNemec/Playnite/compare/master...devel_4.5

**Comment by JosefNemec** [comment]
New strings for upcoming patch:
https://github.com/JosefNemec/Playnite/compare/f49aed7ec855e001556753492038b7dcb2c0a3cc...master

I also did small commit to last patch and forgot to mentioned it, these were also added since last time:
https://github.com/JosefNemec/Playnite/commit/7c5fa960f0f6b89d3849ff0664776b618377a5f5#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by JosefNemec** [comment]
New strings for upcoming 4.70:
https://github.com/JosefNemec/Playnite/compare/master..1c120cfb8dca9feea061007ff6a3f17aa6a9d57a#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by PhrozenByte** [comment]
@JosefNemec: I noticed this before after seeing some LOC strings I never saw in your comparisons: Unfortunately the comparison links you provide are wrong. They don't include all changes you made to `english.xaml` since the last time we were notified to update localization files (e.g. `LOCSettingsStartOnBootRegistrationError` is missing in your comparison).

It's really frustrating to see that even though we do our best to keep track with development and update the translations as fast as possible, we often fall behind because you don't notify us about changes you made to `english.xaml`. For example, the last time you notified us was for Playnite 4.61. Since then you added 7 new LOC strings (see [`4.61...4.67`](https://github.com/JosefNemec/Playnite/compare/4.61..4.67#diff-fc6eaa727d5578c3ac3d59652659d9e2)). Neither were we notified about these changes, nor do they show up in the comparison link you provided.

Upcoming Playnite 4.70 is at 1c120cfb8dca9feea061007ff6a3f17aa6a9d57a, last time we updated translations was for Playnite 4.61 (f49aed7ec855e001556753492038b7dcb2c0a3cc), so the comparison URL including all changes is: [`f49aed7...1c120cf`](https://github.com/JosefNemec/Playnite/compare/f49aed7ec855e001556753492038b7dcb2c0a3cc...1c120cfb8dca9feea061007ff6a3f17aa6a9d57a#diff-fc6eaa727d5578c3ac3d59652659d9e2) (or [`4.61...1c120cf`](https://github.com/JosefNemec/Playnite/compare/4.61...1c120cfb8dca9feea061007ff6a3f17aa6a9d57a#diff-fc6eaa727d5578c3ac3d59652659d9e2), it's the same)

I'm not even sure whether these links include all changes... So I'll compare everything manually... Again... I already did it the last time because I though it might have been my error. Really, this is super frustrating :unamused:

**Comment by StarFang208** [comment]
Updated the italian translation for 4.70  #446

**Comment by JosefNemec** [comment]
@PhrozenByte I apologize, I'll try to do better job notifying about changes in language files.

**Comment by L1cardo** [comment]
Simplified Chinese localization has been updated

**Comment by JosefNemec** [comment]
New `LOCItchioClientNotInstalledError` was added in 4.72 https://github.com/JosefNemec/Playnite/commit/ac9f2b29796601c34c80664c00bf6bd24dca7324#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by JosefNemec** [comment]
New option string added `LOCSettingsShowGroupCount` (will be in 4.73)
https://github.com/JosefNemec/Playnite/pull/996/files#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by JosefNemec** [comment]
General update on localization. I decided to change how localization contributions will be handled and we will probably start using [Crowdin](https://crowdin.com) #958. Their solution integrates nicely with GitHub, which means that you will be able to easily see any changes I do to English files almost immediately as well as have nice view of what is or isn't translated.

I'll let your know when the switch is complete since there are some changes needed in our build process first.

**Comment by JosefNemec** [comment]
Added two more strings for 4.73: `LOCNoCategory` and `LOCNoPlatform`, they were previously hard-coded strings for empty group descriptions.

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates. Project is currently linked to `devel` branch, which means that some new strings from upcoming 5.0 are already there.

**Comment by PhrozenByte** [comment]
@translators: Since there were changes to existing localization strings before switching to Crowdin, you won't see all changes there. You'll have to do one last manual comparison to get all changes. Simply compare the old [`english.xaml` as of Playnite 4.73](https://github.com/JosefNemec/Playnite/blob/4.73/source/PlayniteUI/Localization/english.xaml) (the last time we updated the localization) and the latest [`LocSource.xaml` on the `devel` branch](https://github.com/JosefNemec/Playnite/blob/devel/source/Playnite/Localization/LocSource.xaml) using e.g. https://www.diffchecker.com/.

**Comment by JosefNemec** [comment]
I should have made a diff before refactoring the solution, sorry about that. The most changes, from what I remember, where done to `LOCSettings*` strings.
