### ISSUE TITLE
IGDB Metadata Not Found in Playnite for *Etterna* (Exists on IGDB)

### ISSUE THREAD

**Issue by mfaathirarsa** [JosefNemec/Playnite#3865]
### Bug Description

**Description**:  
When trying to fetch metadata from IGDB for the game *Etterna* in Playnite, the entry does not appear in the search results, even though the game exists on IGDB.

**Relevant Links**:  
- Previous related issue: https://github.com/JosefNemec/Playnite/issues/2260

**Additional Notes**:  
This issue seems similar to the previous issue (https://github.com/JosefNemec/Playnite/issues/2260), which was closed, but this specific problem persists for certain games like *Etterna*.

### To Reproduce

**Steps to Reproduce**:
1. Open Playnite.
2. Add `etterna.exe` as a game.
3. Edit the metadata and select automatic search using IGDB.
4. Notice that *Etterna* is not listed in the search results.

**Expected Behavior**:  
*Etterna* should appear in the search results when retrieving metadata from IGDB.

**Observed Behavior**:  
*Etterna* does not appear in the search results in Playnite, but it can be found directly on IGDB at this link: https://www.igdb.com/games/etterna.

### Diagnostics ID

6cde19d4-972a-46e0-ace9-8582a807fe55

### Screenshots

![{2945635F-E278-4AB7-BB43-3F4A43E651A1}](https://github.com/user-attachments/assets/a84aa671-8565-4d39-8682-5b61edb56b5a)

**Comment by JosefNemec** [comment]
It's because it's a fork of another another game. Mods and forks are excluded from search results intentionally because of some issues with search results. You can put IGDB game id into search results (visible on game page on the website) to get the game directly.


Also this is all handled by IGDB plugin and should be reported in IGDB plugin's repo.

![image](https://github.com/user-attachments/assets/591ce4fd-3404-485f-beea-f2401d765872)

**Comment by mfaathirarsa** [comment]
Okay thank you so much for the help
