### ISSUE TITLE
Missing one Steam game (Star Wars Republic Commando)

### ISSUE THREAD

**Issue by Quitch** [JosefNemec/Playnite#3892]
### Bug Description

My library is missing Star Wars Republic Commando from Steam.

No filters are active and all other Steam games have been correctly imported. I force a refresh of my libraries, but the game is not added to my population.

Steam is authenticated and my Steam profile and game library is public. The library is also set to import installed games, and this game is installed currently.

### Diagnostics ID

7b3a218f-16b2-4dae-8acc-bf16dacb7cc8

**Comment by JosefNemec** [comment]
1) wrong repository, as template says, integration extension issues should be reported to wherever their repository is
2) I can't replicate it myself, the game is imported correctly for me
3) I recommend getting an API key and using that instead of plain public account config, Steam API can be finicky with that ever since they introduced various privacy settings
4) See [this](https://api.playnite.link/docs/manual/library/games/faq.html#my-games-are-not-importing) and [this](https://api.playnite.link/docs/manual/library/games/faq.html#my-games-are-gone-or-missing)
