### ISSUE TITLE
Show game media metadata

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#393]
Show the image's dimensions, size and format. Requested in #349

**Comment by PhrozenByte** [comment]
I'd like to add @RubeensVinicius suggestion he cancelled later:

> A slider to make all the background images blurry and/or darker. If the image is too detailed, it can be hard to read the text sometimes.

It's IMO very reasonable to allow users to blurry/darken images on a per-game basis, because you usually don't use images from a single source (e.g. Steam background images are already blurry, "normal" screenshots are not). However, the user should be able to change the transparency of a theme-controlled overlay only (to limit complexity), making the image more or less blurry and more or less dark by fading to a theme-specific color (might be black or a usually dark color).

**Comment by Continous** [comment]
@PhrozenByte I think that should be left to the theme to decide actually.

**Comment by PhrozenByte** [comment]
@Continous No, because a theme can't know how a game's background image looks like and whether it already is blurry (like background images from Steam) or not.

**Comment by Continous** [comment]
No, but having a slider just seems unnecessary. I've already made issues elsewhere requesting configurable variables for themes, and the current themeing scheme would already allow user-definable (albeit through XAML editing) blurring.

**Comment by PhrozenByte** [comment]
I'm not sure whether you're getting the point of the suggestion - it's about blurring/darkening background images on a **per-game basis**.

**Comment by JosefNemec** [comment]
Guys this issue is only about displaying media properties when editing game, other features should be handled in separate issues.

**Comment by JosefNemec** [comment]
Done in Playnite 7.
