### ISSUE TITLE
No icons for Origin games

### ISSUE THREAD

**Issue by HunterZ** [JosefNemec/Playnite#398]
Noticed in 3.4 that none of my Origin games have game-specific icons. This is probably Origin's fault, but figured if may be worth capturing as an issue in case someone thinks of a good way to scrape one from somewhere else (e.g. Steam, GOG, Google).

**Comment by JosefNemec** [comment]
There was no change in 3.4 in regards to icons. Icons are only applied to Origin games if the game is installed during import (there's no way where to get the icon otherwise). There's nothing I can do about that, automatically scrapping icons from other services would be too complicated. I don't think it's worth the effort.

**Comment by HunterZ** [comment]
It wasn't intended to be reported as a 3.4 regression. I just make a habit of reporting what version something was noted in, in case it later becomes OBE.
