### ISSUE TITLE
Allow themes and users to launch external programs with game-defined and user-defined parameters.

### ISSUE THREAD

**Issue by Continous** [JosefNemec/Playnite#426]
Games often have many other things associated with them, ranging from third-party programs, to OSTs. Allowing Playnite to launch arbitrarily defined programs from hyperlinks in the game details page, or better yet allowing programs to be launched alongside the game would greatly assist the usability of Playnite.

More forward-thinking however, allowing plugins to reference exterior programs or DLLs would be rather useful for integration with things like Foobar2000 or OBS.

**Comment by JosefNemec** [comment]
You can do that right now by adding custom actions to the game. Adding additional actions to those actions while launching games will be taken care of with #113. Plugin support is planned with #414 and #115 

Do these issues cover what are you looking for or is there something more? (otherwise I will close this issue)

**Comment by Continous** [comment]
#113 addresses this concern, I'll close this.
