### ISSUE TITLE
Multiple Games are being listed twice in the UI (Possibly upgraded editions?)

### ISSUE THREAD

**Issue by Edstub207** [JosefNemec/Playnite#492]
Hey!

I have just been playing around with Playnite and loved what I have seen so far. However, I noticed that some games are being listed multiple times. I don't own multiple copies but they might be for example the Deluxe Version of the games? 

![capture](https://user-images.githubusercontent.com/13305475/37064838-6e91fde2-2196-11e8-8e9b-21eadefedf24.PNG)

**Comment by JosefNemec** [comment]
I'm guessing these are from Steam. Steam API sometimes reports games that are not displayed in Steam client (f2p games, some beta versions etc.). There's currently no way how to filter those out, so for now you have to hide the duplicate manually (from right-click context menu).

**Comment by Edstub207** [comment]
I originally thought it might be a special edition or DLC or something. However, it looks like I don't have any DLC and only own the base game once. As seen in attached image. 

![image](https://user-images.githubusercontent.com/13305475/37181192-dbae10b2-2323-11e8-946b-4c86bf168d48.png)

**Comment by DennoCoil** [comment]
Don't know why Playnite would do that, but I know even Steam gets confused as hell because a publisher\developer makes multiple versions or messes up deploying it.  For example, I have multiple copies of the same Civilization games in my library and the duplicates don't work.  The best thing to do is test which is the correct link (if one is broken) and use the Hide option on both clients.

**Comment by JosefNemec** [comment]
As I said in my previous comment this is because of data Steam API provides. Nothing I can do about it right now.
