### ISSUE TITLE
Search is not instant (slow) when you type

### ISSUE THREAD

**Issue by smcyr** [JosefNemec/Playnite#495]
When you type in the global search box, there is a delay before the results appear. In Steam, for example, the results are pretty much instant (for the same library size). 
Thanks

**Comment by JosefNemec** [comment]
This is intended behavior for performance reasons. We could possibly add an option to disable it, but it will have negative impact on performance for large libraries.

**Comment by smcyr** [comment]
It's what I thought. Maybe add in advanced settings a textbox where you can configure the delay (with the default at 500). I'm a .NET dev also, maybe I could look at the code if you could point me where the search query is done. Thank you, this is a great program!

**Comment by DennoCoil** [comment]
I was wondering why it was slow too.  I don't expect it to load 10,000 entries at the drop of a hat, but it seems very slow for a text search.  Either that or a potential solution is creating multiple library\databases the user can select from.

**Comment by JosefNemec** [comment]
I will lower the default delay and add an option to disable it altogether.

**Comment by smcyr** [comment]
On a library of 16,000 games, the performance is the most affected by those 3 lines:
CollectionView.IsLiveSorting = true;
CollectionView.IsLiveFiltering = true;
CollectionView.IsLiveGrouping = true; 
Is it necessary if you already refresh the filter when you enter text, group or sort? When I comment the 3 lines, it seems to be working fine, but I am probably missing something.

**Comment by JosefNemec** [comment]
That's not what the "live" options from collections views are for. They are for cases where you have sorting/filtering/grouping set for some specific object field(s) and that field changes on some of the items in the list. In that case list sorting/filtering/grouping is updated automatically by WPF without need to refresh the list. But if you are performing search then you are not chaning any field values and therefore "live" features do nothing.

When I was talking about performance problems I specifically meant case where the search would be invoked after every character you would type in search field. That's why the delay is there right now to make sure that we invoke refresh the list only when search term is entered by user completely. Also you need to refresh filter when search term changes because of the way how collection views work in WPF.

Finally you may not see performance problems because it greatly depends on too many things (CPU, IO performance, library size and complexity etc.). That's why I'm going to lower default delay and add option for people that want no delay if they choose to not have it (even that performance might be impacted).

**Comment by smcyr** [comment]
Ok, thanks for the explanation and again, great work!

**Comment by JosefNemec** [comment]
Forgot to mark this as implemented in one of the 4.5x updates.
