### ISSUE TITLE
Add Steam Store Scraper API for non-Steam games

### ISSUE THREAD

**Issue by spiral6** [JosefNemec/Playnite#538]
We already have IGDB and Wiki for scraping options, but the Steam store scraper is unavailable unless you have Steam installed. I'd like to have this as an option because I've noticed the Steam store has updated descriptions and features over those two sites for a lot of games. #

**Comment by JosefNemec** [comment]
Steam scrapped is only available for Steam games, I'm not sure it would make sense to provide that option for non-Steam games.

**Comment by spiral6** [comment]
I'm talking about Steam games that were not bought on Steam. i.e. buying Assassin's Creed IV on the uPlay Store does not allow me to update the description to the Steam Store description. (despite it being in the Steam Store as well)

We should be able to specify what game it is by APPID (i.e. CSGO is 730).

**Comment by JanPokorny** [comment]
I have accidentally made a duplicate issue, I'll copy my text here:

Many games are on Steam, even those bought on other platforms. Steam also provides a wide cover for all games, which is preferred by some users over DVD-sized covers. It would make sense to allow a setting to primarily use the Steam data.

Metadata API endpoint: https://store.steampowered.com/api/appdetails?appids=620

It also seems like the cover and background URLs are pretty constant (although they may change in the future):
https://steamcdn-a.akamaihd.net/steam/apps/620/header.jpg
https://steamcdn-a.akamaihd.net/steam/apps/620/page_bg_generated_v6b.jpg

Probably depends on #417

**Comment by ivanmayes** [comment]
+1 For this, I have a lot of pre owned games that don't have great coverage on IGDB, but are on Steam.  Steam also tends to have more comprehensive and up to date metadata than IDGB, also better review scoring.

I could imagine the user inputting the steam id to simplify the lookup instead of having to search and parse as an MVP feature.

**Comment by Kilroy5150** [comment]
You are….wow…..so hilarious to email me personally……what a loser.

Sent from Mail for Windows 10

**Comment by Kilroy5150** [comment]
You are such a loser to email me personally about that...."mute" goes you 👎

**Comment by JosefNemec** [comment]
@Kilroy5150 Do you realize that it was automatic email message generated by GitHub because you commented in this issue (plus you got mentioned via @)? Anyways, no drama here or I'm going to lock this, keep this about original issue.

Also as mentioned before, this issue can't be done unless #417 is completed.

**Comment by JosefNemec** [comment]
Done as [separate plugin](https://github.com/JosefNemec/PlaynitePlugin-SteamStoreMetadata).
