### ISSUE TITLE
Import hidden status on Steam games to Playnite

### ISSUE THREAD

**Issue by HyphenSam** [JosefNemec/Playnite#615]
I have 600+ games hidden on Steam ([no, I am not joking](https://i.imgur.com/3WKYzIU.png)), and this isn't reflected when imported to Playnite.
It'll be a pain having to sort through all of them again, so having support for this would be nice.

**Comment by JosefNemec** [comment]
I'm not sure this will be possible because API we user right now doesn't report what games are hidden.

**Comment by psychonic** [comment]
@JosefNemec this is actually stored in the same file looked at to pull tags automatically - sharedconfig.vdf in the user's app 7 Steam Cloud cache.
<steam>/userdata/<acct id>/7/remote/sharedconfig.vdf

I can look at adding if you want.

**Comment by JosefNemec** [comment]
Sure go ahead.

**Comment by psychonic** [comment]
I took a look at this, and it seemed like the best place to handle it would be where categories are imported from Steam, since the hidden flag is stored in roughly the same place. That also handles knowing which Steam account you want to pull the hidden data for, since you have to select one on that settings page.

The issue I ran into is that IGameDatabaseAPI.ImportCategories ignores the hidden status (which makes sense, since it's for categories). I'm not sure how to best convey that updated game info there.

I don't think it makes sense to bundle it in with ImportCategories there since other providers may have them separate. Adding a bool param to it to accept hidden status data, or adding an ImportHiddenStatus function on the API seem dirty. Thoughts?

**Comment by JosefNemec** [comment]
I think we should remove `ImportCategories` from database API completely, it's way too specific of a scenario to be part of the API. So just move the category import code to Steam plugin and add handling of hidden state to it. The only issue is lack of buffered updates in the DB API, but it just means that import will be a bit slower. I will add buffered updates to API in next version as well as remove ImportCategories method (there will be some other breaking changes anyways).

**Comment by JosefNemec** [comment]
@psychonic I've pushed API changes to `devel_4.5` branch if you wanna to check it out. I moved all the code already, so you basically just need to update `ImportSteamCategories` method from `SteamLibrary.cs` to include hidden status and that should be it.

**Comment by psychonic** [comment]
Cool. Thanks for the heads up. I'll take a look.

**Comment by JosefNemec** [comment]
Released in 4.59
