### ISSUE TITLE
Playnite imports complete game libraries even if "Only installed games" is selected

### ISSUE THREAD

**Issue by Dragonink** [JosefNemec/Playnite#62]
![Screenshot](https://user-images.githubusercontent.com/10474586/28455648-0ce929f2-6e00-11e7-82ec-4acfbd5d458f.png)

**Comment by JosefNemec** [comment]
This is intended behavior since version 0.93. Settings seen on screenshot only affects what games will be updated (re-imported) to local db, not reflecting what games are already imported into Playnite. Meaning that if you've enabled complete lib import in past you will now see those games in Playnite because they where imported from before. In your case Playnite will now re-import changes only for games that are installed (newly installed games will show up as installed and uninstalled as not installed). You now need to enable filter to see only installed games and you'll get the same view as before.

However I should have updated the description in settings and other places to reflect the change.

**Comment by JosefNemec** [comment]
I changes description in 1.0 to make it more clear.
