### ISSUE TITLE
Emulator support improvements

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#653]
To improve emulator compatibility and enhance game import precision, following enhancements should be implemented:

- split `Definitions.yaml` file, each emulator will have it's own definition file
- add ability for definitions to specify scripts that can:
  - start before game is started (in general control game startup)
  - import games
  - download and install emulator
  - locate installed emulator
~~- treat all definitions as new extension type that will support installation and update via #593 and #298~~
- automatically import newly added ROM files
~~- advanced configurations for metadata downloads~~

**What this means for end users:**
- better metadata import
- better import of games (more options how to import games, like drag and drop)
- improvements to emulator import dialog #423
- support for multi disk games #159 
- possible automatic import of newly added ROMs
- custom game scripts on emulator profile level

**Comment by TheCakeIsNaOH** [comment]
I suggest also adding support for advanced import search. 

Currently, only searching by file extension is supported, but this is a problem for PS3 games and possibly other platforms. PS3 games boot from an EBOOT.bin or BOOT.bin but the game directory structure always has other .bin files, sometimes dozens of them. Sorting which to import after a search is not fun. Being able to search for a *BOOT.bin file would be very helpful on the import for RPCS3.

**Comment by AmenAnthem** [comment]
Suggestions for further improvements:

- What: Add support for emulator selection for selected game.
- Why: I'm currently using multiple emulators per system because I use a different one depending on how I need to play. For example I'm using RetroArch for casually playing and for practicing with save states for speedruns, highly accurate emulators for actual speedruns (PB attempts).
- How: By adding a window to select the wanted emulator after selecting a game.

- What: Add platform selection for games.
- Why: Using a lot of different platforms leads to an ernormous clutter when viewing games. Having multiple games with the same name on different platforms is confusing.
- How By adding the possibility to activate an option which adds a platforms view.

**Comment by okokokokokovtrwrgvgvgvvg** [comment]
also improve the retroarch cores and add more consoles, such as the fairchild channel f

**Comment by OsoaGitHub** [comment]
Could you add the functionality of importing Playtime from emulators that record it (such as Cemu)

**Comment by JosefNemec** [comment]
Done in devel9. Some things were moved to #2409 and  #2407 due to their complexity.
