### ISSUE TITLE
Crash on Inaccessible Database

### ISSUE THREAD

**Issue by epeternally** [JosefNemec/Playnite#654]
Playnite is throwing a "Cannot access library database," error and then immediately crashing, preventing me from actually changing the database location.

[Playnite Crash.zip](https://github.com/JosefNemec/Playnite/files/2066146/Playnite.Crash.zip)

**Comment by JosefNemec** [comment]
I've changed it so Playnite won't crash anymore if this occurs and you'll be able to change the location via settings menu.

In the mean time you can change the path manually in `%appdata%\Playnite\config.json` file, `DatabasePath` field.

Also it crashes because Playnite is by default not running with elevated rights, so it won't be able to use databases located in places such disk root or other system folders. You need to either start Playnite as admin or use different location.

**Comment by JosefNemec** [comment]
Released in 4.30
