### ISSUE TITLE
[Request] Add an option to Playnite to mount an iso and then execute a .exe in another directory

### ISSUE THREAD

**Issue by Ultracoolguy** [JosefNemec/Playnite#676]
So, if you have ever played the CD version of Morrowind, you know you have to keep the CD in the drive before launching it, or else it won't work. Well, as a workaround to not putting the CD everytime, I converted it in an iso, and then mount that. That works as a breeze. However, it would be nice if Playnite could mount the iso and then launch the game. I know my situation is a bit specific, and I will understand if you don't put this feature.

**Comment by JosefNemec** [comment]
This will be possible when #113 is implemented. You will be able to assign any custom script to be executed before game is started. In your case script that would mount an ISO.

I'm going to close this issue since we will cover this by #113. This is very specific scenario and I don't know if it makes sense to add it as a standard feature to Playnite.
