### ISSUE TITLE
Columns order is not saved on List view

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#688]

**Comment by Poggles** [comment]
I would like to add to this, that the column width is also not saved.  This seems a good place to add this as a bug since fix for this should solve both issues.

Since the last release (4.5.8) the columns are always too narrow to display the game logo and title.
I have to resize them on startup every time.  

Thanks for all your efforts on this program.  It's exactly the sort of tool that people don't realise they are missing, until they stumble across it one day.

**Comment by JosefNemec** [comment]
Will be done as part of #976
