### ISSUE TITLE
Metadata download stuck on very large libraries

### ISSUE THREAD

**Issue by rezorrand** [JosefNemec/Playnite#732]
My steam library consists of over 1600 titles, and GOG has over 500 titles, when I trigger metadata download for all items, it seems to crash or get stuck at some point. Pressing cancel won't stop it, and trying to close the app causes it to hang trying to exit. Then it's possible to exit the curtain while exiting and trigger another exit with similar exit loading.

Issue can't be reproduced if data has already been loaded.

**Comment by JosefNemec** [comment]
Can you attach diagnostics package that can be created from the crash dialog? Or you can create it manually via "About" menu. Thanks

Also download may seem to be stuck, but it most probably waits on Steam metadata (since you have large Steam library). If metadata are not cached then they have to be downloaded fresh from the store and Steam store has limit of how much requests you can make per minute. If you have large library then it's more likely to run out over the request limit and then Playnite has to wait for Steam store to accept new requests. In that case download may look like it's stuck, but in reality it just waits for a while to be able to download new data.

**Comment by rezorrand** [comment]
Hi, I haven't been able to reproduce it despite forcing to redownload all (yet at least), here's the diagnostics however. Hope it is of help, though it's been a while since I got it to malfunction.

[diagnostics.zip](https://github.com/JosefNemec/Playnite/files/2288500/diagnostics.zip)

**Comment by JosefNemec** [comment]
I've made some changes to metadata download in 4.5 so it should not happen anymore. Feel free to reopen if it occurs again.
