### ISSUE TITLE
Steam Imports Not Working After 4.5 Update

### ISSUE THREAD

**Issue by epeternally** [JosefNemec/Playnite#777]
As mentioned on Discord, Playnite doesn't want to import my Steam library after updating. I've tried all the different permutations of configuration options. My account name is 'epeternally' (no quotes). I've already setup a portable 4.53 installation with a new database on my end to see if the issue was with my configuration, which I honestly expected it to be, but that does not want to import anything either. Running the import in version 4.40 works perfectly, including all of the games that aren't showing up in 4.53.

Those games are:
- Assassin's Creed Odyssey
- Hidden Folks
- Dungeons 3
- Super Treasure Arena
- Echoes III
- Looterkings
- Shadow Council: The Puppeteers

And a few other pieces of bundle fodder. Those just happen to be what was most recently added to my account.

**Comment by JosefNemec** [comment]
I can't reproduce it, I'm just setting `Account Name` to `epeternally` and `Private Account` option is disabled. Only `Assassin's Creed Odyssey` and `Shadow Council: The Puppeteers` are not imported because they are not reported by Steam API as part of your library. I would guess that Assassin's Creed is not reported because the game is not out yet, not sure what the deal with Shadow Council is. However if Steam API doesn't report that they are in your library then there's nothing I can do about it.

If you still have issues with other games then please attach diagnostics package created from "About" menu.

**Comment by JosefNemec** [comment]
I think I know what happening. There was a change in 4.50 with how installed games are being detected, there has to be actual folder with game data otherwise game is not detected as installed. That's why Odyssey is not detected, because it's not actually installed.

**Comment by epeternally** [comment]
I think you're on the wrong path. The following error appears repeatedly in my log, and would seem to be the actual culprit.

> ERROR:Failed to import games from plugin: SteamSystem.ArgumentException: An item with the same key has already been added.

It's not an issue with any particular game. Whether AC:O should import yet or not is ultimately incidental because it and Shadow Council aren't the only games that are failing. The entire Steam import process seems to be getting aborted, it always completes instantaneously, likely as a result of that error.

**Comment by JosefNemec** [comment]
Ok, thanks for an update.
