### ISSUE TITLE
Export library with metadata

### ISSUE THREAD

**Issue by Nickar124** [JosefNemec/Playnite#791]
As a user, I want to export my library with all associated/downloaded metadata so that I can sort and organize my metadata in .csv format in 3rd party applications (e.g. Microsoft excel, google docs, etc. ). 

I will know this is complete when:
I am able to select the option "Include Metadata" when running the "Export Library" command from the extensions list.
OR 
I am able to select a separate command "Export Library (With Metadata)" from the extensions list.

**Comment by JosefNemec** [comment]
I had this planned for some time now, but next version will completely change how the library database is being stored. It won't be all in single file anymore. Every game will have it's own data file (in plain JSON) and all metatada files will be stored separately in their original format.

**Comment by enfenix** [comment]
Hello! Are you still working on this export feature? Especially now that the new structure is in place and LightDB no longer serves the purpose, it would be very useful. Thank you.

**Comment by JosefNemec** [comment]
No I'm not working on this. You can already access any game image file, by just browsing the library folder structure (and there's a button in game edit dialog that open folder for specific game).

Plus I'm wondering what purpose would this server? It's not like you would be able to import those data back to Playnite.

**Comment by enfenix** [comment]
Hello! Thank you for your answer. I'm sorry if I did not specify my intention.
Since there is no mobile app, I read the CSV file with php on my homepage. This avoids me to buy games twice when I'm on the go. In addition, I have "found out" that I can specify in the "LibraryExporter.ps1" myself what I need. An HTML exporter would certainly be a nice thing, but playing it back is not relevant to me. Thanks again for this great app.

**Comment by JosefNemec** [comment]
PowerShell has [ConvertTo-Html](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-html?view=powershell-6) cmdlet you can use to convert data directly to HTML without going though csv first (I recommend copying default exporter script rather then editing original files, because they can be overwritten by an update and you will loose all changes).

**Comment by JosefNemec** [comment]
Is this still needed since Playnite no longer stores everything in single file?

**Comment by enfenix** [comment]
Hello Josef,
not for me.  I followed your advice.  Thank you.

Von unterwegs gesendet
