### ISSUE TITLE
 Mounting of ISO/BIN/CUE images for certain games

### ISSUE THREAD

**Issue by sparxooo** [JosefNemec/Playnite#797]
Hey all!

Just to pop this here to get some ideas. I do the odd bit of C# here and there so will dabble with the source myself at some time. Was debating whether this would be suitable for a plugin or would have to be integrated into the main codebase.

I have certain games that I play where I have the disk images but no physical disk. The game also retains it's install cd drive (registry, or file in game dir), so that the CD needs to be at that drive letter. The copy protection can nearly almost be bypassed by no-cd patches, but these are both untrustworthy, and sometimes poorly executed.

A nice feature would be the ability (when creating a new game entry?) to mount and then install from a CD image, once install is complete, it would unmount, and then when launching a game Playnite can automatically mount the required image to that drive letter (should only need one virtual drive letter).

Windows 8 and 10 support native ISO mounting, but looks like Windows 7 would have to use a third party tool. BIN/CUE mounting would also have to be a third party tool.

**Comment by sparxooo** [comment]
I've written a proof of concept automounting plugin (see my Github @sparxooo )

I will continue to explore functionality in the plugin, but also explore implementing this into Playnite directly.

**Comment by JosefNemec** [comment]
I'm not sure about having this as built-in feature (the plugin solution make more sense to me), but I think this could be achieved easily once we implement  #113 without additional effort (users would be able to use whatever app they want for image mounting).

The main reason against built-in support is need for 3rd party application for this to work. Depending of what application we would use, there are questions about being able to control it via API and that application being usable by all users (licensing and technical aspects not suitable for all). As you say only Windows 8+ supports image mounting (only for ISO format anyways), which is a problem because we do support Windows 7 at the moment.

Also for plugin solution I think we might need to add ability for plugins to define per game settings first. Otherwise I don't know how you would decide whether to mount the image or not and mounting image for all games might not be wanted for emulated titles. I've opened #801 for this to be added in future.

**Comment by sparxooo** [comment]
Hi Josef,

Per game plugins make sense, and also being able to handle the Pre-game launch command until everything is ready also makes good sense.

There are some open source image mounting solutions, although as you say, it makes sense as a plugin to allow users to choose if they want to install or not (a lot of the image mounting solutions install a permanent driver).

I will watch and wait :) This is a fantastic project so far!

**Comment by JosefNemec** [comment]
This should be already possible via custom game scripts, since #113 is now implemented. As said in my previous comment, making as built-in feature is not possible without having hard dependencies on other software.
