### ISSUE TITLE
Problem screen after attempting to import DRM-Free Games in portable version

### ISSUE THREAD

**Issue by Alecadabra** [JosefNemec/Playnite#81]
I'm trying to make a more user-friendly way of playing games off my portable HDD since it is shared around a bunch. Got this error after choosing all the files to use.

[Diagnostics package .zip](https://github.com/JosefNemec/Playnite/files/1236128/error.zip)

[Pastebin](https://pastebin.com/raw/SyTLtQds)

**Comment by JosefNemec** [comment]
Thanks for the report, this should be easy fix.

I'm also interested in your setup and the way you want to use Playnite with portable drive, because there might be some changes needed to properly support what you want to do. Specifically there might be some issues if you try to run game which changes it's installation directory from PC to PC (there's currently no support for relative paths).

**Comment by JosefNemec** [comment]
Released in 1.1
