### ISSUE TITLE
Adding "Uplay" to "Source" field does not add game to Uplay section

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [JosefNemec/Playnite#816]
I noticed "Uplay" is added to the "Source" field for games auto imported from Uplay. However when I add this tag to the field myself when manually adding a game it is only listed at the top. Even using the left hand panel filters does not list those games that have "Source" as Uplay. Version 4.58.

**Comment by JosefNemec** [comment]
Are you actually using `Source` property on filter panel or `Libraries`? `Source` field only affects filtering when using `Source` filter field. `Libraries` filter specifically lists only games that were imported automatically because they are tied to the library plugin. The same goes for why the game is not added to Uplay group, because technically it's still a custom game and you can't currently group by `Source` field (only by `Library`).

Issue #318 will add an option to actually group by `Source` fields, which will fix your use case.
