### ISSUE TITLE
Exlcusion filtering

### ISSUE THREAD

**Issue by Poggles** [JosefNemec/Playnite#837]
Sometimes you want to see every single game to check for duplicates etc, it would be useful to start typing a title and see games that you have installed/uninstalled AND hidden titles at the same time.

**Comment by Mates1500** [comment]
Is this being worked on? I could take a look at it.

**Comment by JosefNemec** [comment]
I'm not working on it, feel free to look at it.

**Comment by Poggles** [comment]
Depending on whether further (large) changes are already planned for the way filtering works, a quick fix could be to add another checkbox for "everything including hidden".

I really appreciate the work you guys are doing on this.

**Comment by JosefNemec** [comment]
I think the easier solution would be to change the checkbox to three-state one:
- checked: show only hidden
- intermediate: don't show hidden
- unchecked: show hidden as well

That could be done for other filters as well (like Installed, Uninstalled).

**Comment by Mates1500** [comment]
I've created a pull request suggesting consolidation of the entire checkbox logic with some questions still left unanswered, your feedback would be appreciated, please check out #881

**Comment by Poggles** [comment]
I like this suggestion.  It gives me all the functionality I felt was missing in the filtering.  You could even extend this to the textbox filters (a checkbox next to the textbox to indicate if the text input is to be exclusively or inclusively applied).

I was picturing in my head a way of displayed "AND / OR" filtering to users similarly to the filters in isthereanydeal.com but I couldn't think of a way to show it concisely in the current UI.

The use of the different checkbox options seems ideal to me.  I also agree with the "reset filters" and tooltip idea.  I am not certain if the "Enable Inclusive" icon is clear enough without tooltips.  What about some subtle colouring:

1. Disable  - slightly greyed (as in your pic in #881)
2. Enable Inclusive - Normal white
3. Enable Exclusive - Hint of red?

Colour might be excessive to be honest.

**Comment by jpflanegan** [comment]
I have given this much thought and I think I have a workable solution. Not sure how easy it is to implement though. I found showing or not showing hidden games was causing problems with filtering and knowing what would appear or not.

These are the changes I would make

Add a "Show Hidden Games" toggle switch which can be on or off
Change all other checkbox UI functionality so that first click on a checkbox will be a solid checkbox, second click will be a tick, third click will clear it.
If a checkbox has a solid square then a game only has to meet one of the checkbox filters with a solid square to be included in the results
If a checkbox is ticked then the game has to meet all of the checkbox filters with a tick to be included in the results
An example of filter below
By default you will see your library except for hidden games.
Click Show Hidden Games you will see everything.
Single click Installed making it a solid square you will still see everything.
Single click Uninstalled making it a solid square you will still see everything.
Single click Installed making it a tick will show installed games as well as installed hidden games.
Click Show Hidden Games will show installed games but not installed hidden games.
Single click Uninstalled making it a tick will show nothing.
Click Show Hidden Games will show noting.
Click Installed which will clear it will show uninstalled games as well as uninstalled hidden games.
Click Hidden twice making it a tick will show only hidden and uninstalled games.

I have sat and thought through how selecting different options might return results and this seems to be the best way to have an AND and an OR option together for filtering. If I had the skill to code this to test I would do it but I am still learning. This could be incorporated for each filtering field and should give satisfactory results.

I also feel it fits with the rest of the UI experience when selecting multiple games and want to set a tag or category and only if all of the selected items have that tag will it show a tick otherwise it shows a solid checkbox.

**Comment by JosefNemec** [comment]
Some other suggestions to this have been posted [on forums](https://playnite.link/forum/thread-75.html).

**Comment by JosefNemec** [comment]
Will be done with filtering rework in #1895
