### ISSUE TITLE
Epic Store library support

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#845]
https://arstechnica.com/gaming/2018/12/epic-undercuts-steam-with-new-store-that-gives-devs-more-money/

**Comment by effcol** [comment]
Don't know if this helps, but it was previously said that an issue with importing Epic Game Launcher games was that you couldn't launch them from outside the Epic Gasmes Launcher.

Turns out there is a way, if you add the command ling argument `-EpicPortal` To each game int he launcher.

source:
https://pcgamingwiki.com/wiki/Subnautica#Launching_Game_via_Steam_when_purchased_through_Epic_Games_Store.2FLauncher

**Comment by JosefNemec** [comment]
I have Epic support basically finished so there's no need to analyze it any further.

**Comment by JosefNemec** [comment]
Released in 4.70

**Comment by Stuntaneous** [comment]
Just updating this: 

The "-EpicPortal" argument didn't work for me but making a desktop shortcut through the Epic Launcher and using the URL it contains did, e.g. World War Z gave me "com.epicgames.launcher://apps/Wombat?action=launch&silent=true"

**Comment by JosefNemec** [comment]
We already use `com.epicgames.launcher` URLs to launch games.
