### ISSUE TITLE
Filter menu not appearing after going into application settings

### ISSUE THREAD

**Issue by SnoutBaron** [JosefNemec/Playnite#858]
To reproduce, 

-Start Playnite. 
-Click on the filter button, filter will work. Collapse the filter menu.
-Open Playnite menu, open Settings. Settings window appears, close Settings window using X.
-Try open filter menu again. It will not open.

The only way to fix the issue at the moment is to restart Playnite.

**Comment by TheCakeIsNaOH** [comment]
1. The filter menu will start working again if settings is opened again, then closed with the save or cancel buttons instead of the X.
2. This bug does not affect the classic theme in any of the versions I have tested.
3. This bug does affect the modern theme all the way back to 3.0 when the modern theme was added.
4. It also prevents closing of the filter menu, not only opening.
5. If the filter menu is stuck open, filtering works fine, it is just closing it that does not work.

**Comment by JosefNemec** [comment]
Fixed in 4.64
