### ISSUE TITLE
Standart steam covers

### ISSUE THREAD

**Issue by evgdovg1996** [JosefNemec/Playnite#86]
Currenly, the narrow and elongated ratio of the cover is very inconvenient, since it's hard to find a normal image for the game. Please make a standard ratio, as on the steam-covers (460x215px)

**Comment by JosefNemec** [comment]
Current size was chosen to correspond with standard game cover art sizes. This was done in cases where you would download cover manually from other sources (for example IGDB, which you can when editing game using "Download metadata" button), or if you add non-Steam game, which would have that standard aspect ratio. Having default Steam images mixed with standard cover art, didn't look very nice. That's why Steam and GOG covers are modified to fit into this "standard".

I will adding option to keep unmodified images in issue #36.
