### ISSUE TITLE
Change background in the list categories

### ISSUE THREAD

**Issue by Evene174** [JosefNemec/Playnite#87]
It would be cool if it was possible to change standart black background for non-clients games

**Comment by JosefNemec** [comment]
Will be done in 3.0 with as part of theming support.

**Comment by evgdovg1996** [comment]
@Thanks for the response and support!
Tell me, are you planning to add an option to turn off the small icons?
To get something like this:
https://i.imgur.com/Rn9HdCx.png
I think this would greatly improve the speed of the program for those who do not need them.
In my opinion, icons are not really needed in 'list' category because if user want he can make standard steam-covers like this, which look cool:
https://i.imgur.com/3aIQXoO.png

**Comment by JosefNemec** [comment]
You will be able to do that by changing the skin which will not include icons.

**Comment by JosefNemec** [comment]
Option to turn off icons has been added in newly released version 2.0

**Comment by evgdovg1996** [comment]
@JosefNemec Please,also could you make an option to turn off the icons in the game description?
The user can make empty picture, but then the name of the game is shifted relative to the other columns, and it does not look very nice.
https://imgur.com/a/6NBMa

**Comment by JosefNemec** [comment]
Added in 3.0
