### ISSUE TITLE
"Profiles Features Limited" Steam games not being imported

### ISSUE THREAD

**Issue by TechLibrarian** [JosefNemec/Playnite#910]
Hi Josef!
I noticed that the game Shadowlings is missing in Playnite. My Steam account is set to public and most (it seems) other games (added before and since) are showing. I have over 1000, so I haven't combed through. Found this one by fluke.
Diagnostic: d46effb4-9781-45d9-827f-ebe35f3b538a
See screenshot:
![missing game](https://user-images.githubusercontent.com/35371465/50569965-231fdb80-0d3c-11e9-8fa3-cf5467bf64f6.png)

**Comment by JosefNemec** [comment]
This might be the same as #639

**Comment by darklinkpower** [comment]
I just noticed the I have some missing games and I think I know why. Profile limited games don't show in Playnite because they don't get listed in the Steam Web Api when using `GetOwnedGames`

![imagen](https://user-images.githubusercontent.com/1389286/67621758-a719e700-f7d8-11e9-95d0-ca20bf1b067a.png)

A few of the games I have that don't get listed: 
https://store.steampowered.com/app/898450/UBERMOSHSANTICIDE/
https://store.steampowered.com/app/1029980/UBERMOSH_Vol7/

The game @TechLibrarian posted:
https://store.steampowered.com/app/883020/Shadowlings/
Also has profile features limited.

I don't know how this could be solved, perhaps adding an input box where one could write the steam game id for Playnite to be added but even that way it would be difficult since you could easily miss some games in the process if you have a large library.

**Comment by JosefNemec** [comment]
Good to know what's causing this, but sadly I can't do anything about it right now. If API doesn't report it as part of your library then we can't import it.

Alternative would be to completely rework the import system to parse your profile page, but that has some disadvantages, because that page includes other items like DLCs, movies etc. We would have to add separate backend component that would filter those out.

Or add an option to manually import game as you propose.

**Comment by darklinkpower** [comment]
Yeah that's why I thought of that "solution" since it wouldn't require a heavy rework on how games are parsed and it could solve other problems people have, for example I've seen requests for adding family shared games and this solution could help them add the games they want to Playnite (or they could login once in the other profile in Playnite but... it wouldn't hurt to have this option)

**Comment by darklinkpower** [comment]
Found something interesting that might help with this issue. If you are logged in in your browser, this link gives a list of every owned game, games in wishlist and a lot of other interesting data.

https://store.steampowered.com/dynamicstore/userdata/

The `rgOwnedApps` lists all games including profile limited games.

**Comment by JosefNemec** [comment]
I know about that endpoint, but the problem is that they list everything there, including DLCs, movies and other stuff. We would have to filter those out, which means doing API request for every single item in your library, which would slow down import noticeably.

It would most definitely require some additional backend part to store the list of items to be ignored during import (GOG does that in Galaxy 2).

I'll reconsider it for future releases, but I'm definitely not reworking Steam import for Playnite 7.

**Comment by JosefNemec** [comment]
I've added workaround for this to [Steam troubleshooting](https://github.com/JosefNemec/Playnite/wiki/Steam-troubleshooting#some-games-not-being-imported) wiki page.

**Comment by ArtexJay** [comment]
Strange that Playnite is unable to see these games, while GOG 2.0 has managed to get all games including those listed as "Profile Feature Limited"

**Comment by darklinkpower** [comment]
@ArtexJay That's not how they do it at all. They parse your steam profile's game page and don't use the steam API and  the `GetOwnedGames` API request. https://github.com/FriendsOfGalaxy/galaxy-integration-steam/blob/master/src/backend.py#L169

So it's not strange because that's how the API works and they do it another way, hence the different results in this case.

**Comment by JosefNemec** [comment]
Will be done via #910

**Comment by JosefNemec** [comment]
Fixed in 8.9

**Comment by TheRhanderson** [comment]
If it helps...

Add &skip_unvetted_apps=false to url

https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=XXXXXXXXXXXXXXXXXXXXXXXX&steamid=XXXXXXXXXXXXXXX&format=json&skip_unvetted_apps=false

"Learning/Limited" games will be displayed.
