### ISSUE TITLE
Duplicate games or wrong name 

### ISSUE THREAD

**Issue by L-anonyme** [JosefNemec/Playnite#915]
I have some steam games that are shown in doubles but I don't know why. These are GTA III, Vice City and San Andreas. I'm thinking it's because the game folder contains two.exe.

![capture](https://user-images.githubusercontent.com/31326745/50727779-11fe1280-1120-11e9-92c9-49622a8eda0b.PNG)

I also have the BlackLight game that becomes SteamGame and SteamWorks Common Redistributable
![capture1](https://user-images.githubusercontent.com/31326745/50727780-1296a900-1120-11e9-831a-c215ab55e3e8.PNG)
![capture2](https://user-images.githubusercontent.com/31326745/50727781-1296a900-1120-11e9-8e0b-e1f6592fa4c5.PNG)

These are the only bugs noticed at the moment.

**Comment by JosefNemec** [comment]
All of those duplicates are reported by Steam API and that's why they are imported (I don't know why is Steam reporting them in public library API). F2P games like BlackLight will be imported if you installed the game at least once, again because the Steam API is reporting it as part of your library. There are plans to add ignore list for games you don't want to be imported in #565, but for now you'll have hide those (from righ-click menu).

**Comment by L-anonyme** [comment]
Thanks to your quick answer

**Comment by psychonic** [comment]
> All of those duplicates are reported by Steam API and that's why they are imported (I don't know why is Steam reporting them in public library API)

In the case of those GTA ones, one set of them is the Windows version, and the other is the Mac version. They are on Steam as separate games instead of one multi-platform one, but you get access to both platforms when buying one.
