### ISSUE TITLE
Requesting Moonlight support

### ISSUE THREAD

**Issue by clee** [JosefNemec/Playnite#952]
[Moonlight streaming](https://moonlight-stream.org/) works great for letting me play my Windows games on Linux; it would be awesome to be able to launch my Moonlight-streamable games directly from Playnite!

**Comment by JosefNemec** [comment]
We should probably do this together with #883 and #712. Or at least implement it in a way that would support multiple streaming apps via our plugin API.

**Comment by genova447** [comment]
For now, you can manually add the ability on a per-game basis : o

Here's the help menu from Moonlight: 
![image](https://user-images.githubusercontent.com/36210357/94304897-54900000-ff3e-11ea-9b11-6762178b0708.png)

so you would call: Moonlight.exe stream pcnamehere "gamenamehere"

Or shown perhaps better (in my particular case anyway): 
![image](https://user-images.githubusercontent.com/36210357/94305560-5d350600-ff3f-11ea-80c8-fe00ffd4789b.png)
To note is that VGEN is just the name of my own host (you can also use IP of the host)
And in my case the name I gave the game in Playnite, matches exactly what the game is in Moonlight, hence I use {Name} - otherwise if they differed even a little, you'd have to write out the full name as it is called in Moonlight.

Maybe not desirable this way, but I thought it might be nice to share here regardless.

**Comment by JosefNemec** [comment]
Is this still necessary when [this](https://github.com/cgarst/gamestream_launchpad) exists?

**Comment by clee** [comment]
@JosefNemec Seems like a decent solution! I'll close this out.
